import { beforeEach, describe, expect, it, vi } from 'vitest';

import type { Env } from '../src/index';
import type {
  TranscriptBundle,
  TranscriptFetchCallbacks,
  TranscriptProviderOptions,
} from '../src/services/youtube';

const {
  fetchTranscriptBundleMock,
  generateTranscriptSectionsMock,
  summarizeQuickTranscriptSectionMock,
  translateTranscriptSectionToZhMock,
} = vi.hoisted(() => ({
  fetchTranscriptBundleMock: vi.fn(),
  generateTranscriptSectionsMock: vi.fn(),
  summarizeQuickTranscriptSectionMock: vi.fn(),
  translateTranscriptSectionToZhMock: vi.fn(),
}));

vi.mock('../src/services/youtube', async () => {
  const actual = await vi.importActual<typeof import('../src/services/youtube')>('../src/services/youtube');
  return {
    ...actual,
    fetchTranscriptBundle: fetchTranscriptBundleMock,
  };
});

vi.mock('../src/services/gemini', async () => {
  const actual = await vi.importActual<typeof import('../src/services/gemini')>('../src/services/gemini');
  return {
    ...actual,
    generateTranscriptSections: generateTranscriptSectionsMock,
    summarizeQuickTranscriptSection: summarizeQuickTranscriptSectionMock,
    translateTranscriptSectionToZh: translateTranscriptSectionToZhMock,
  };
});

import { handleGenerateRoute } from '../src/routes/generate';

function createBundle(overrides: Partial<TranscriptBundle> = {}): TranscriptBundle {
  const chunks = overrides.chunks ?? [
    { start: 0, end: 15, text: 'Opening line' },
    { start: 15, end: 30, text: 'Closing line' },
  ];

  return {
    videoId: 'xRh2sVcNXQ8',
    sourceTitle: 'Test title',
    sourceAuthor: 'Test author',
    channelId: 'channel',
    languageCode: 'en',
    languageName: 'English',
    isAutoGenerated: true,
    durationSeconds: overrides.durationSeconds ?? 30,
    viewCount: 42,
    thumbnailUrl: 'https://example.com/thumb.jpg',
    segments: [],
    chunks,
    transcriptText: overrides.transcriptText ?? chunks.map((chunk) => chunk.text).join('\n'),
    ...overrides,
  };
}

function createExecutionContext() {
  const tasks: Promise<unknown>[] = [];

  return {
    ctx: {
      waitUntil(promise: Promise<unknown>) {
        tasks.push(Promise.resolve(promise));
      },
      passThroughOnException() {
      },
    } as ExecutionContext,
    async waitForAll() {
      await Promise.allSettled(tasks);
    },
  };
}

describe('handleGenerateRoute', () => {
  beforeEach(() => {
    fetchTranscriptBundleMock.mockReset();
    generateTranscriptSectionsMock.mockReset();
    summarizeQuickTranscriptSectionMock.mockReset();
    translateTranscriptSectionToZhMock.mockReset();
  });

  it('passes Supadata transcript provider options to the fetcher', async () => {
    const bundle = createBundle();

    fetchTranscriptBundleMock.mockImplementation(async (
      _input: string,
      _callbacks?: TranscriptFetchCallbacks,
      _signal?: AbortSignal,
      _options?: TranscriptProviderOptions,
    ) => bundle);
    generateTranscriptSectionsMock.mockResolvedValue({
      sections: [
        {
          startLabel: '00:00',
          endLabel: '00:30',
          subtitle: 'Section 1',
          summary: 'Summary',
          transcript: '[00:00] Opening line\n[00:15] Closing line',
        },
      ],
      model: 'test-sections-model',
    });
    summarizeQuickTranscriptSectionMock.mockResolvedValue({
      section: {
        startLabel: '00:00',
        endLabel: '00:30',
        subtitle: 'Section 1',
        summary: 'Summary',
        transcript: '[00:00] Opening line\n[00:15] Closing line',
      },
      question: 'What happened?',
      answer: 'A short intro and outro.',
      questionZh: '讲了什么？',
      answerZh: '先开场，再收尾。',
      model: 'test-summary-model',
    });

    const request = new Request('https://example.com/api/generate', {
      method: 'POST',
      body: JSON.stringify({
        youtubeUrl: 'https://www.youtube.com/watch?v=xRh2sVcNXQ8',
        readingMode: 'quick',
      }),
      headers: {
        'content-type': 'application/json',
      },
    });
    const env: Env = {
      GEMINI_API_KEY: 'test-gemini-key',
      SUPADATA_API_KEY: 'test-supadata-key',
      SUPADATA_TRANSCRIPT_MODE: 'auto',
    };
    const { ctx, waitForAll } = createExecutionContext();

    const response = await handleGenerateRoute(request, env, ctx);
    const bodyPromise = response.text();
    await waitForAll();

    expect(fetchTranscriptBundleMock).toHaveBeenCalledTimes(1);
    expect(fetchTranscriptBundleMock).toHaveBeenCalledWith(
      'https://www.youtube.com/watch?v=xRh2sVcNXQ8',
      expect.any(Object),
      request.signal,
      {
        supadataApiKey: 'test-supadata-key',
        supadataMode: 'auto',
      },
    );

    const body = await bodyPromise;
    expect(body).toContain('event: done');
  });

  it('streams section previews first and then replaces them with translated dialogue in full mode', async () => {
    const bundle = createBundle();

    fetchTranscriptBundleMock.mockResolvedValue(bundle);
    generateTranscriptSectionsMock.mockResolvedValue({
      titleTranslationZh: '测试标题',
      summaryZh: '测试高亮',
      summary: 'Highlight sentence.',
      speakers: ['Host'],
      sections: [
        {
          startLabel: '00:00',
          endLabel: '00:30',
          subtitle: 'Opening',
          summary: 'Covers the opening lines.',
          topicTitleZh: '开场判断',
          topicSummaryZh: '先交代核心背景。',
          subtitleZh: '开场',
          summaryZh: '概述开场内容。',
          transcript: '',
        },
      ],
      model: 'test-sections-model',
    });
    translateTranscriptSectionToZhMock.mockResolvedValue({
      section: {
        startLabel: '00:00',
        endLabel: '00:30',
        subtitle: 'Opening',
        summary: 'Covers the opening lines.',
        topicTitleZh: '开场判断',
        topicSummaryZh: '先交代核心背景。',
        subtitleZh: '开场',
        summaryZh: '概述开场内容。',
        transcript: '[00:00] Opening line\n[00:15] Closing line',
      },
      turns: [
        { timestamp: '00:00', speaker: 'Host', textZh: '开场白。' },
        { timestamp: '00:15', speaker: 'Host', textZh: '结束语。' },
      ],
      groups: [
        {
          topicTitleZh: '投资判断',
          turns: [
            { timestamp: '00:00', speaker: 'Host', textZh: '开场白。' },
            { timestamp: '00:15', speaker: 'Host', textZh: '结束语。' },
          ],
        },
      ],
      model: 'test-dialogue-model',
    });

    const request = new Request('https://example.com/api/generate', {
      method: 'POST',
      body: JSON.stringify({
        youtubeUrl: 'https://www.youtube.com/watch?v=xRh2sVcNXQ8',
        readingMode: 'full',
      }),
      headers: {
        'content-type': 'application/json',
      },
    });
    const env: Env = {
      GEMINI_API_KEY: 'test-gemini-key',
    };
    const { ctx, waitForAll } = createExecutionContext();

    const response = await handleGenerateRoute(request, env, ctx);
    const bodyPromise = response.text();
    await waitForAll();

    const body = await bodyPromise;
    expect(body).toContain('"target":"dialogue","html":"<div class=\\"dialogue-section-block\\" data-dialogue-section-id=\\"dialogue-section-1\\">');
    expect(body).toContain('Gemini 正在打磨中文表达');
    expect(body).toContain('会优先保持自然、直接、适合阅读的中文语感。');
    expect(body).toContain('"target":"dialogue-replace"');
    expect(body).toContain('"sectionId":"dialogue-section-1"');
    expect(body).toContain('section-theme-title');
    expect(body).toContain('section-theme-summary');
    expect(body).toContain('section-theme-divider');
    expect(body).toContain('开场判断');
    expect(body).toContain('先交代核心背景。');
    expect(body).not.toContain('内容翻译中');
    expect(body).toContain('dialogue-subtopic-title');
    expect(body).toContain('投资判断');
    expect(body).toContain('开场白。');
  });

  it('hides sections that are fully merged into the previous dialogue section', async () => {
    const bundle = createBundle({
      durationSeconds: 45,
      chunks: [
        { start: 0, end: 15, text: 'Opening line' },
        { start: 15, end: 30, text: 'Middle line' },
        { start: 30, end: 45, text: 'Closing line' },
      ],
    });

    fetchTranscriptBundleMock.mockResolvedValue(bundle);
    generateTranscriptSectionsMock.mockResolvedValue({
      titleTranslationZh: '测试标题',
      summaryZh: '测试高亮',
      summary: 'Highlight sentence.',
      speakers: ['Host'],
      sections: [
        {
          startLabel: '00:00',
          endLabel: '00:15',
          subtitle: 'Opening',
          summary: 'Covers the opening lines.',
          topicTitleZh: '开场判断',
          topicSummaryZh: '先交代核心背景。',
          subtitleZh: '开场',
          summaryZh: '概述开场内容。',
          transcript: '',
        },
        {
          startLabel: '00:15',
          endLabel: '00:30',
          subtitle: 'Continuation',
          summary: 'Continues the same speaker.',
          topicTitleZh: '延续判断',
          topicSummaryZh: '补上一句完整表达。',
          subtitleZh: '延续',
          summaryZh: '补上一句完整表达。',
          transcript: '',
        },
      ],
      model: 'test-sections-model',
    });
    translateTranscriptSectionToZhMock
      .mockResolvedValueOnce({
        section: {
          startLabel: '00:00',
          endLabel: '00:15',
          subtitle: 'Opening',
          summary: 'Covers the opening lines.',
          topicTitleZh: '开场判断',
          topicSummaryZh: '先交代核心背景。',
          subtitleZh: '开场',
          summaryZh: '概述开场内容。',
          transcript: '[00:00] Opening line',
        },
        turns: [
          { timestamp: '00:00', speaker: 'Host', textZh: '这是上一节。' },
        ],
        groups: [
          {
            topicTitleZh: '投资判断',
            turns: [
              { timestamp: '00:00', speaker: 'Host', textZh: '这是上一节。' },
            ],
          },
        ],
        model: 'test-dialogue-model',
      })
      .mockResolvedValueOnce({
        section: {
          startLabel: '00:15',
          endLabel: '00:30',
          subtitle: 'Continuation',
          summary: 'Continues the same speaker.',
          topicTitleZh: '延续判断',
          topicSummaryZh: '补上一句完整表达。',
          subtitleZh: '延续',
          summaryZh: '补上一句完整表达。',
          transcript: '[00:15] Closing line',
        },
        turns: [
          { timestamp: '00:15', speaker: 'Host', textZh: '这是并入的下一节。' },
        ],
        groups: [
          {
            topicTitleZh: '投资判断',
            turns: [
              { timestamp: '00:15', speaker: 'Host', textZh: '这是并入的下一节。' },
            ],
          },
        ],
        model: 'test-dialogue-model',
      });

    const request = new Request('https://example.com/api/generate', {
      method: 'POST',
      body: JSON.stringify({
        youtubeUrl: 'https://www.youtube.com/watch?v=xRh2sVcNXQ8',
        readingMode: 'full',
      }),
      headers: {
        'content-type': 'application/json',
      },
    });
    const env: Env = {
      GEMINI_API_KEY: 'test-gemini-key',
    };
    const { ctx, waitForAll } = createExecutionContext();

    const response = await handleGenerateRoute(request, env, ctx);
    const bodyPromise = response.text();
    await waitForAll();

    const body = await bodyPromise;
    expect(body).toContain('"sectionId":"dialogue-section-2"');
    expect(body).toContain('<div class=\\"dialogue-section-block\\" data-dialogue-section-id=\\"dialogue-section-2\\" hidden aria-hidden=\\"true\\"></div>');
    expect(body).toContain('这是上一节。这是并入的下一节。');
    expect(body).not.toContain('已并入上一节');
    expect(body).not.toContain('为保持说话连续性，这一小段内容已合并到上一节展示。');
  });

  it('keeps the quick overview Chinese section copy in full-mode previews when section slicing falls back to manual windows', async () => {
    const bundle = createBundle({
      durationSeconds: 66,
      chunks: [
        { start: 0, end: 30, text: 'Opening line' },
        { start: 60, end: 66, text: 'Closing line' },
      ],
    });

    fetchTranscriptBundleMock.mockResolvedValue(bundle);
    generateTranscriptSectionsMock.mockResolvedValue({
      titleTranslationZh: '测试标题',
      summaryZh: '测试高亮',
      summary: 'Highlight sentence.',
      speakers: ['Host'],
      sections: [
        {
          startLabel: '00:01',
          endLabel: '01:06',
          subtitle: '开场判断',
          summary: '先交代核心背景。',
          transcript: '',
        },
      ],
      model: 'test-sections-model',
    });
    translateTranscriptSectionToZhMock.mockImplementation(async (
      _bundle,
      section,
    ) => ({
      section: {
        ...section,
        topicTitleZh: '最终标题',
        topicSummaryZh: '最终摘要。',
        subtitleZh: '最终标题',
        summaryZh: '最终摘要。',
      },
      turns: [
        { timestamp: '00:00', speaker: 'Host', textZh: '开场白。' },
      ],
      groups: [
        {
          topicTitleZh: '最终分组',
          turns: [
            { timestamp: '00:00', speaker: 'Host', textZh: '开场白。' },
          ],
        },
      ],
      model: 'test-dialogue-model',
    }));

    const request = new Request('https://example.com/api/generate', {
      method: 'POST',
      body: JSON.stringify({
        youtubeUrl: 'https://www.youtube.com/watch?v=xRh2sVcNXQ8',
        readingMode: 'full',
      }),
      headers: {
        'content-type': 'application/json',
      },
    });
    const env: Env = {
      GEMINI_API_KEY: 'test-gemini-key',
    };
    const { ctx, waitForAll } = createExecutionContext();

    const response = await handleGenerateRoute(request, env, ctx);
    const bodyPromise = response.text();
    await waitForAll();

    const body = await bodyPromise;
    expect(body).toContain('开场判断');
    expect(body).toContain('先交代核心背景。');
    expect(body).toContain('最终标题');
    expect(body).not.toContain('内容翻译中');
    expect(body).not.toContain('该片段覆盖 00:00 到 01:06 的原文内容。');
  });
});
