import { describe, expect, it } from 'vitest';

import {
  buildFirstCallTranscriptBundle,
  buildManualTranscriptSections,
  buildTranscriptSectionsFromTimestampBoundaries,
  buildTranscriptSliceBundles,
  mergeDialogueSectionBoundary,
  mergeQuestionAnswerSplitSections,
  shouldSliceFirstGeminiCall,
  usesGeminiReadingFlow,
} from '../src/routes/generate';
import type { TranscriptDialogueSliceResult } from '../src/services/gemini';
import type { TranscriptBundle } from '../src/services/youtube';

function createBundle(
  overrides: Partial<TranscriptBundle> = {},
): TranscriptBundle {
  const chunks = overrides.chunks ?? [
    { start: 0, end: 30, text: 'Opening line' },
    { start: 60, end: 90, text: 'Second line' },
  ];

  return {
    videoId: 'abc123xyz00',
    sourceTitle: 'Test title',
    sourceAuthor: 'Test author',
    channelId: 'channel',
    languageCode: 'en',
    languageName: 'English',
    isAutoGenerated: true,
    durationSeconds: overrides.durationSeconds ?? Math.ceil(chunks.at(-1)?.end ?? 0),
    viewCount: 10,
    thumbnailUrl: 'https://example.com/thumb.jpg',
    segments: [],
    chunks,
    transcriptText: overrides.transcriptText ?? chunks.map((chunk) => chunk.text).join('\n'),
    ...overrides,
  };
}

function createDialogueSlice(
  overrides: {
    section?: Partial<TranscriptDialogueSliceResult['section']>;
    turns?: TranscriptDialogueSliceResult['turns'];
    groups?: TranscriptDialogueSliceResult['groups'];
    model?: string;
  } = {},
): TranscriptDialogueSliceResult {
  const turns = overrides.turns ?? [
    { timestamp: '00:00', speaker: 'Host', textZh: 'Example line' },
  ];
  return {
    section: {
      startLabel: '00:00',
      endLabel: '01:00',
      subtitle: 'Section',
      summary: 'Summary',
      transcript: '[00:00] Example line',
      ...overrides.section,
    },
    turns,
    groups: overrides.groups ?? [],
    model: overrides.model ?? 'test-model',
  };
}

describe('shouldSliceFirstGeminiCall', () => {
  it('returns true when transcript duration exceeds 30 minutes', () => {
    expect(shouldSliceFirstGeminiCall(createBundle({
      durationSeconds: 30 * 60 + 1,
    }))).toBe(true);
  });

  it('returns false when transcript duration is within 30 minutes', () => {
    expect(shouldSliceFirstGeminiCall(createBundle({
      durationSeconds: 30 * 60,
    }))).toBe(false);
  });
});

describe('usesGeminiReadingFlow', () => {
  it('uses Gemini flow for quick mode', () => {
    expect(usesGeminiReadingFlow('quick')).toBe(true);
  });

  it('uses Gemini flow for full mode', () => {
    expect(usesGeminiReadingFlow('full')).toBe(true);
  });
});

describe('buildFirstCallTranscriptBundle', () => {
  it('keeps the full transcript when duration does not exceed 30 minutes', () => {
    const bundle = createBundle({
      durationSeconds: 20 * 60,
    });

    expect(buildFirstCallTranscriptBundle(bundle)).toBe(bundle);
  });

  it('slices the transcript to the first 30 minutes when duration exceeds the limit', () => {
    const bundle = createBundle({
      durationSeconds: 75 * 60,
      chunks: [
        { start: 0, end: 60, text: 'Opening line' },
        { start: 29 * 60 + 45, end: 30 * 60 + 20, text: 'Still inside the first half hour' },
        { start: 30 * 60, end: 30 * 60 + 30, text: 'Should be excluded' },
        { start: 50 * 60, end: 50 * 60 + 30, text: 'Later line' },
      ],
    });

    expect(buildFirstCallTranscriptBundle(bundle)).toEqual({
      ...bundle,
      durationSeconds: 30 * 60,
      chunks: [
        { start: 0, end: 60, text: 'Opening line' },
        { start: 29 * 60 + 45, end: 30 * 60, text: 'Still inside the first half hour' },
      ],
      transcriptText: 'Opening line\nStill inside the first half hour',
    });
  });
});

describe('buildManualTranscriptSections', () => {
  it('builds fixed 20-minute sections from the full transcript', () => {
    const bundle = createBundle({
      durationSeconds: 65 * 60,
      chunks: [
        { start: 5, end: 30, text: 'Opening line' },
        { start: 19 * 60 + 50, end: 20 * 60 + 10, text: 'End of first window' },
        { start: 20 * 60 + 15, end: 20 * 60 + 40, text: 'Start of second window' },
        { start: 40 * 60 + 5, end: 40 * 60 + 30, text: 'Start of third window' },
        { start: 64 * 60 + 10, end: 64 * 60 + 55, text: 'Final line' },
      ],
    });

    expect(buildManualTranscriptSections(bundle)).toEqual([
      {
        startLabel: '00:00',
        endLabel: '20:00',
        subtitle: 'Transcript Section 1',
        summary: 'Transcript content from 00:00 to 20:00.',
        transcript: '[00:05] Opening line\n[19:50] End of first window',
      },
      {
        startLabel: '20:00',
        endLabel: '40:00',
        subtitle: 'Transcript Section 2',
        summary: 'Transcript content from 20:00 to 40:00.',
        transcript: '[20:15] Start of second window',
      },
      {
        startLabel: '40:00',
        endLabel: '01:00:00',
        subtitle: 'Transcript Section 3',
        summary: 'Transcript content from 40:00 to 01:00:00.',
        transcript: '[40:05] Start of third window',
      },
      {
        startLabel: '01:00:00',
        endLabel: '01:04:55',
        subtitle: 'Transcript Section 4',
        summary: 'Transcript content from 01:00:00 to 01:04:55.',
        transcript: '[01:04:10] Final line',
      },
    ]);
  });
});

describe('buildTranscriptSectionsFromTimestampBoundaries', () => {
  it('rebuilds exact section transcript slices from Gemini timestamp boundaries', () => {
    const bundle = createBundle({
      durationSeconds: 4 * 60,
      chunks: [
        { start: 5, end: 20, text: 'Opening line' },
        { start: 65, end: 90, text: 'Follow-up question' },
        { start: 125, end: 140, text: 'Main answer' },
        { start: 190, end: 210, text: 'Closing takeaway' },
      ],
    });

    expect(buildTranscriptSectionsFromTimestampBoundaries(bundle, [
      {
        startLabel: '00:05',
        endLabel: '01:05',
        subtitle: 'Opening setup',
        summary: 'Frames the topic and raises the first question.',
      },
      {
        startLabel: '02:05',
        endLabel: '03:10',
        subtitle: 'Answer and close',
        summary: 'Responds to the question and lands the takeaway.',
      },
    ])).toEqual([
      {
        startLabel: '00:05',
        endLabel: '01:05',
        subtitle: 'Opening setup',
        summary: 'Frames the topic and raises the first question.',
        transcript: '[00:05] Opening line\n[01:05] Follow-up question',
      },
      {
        startLabel: '02:05',
        endLabel: '03:10',
        subtitle: 'Answer and close',
        summary: 'Responds to the question and lands the takeaway.',
        transcript: '[02:05] Main answer\n[03:10] Closing takeaway',
      },
    ]);
  });
});

describe('buildTranscriptSliceBundles', () => {
  it('splits a long transcript bundle into contiguous request slices', () => {
    const bundle = createBundle({
      durationSeconds: 46 * 60,
      chunks: [
        { start: 5, end: 20, text: 'Opening line' },
        { start: 17 * 60 + 20, end: 17 * 60 + 50, text: 'Still in first slice' },
        { start: 18 * 60 + 10, end: 18 * 60 + 40, text: 'Second slice begins' },
        { start: 35 * 60 + 15, end: 35 * 60 + 45, text: 'Still in second slice' },
        { start: 36 * 60 + 5, end: 36 * 60 + 30, text: 'Third slice begins' },
      ],
    });

    expect(buildTranscriptSliceBundles(bundle)).toEqual([
      {
        ...bundle,
        durationSeconds: 17 * 60 + 50,
        chunks: [
          { start: 5, end: 20, text: 'Opening line' },
          { start: 17 * 60 + 20, end: 17 * 60 + 50, text: 'Still in first slice' },
        ],
        transcriptText: 'Opening line\nStill in first slice',
      },
      {
        ...bundle,
        durationSeconds: 35 * 60 + 45,
        chunks: [
          { start: 18 * 60 + 10, end: 18 * 60 + 40, text: 'Second slice begins' },
          { start: 35 * 60 + 15, end: 35 * 60 + 45, text: 'Still in second slice' },
        ],
        transcriptText: 'Second slice begins\nStill in second slice',
      },
      {
        ...bundle,
        durationSeconds: 36 * 60 + 30,
        chunks: [
          { start: 36 * 60 + 5, end: 36 * 60 + 30, text: 'Third slice begins' },
        ],
        transcriptText: 'Third slice begins',
      },
    ]);
  });
});

describe('mergeQuestionAnswerSplitSections', () => {
  it('merges adjacent sections when one ends with a question and the next begins with the answer', () => {
    expect(mergeQuestionAnswerSplitSections([
      {
        startLabel: '00:00',
        endLabel: '00:30',
        subtitle: '提出问题',
        summary: '先提出核心问题。',
        transcript: '[00:00] Why is adoption slowing down?',
      },
      {
        startLabel: '00:30',
        endLabel: '01:00',
        subtitle: '解释原因',
        summary: '再解释背后的原因。',
        transcript: '[00:30] Companies are becoming more careful.',
      },
    ])).toEqual([
      {
        startLabel: '00:00',
        endLabel: '01:00',
        subtitle: '解释原因',
        summary: '再解释背后的原因。',
        transcript: '[00:00] Why is adoption slowing down?\n[00:30] Companies are becoming more careful.',
      },
    ]);
  });
});

describe('mergeDialogueSectionBoundary', () => {
  it('merges a same-speaker handoff into the previous section and leaves the rest in the next one', () => {
    const previous = createDialogueSlice({
      section: {
        startLabel: '58:39',
        endLabel: '01:00:00',
      },
      turns: [
        { timestamp: '58:39', speaker: 'John', textZh: '这很好地引出了 A16Z 的问题。' },
        { timestamp: '58:50', speaker: 'Marc', textZh: '我们最大的共同点在于，我们都愿意为了达成最佳结论进行激烈辩论。' },
      ],
    });
    const next = createDialogueSlice({
      section: {
        startLabel: '01:00:00',
        endLabel: '01:03:00',
        subtitle: 'AI 的社会影响与投资哲学',
      },
      turns: [
        { timestamp: '01:00:01', speaker: 'Marc', textZh: '关于公司的公众形象，我和 Ben 经常讨论。' },
        { timestamp: '01:00:14', speaker: 'Marc', textZh: '我们面临一个重要的张力。' },
        { timestamp: '01:01:03', speaker: 'John', textZh: '这对业务意味着什么？' },
      ],
    });

    const [mergedPrevious, remainingNext] = mergeDialogueSectionBoundary(previous, next, true);

    expect(mergedPrevious.turns).toEqual([
      { timestamp: '58:39', speaker: 'John', textZh: '这很好地引出了 A16Z 的问题。' },
      {
        timestamp: '58:50',
        speaker: 'Marc',
        textZh: '我们最大的共同点在于，我们都愿意为了达成最佳结论进行激烈辩论。关于公司的公众形象，我和 Ben 经常讨论。我们面临一个重要的张力。',
      },
    ]);
    expect(remainingNext.turns).toEqual([
      { timestamp: '01:01:03', speaker: 'John', textZh: '这对业务意味着什么？' },
    ]);
  });

  it('keeps the section boundary when speaker labels are hidden', () => {
    const previous = createDialogueSlice({
      turns: [
        { timestamp: '58:50', speaker: 'Marc', textZh: '前一段。' },
      ],
    });
    const next = createDialogueSlice({
      turns: [
        { timestamp: '01:00:01', speaker: 'Marc', textZh: '后一段。' },
        { timestamp: '01:00:14', speaker: 'Marc', textZh: '继续补充。' },
      ],
    });

    const [unchangedPrevious, normalizedNext] = mergeDialogueSectionBoundary(previous, next, false);

    expect(unchangedPrevious.turns).toEqual([
      { timestamp: '58:50', speaker: 'Marc', textZh: '前一段。' },
    ]);
    expect(normalizedNext.turns).toEqual([
      { timestamp: '01:00:01', speaker: 'Marc', textZh: '后一段。继续补充。' },
    ]);
  });

  it('merges same-speaker spillover between adjacent dialogue groups and sections', () => {
    const previous = createDialogueSlice({
      section: {
        startLabel: '58:39',
        endLabel: '01:00:00',
      },
      turns: [
        { timestamp: '58:39', speaker: 'Jen', textZh: '最后一个问题，你和 Ben 在什么事情上存在分歧但最终达成共识？' },
        { timestamp: '58:50', speaker: 'Marc', textZh: '我们经常争论，但我们都乐于被对方说服，所以大多数时候能达成一致。' },
      ],
      groups: [
        {
          topicTitleZh: '合伙人间的协作',
          turns: [
            { timestamp: '58:39', speaker: 'Jen', textZh: '最后一个问题，你和 Ben 在什么事情上存在分歧但最终达成共识？' },
            { timestamp: '58:50', speaker: 'Marc', textZh: '我们经常争论，但我们都乐于被对方说服，所以大多数时候能达成一致。' },
          ],
        },
      ],
    });
    const next = createDialogueSlice({
      section: {
        startLabel: '01:00:03',
        endLabel: '01:03:00',
        subtitle: '安德森的投资哲学与AI展望',
      },
      turns: [
        { timestamp: '01:00:03', speaker: 'Marc', textZh: '我和本经常讨论的一个核心问题是公司的公众形象。' },
        { timestamp: '01:01:03', speaker: 'Jen', textZh: '你怎么看这种张力？' },
      ],
      groups: [
        {
          topicTitleZh: '公司公开立场与争议',
          turns: [
            { timestamp: '01:00:03', speaker: 'Marc', textZh: '我和本经常讨论的一个核心问题是公司的公众形象。' },
            { timestamp: '01:01:03', speaker: 'Jen', textZh: '你怎么看这种张力？' },
          ],
        },
      ],
    });

    const [mergedPrevious, remainingNext] = mergeDialogueSectionBoundary(previous, next, true);

    expect(mergedPrevious.turns).toEqual([
      { timestamp: '58:39', speaker: 'Jen', textZh: '最后一个问题，你和 Ben 在什么事情上存在分歧但最终达成共识？' },
      {
        timestamp: '58:50',
        speaker: 'Marc',
        textZh: '我们经常争论，但我们都乐于被对方说服，所以大多数时候能达成一致。我和本经常讨论的一个核心问题是公司的公众形象。',
      },
    ]);
    expect(mergedPrevious.groups).toEqual([
      {
        topicTitleZh: '合伙人间的协作',
        turns: [
          { timestamp: '58:39', speaker: 'Jen', textZh: '最后一个问题，你和 Ben 在什么事情上存在分歧但最终达成共识？' },
          {
            timestamp: '58:50',
            speaker: 'Marc',
            textZh: '我们经常争论，但我们都乐于被对方说服，所以大多数时候能达成一致。我和本经常讨论的一个核心问题是公司的公众形象。',
          },
        ],
      },
    ]);
    expect(remainingNext.turns).toEqual([
      { timestamp: '01:01:03', speaker: 'Jen', textZh: '你怎么看这种张力？' },
    ]);
    expect(remainingNext.groups).toEqual([
      {
        topicTitleZh: '公司公开立场与争议',
        turns: [
          { timestamp: '01:01:03', speaker: 'Jen', textZh: '你怎么看这种张力？' },
        ],
      },
    ]);
  });

  it('keeps a structured question at the start of the next section instead of orphaning its answers', () => {
    const previous = createDialogueSlice({
      section: {
        startLabel: '58:39',
        endLabel: '01:00:00',
      },
      turns: [
        { timestamp: '58:39', speaker: 'Jen', textZh: '上一节里 Jen 的收尾。' },
      ],
      groups: [
        {
          topicTitleZh: '上一节主题',
          turns: [
            { timestamp: '58:39', speaker: 'Jen', textZh: '上一节里 Jen 的收尾。' },
          ],
        },
      ],
    });
    const next = createDialogueSlice({
      section: {
        startLabel: '01:00:00',
        endLabel: '01:03:00',
        subtitle: '新问题',
      },
      turns: [
        { timestamp: '01:00:01', speaker: 'Jen', textZh: '新的问题是什么？' },
        { timestamp: '01:00:20', speaker: 'Marc', textZh: '这是第一段回答。' },
      ],
      groups: [
        {
          topicTitleZh: '新主题',
          question: { timestamp: '01:00:01', speaker: 'Jen', textZh: '新的问题是什么？' },
          answers: [
            { timestamp: '01:00:20', speaker: 'Marc', textZh: '这是第一段回答。' },
          ],
          turns: [
            { timestamp: '01:00:01', speaker: 'Jen', textZh: '新的问题是什么？' },
            { timestamp: '01:00:20', speaker: 'Marc', textZh: '这是第一段回答。' },
          ],
        },
      ],
    });

    const [mergedPrevious, remainingNext] = mergeDialogueSectionBoundary(previous, next, true);

    expect(mergedPrevious.turns).toEqual([
      { timestamp: '58:39', speaker: 'Jen', textZh: '上一节里 Jen 的收尾。' },
    ]);
    expect(remainingNext.turns).toEqual([
      { timestamp: '01:00:01', speaker: 'Jen', textZh: '新的问题是什么？' },
      { timestamp: '01:00:20', speaker: 'Marc', textZh: '这是第一段回答。' },
    ]);
    expect(remainingNext.groups).toEqual([
      {
        topicTitleZh: '新主题',
        question: { timestamp: '01:00:01', speaker: 'Jen', textZh: '新的问题是什么？' },
        answers: [
          { timestamp: '01:00:20', speaker: 'Marc', textZh: '这是第一段回答。' },
        ],
        turns: [
          { timestamp: '01:00:01', speaker: 'Jen', textZh: '新的问题是什么？' },
          { timestamp: '01:00:20', speaker: 'Marc', textZh: '这是第一段回答。' },
        ],
      },
    ]);
  });

  it('keeps a structured question at the start of the next group inside one section', () => {
    const previous = createDialogueSlice({
      turns: [
        { timestamp: '00:00', speaker: 'Host', textZh: '模型是否具备意识？' },
        { timestamp: '00:10', speaker: 'Vishal', textZh: '我认为它没有意识。' },
        { timestamp: '00:20', speaker: 'Martin', textZh: '我也认为这可以排除。' },
        { timestamp: '00:30', speaker: 'Martin', textZh: '大语言模型究竟是如何运作的？' },
        { timestamp: '00:40', speaker: 'Vishal', textZh: '它本质上是在做概率预测。' },
      ],
      groups: [
        {
          topicTitleZh: '模型是否具备意识',
          question: { timestamp: '00:00', speaker: 'Host', textZh: '模型是否具备意识？' },
          answers: [
            { timestamp: '00:10', speaker: 'Vishal', textZh: '我认为它没有意识。' },
            { timestamp: '00:20', speaker: 'Martin', textZh: '我也认为这可以排除。' },
          ],
          turns: [
            { timestamp: '00:00', speaker: 'Host', textZh: '模型是否具备意识？' },
            { timestamp: '00:10', speaker: 'Vishal', textZh: '我认为它没有意识。' },
            { timestamp: '00:20', speaker: 'Martin', textZh: '我也认为这可以排除。' },
          ],
        },
        {
          topicTitleZh: '模型工作原理',
          question: { timestamp: '00:30', speaker: 'Martin', textZh: '大语言模型究竟是如何运作的？' },
          answers: [
            { timestamp: '00:40', speaker: 'Vishal', textZh: '它本质上是在做概率预测。' },
          ],
          turns: [
            { timestamp: '00:30', speaker: 'Martin', textZh: '大语言模型究竟是如何运作的？' },
            { timestamp: '00:40', speaker: 'Vishal', textZh: '它本质上是在做概率预测。' },
          ],
        },
      ],
    });
    const next = createDialogueSlice({
      turns: [
        { timestamp: '00:50', speaker: 'Host', textZh: '后续问题。' },
      ],
    });

    const [normalizedPrevious] = mergeDialogueSectionBoundary(previous, next, true);

    expect(normalizedPrevious.groups).toEqual([
      {
        topicTitleZh: '模型是否具备意识',
        question: { timestamp: '00:00', speaker: 'Host', textZh: '模型是否具备意识？' },
        answers: [
          { timestamp: '00:10', speaker: 'Vishal', textZh: '我认为它没有意识。' },
          { timestamp: '00:20', speaker: 'Martin', textZh: '我也认为这可以排除。' },
        ],
        turns: [
          { timestamp: '00:00', speaker: 'Host', textZh: '模型是否具备意识？' },
          { timestamp: '00:10', speaker: 'Vishal', textZh: '我认为它没有意识。' },
          { timestamp: '00:20', speaker: 'Martin', textZh: '我也认为这可以排除。' },
        ],
      },
      {
        topicTitleZh: '模型工作原理',
        question: { timestamp: '00:30', speaker: 'Martin', textZh: '大语言模型究竟是如何运作的？' },
        answers: [
          { timestamp: '00:40', speaker: 'Vishal', textZh: '它本质上是在做概率预测。' },
        ],
        turns: [
          { timestamp: '00:30', speaker: 'Martin', textZh: '大语言模型究竟是如何运作的？' },
          { timestamp: '00:40', speaker: 'Vishal', textZh: '它本质上是在做概率预测。' },
        ],
      },
    ]);
  });

  it('merges same-speaker spillover between adjacent groups inside one section before rendering', () => {
    const previous = createDialogueSlice({
      turns: [
        { timestamp: '00:00', speaker: 'Jen', textZh: '问题一？' },
        { timestamp: '00:10', speaker: 'Marc', textZh: '回答上半段。' },
        { timestamp: '00:20', speaker: 'Marc', textZh: '回答下半段。' },
        { timestamp: '00:30', speaker: 'Jen', textZh: '问题二？' },
      ],
      groups: [
        {
          topicTitleZh: '第一问',
          turns: [
            { timestamp: '00:00', speaker: 'Jen', textZh: '问题一？' },
            { timestamp: '00:10', speaker: 'Marc', textZh: '回答上半段。' },
          ],
        },
        {
          topicTitleZh: '第二问',
          turns: [
            { timestamp: '00:20', speaker: 'Marc', textZh: '回答下半段。' },
            { timestamp: '00:30', speaker: 'Jen', textZh: '问题二？' },
          ],
        },
      ],
    });
    const next = createDialogueSlice({
      turns: [
        { timestamp: '00:40', speaker: 'Host', textZh: '后续问题。' },
      ],
    });

    const [normalizedPrevious] = mergeDialogueSectionBoundary(previous, next, true);

    expect(normalizedPrevious.groups).toEqual([
      {
        topicTitleZh: '第一问',
        turns: [
          { timestamp: '00:00', speaker: 'Jen', textZh: '问题一？' },
          { timestamp: '00:10', speaker: 'Marc', textZh: '回答上半段。回答下半段。' },
        ],
      },
      {
        topicTitleZh: '第二问',
        turns: [
          { timestamp: '00:30', speaker: 'Jen', textZh: '问题二？' },
        ],
      },
    ]);
  });
});
