import { beforeEach, describe, expect, it, vi } from 'vitest';

import type { Env } from '../src/index';
import type {
  TranscriptBundle,
  TranscriptFetchCallbacks,
  TranscriptProviderOptions,
} from '../src/services/youtube';

const {
  fetchTranscriptBundleMock,
  generateTranscriptSectionsMock,
  summarizeQuickTranscriptSectionMock,
  translateTranscriptSectionToZhMock,
} = vi.hoisted(() => ({
  fetchTranscriptBundleMock: vi.fn(),
  generateTranscriptSectionsMock: vi.fn(),
  summarizeQuickTranscriptSectionMock: vi.fn(),
  translateTranscriptSectionToZhMock: vi.fn(),
}));

vi.mock('../src/services/youtube', async () => {
  const actual = await vi.importActual<typeof import('../src/services/youtube')>('../src/services/youtube');
  return {
    ...actual,
    fetchTranscriptBundle: fetchTranscriptBundleMock,
  };
});

vi.mock('../src/services/gemini', async () => {
  const actual = await vi.importActual<typeof import('../src/services/gemini')>('../src/services/gemini');
  return {
    ...actual,
    generateTranscriptSections: generateTranscriptSectionsMock,
    summarizeQuickTranscriptSection: summarizeQuickTranscriptSectionMock,
    translateTranscriptSectionToZh: translateTranscriptSectionToZhMock,
  };
});

import { handleGenerateRoute } from '../src/routes/generate';

function createBundle(): TranscriptBundle {
  return {
    videoId: 'xRh2sVcNXQ8',
    sourceTitle: 'Test title',
    sourceAuthor: 'Test author',
    channelId: 'channel',
    languageCode: 'en',
    languageName: 'English',
    isAutoGenerated: true,
    durationSeconds: 30,
    viewCount: 42,
    thumbnailUrl: 'https://example.com/thumb.jpg',
    segments: [],
    chunks: [
      { start: 0, end: 15, text: 'Opening line' },
      { start: 15, end: 30, text: 'Closing line' },
    ],
    transcriptText: 'Opening line\nClosing line',
  };
}

function createExecutionContext() {
  const tasks: Promise<unknown>[] = [];

  return {
    ctx: {
      waitUntil(promise: Promise<unknown>) {
        tasks.push(Promise.resolve(promise));
      },
      passThroughOnException() {
      },
    } as ExecutionContext,
    async waitForAll() {
      await Promise.allSettled(tasks);
    },
  };
}

describe('handleGenerateRoute', () => {
  beforeEach(() => {
    fetchTranscriptBundleMock.mockReset();
    generateTranscriptSectionsMock.mockReset();
    summarizeQuickTranscriptSectionMock.mockReset();
    translateTranscriptSectionToZhMock.mockReset();
  });

  it('passes Supadata transcript provider options to the fetcher', async () => {
    const bundle = createBundle();

    fetchTranscriptBundleMock.mockImplementation(async (
      _input: string,
      _callbacks?: TranscriptFetchCallbacks,
      _signal?: AbortSignal,
      _options?: TranscriptProviderOptions,
    ) => bundle);
    generateTranscriptSectionsMock.mockResolvedValue({
      sections: [
        {
          startLabel: '00:00',
          endLabel: '00:30',
          subtitle: 'Section 1',
          summary: 'Summary',
          transcript: '[00:00] Opening line\n[00:15] Closing line',
        },
      ],
      model: 'test-sections-model',
    });
    summarizeQuickTranscriptSectionMock.mockResolvedValue({
      section: {
        startLabel: '00:00',
        endLabel: '00:30',
        subtitle: 'Section 1',
        summary: 'Summary',
        transcript: '[00:00] Opening line\n[00:15] Closing line',
      },
      question: 'What happened?',
      answer: 'A short intro and outro.',
      questionZh: '讲了什么？',
      answerZh: '先开场，再收尾。',
      model: 'test-summary-model',
    });

    const request = new Request('https://example.com/api/generate', {
      method: 'POST',
      body: JSON.stringify({
        youtubeUrl: 'https://www.youtube.com/watch?v=xRh2sVcNXQ8',
        readingMode: 'quick',
      }),
      headers: {
        'content-type': 'application/json',
      },
    });
    const env: Env = {
      GEMINI_API_KEY: 'test-gemini-key',
      SUPADATA_API_KEY: 'test-supadata-key',
      SUPADATA_TRANSCRIPT_MODE: 'auto',
    };
    const { ctx, waitForAll } = createExecutionContext();

    const response = await handleGenerateRoute(request, env, ctx);
    const bodyPromise = response.text();
    await waitForAll();

    expect(fetchTranscriptBundleMock).toHaveBeenCalledTimes(1);
    expect(fetchTranscriptBundleMock).toHaveBeenCalledWith(
      'https://www.youtube.com/watch?v=xRh2sVcNXQ8',
      expect.any(Object),
      request.signal,
      {
        supadataApiKey: 'test-supadata-key',
        supadataMode: 'auto',
      },
    );

    const body = await bodyPromise;
    expect(body).toContain('event: done');
  });

  it('streams section previews first and then replaces them with translated dialogue in full mode', async () => {
    const bundle = createBundle();

    fetchTranscriptBundleMock.mockResolvedValue(bundle);
    generateTranscriptSectionsMock.mockResolvedValue({
      titleTranslationZh: '测试标题',
      summaryZh: '测试高亮',
      summary: 'Highlight sentence.',
      speakers: ['Host'],
      sections: [
        {
          startLabel: '00:00',
          endLabel: '00:30',
          subtitle: 'Opening',
          summary: 'Covers the opening lines.',
          topicTitleZh: '开场判断',
          topicSummaryZh: '先交代核心背景。',
          subtitleZh: '开场',
          summaryZh: '概述开场内容。',
          transcript: '',
        },
      ],
      model: 'test-sections-model',
    });
    translateTranscriptSectionToZhMock.mockResolvedValue({
      section: {
        startLabel: '00:00',
        endLabel: '00:30',
        subtitle: 'Opening',
        summary: 'Covers the opening lines.',
        topicTitleZh: '开场判断',
        topicSummaryZh: '先交代核心背景。',
        subtitleZh: '开场',
        summaryZh: '概述开场内容。',
        transcript: '[00:00] Opening line\n[00:15] Closing line',
      },
      turns: [
        { timestamp: '00:00', speaker: 'Host', textZh: '开场白。' },
        { timestamp: '00:15', speaker: 'Host', textZh: '结束语。' },
      ],
      groups: [
        {
          topicTitleZh: '投资判断',
          turns: [
            { timestamp: '00:00', speaker: 'Host', textZh: '开场白。' },
            { timestamp: '00:15', speaker: 'Host', textZh: '结束语。' },
          ],
        },
      ],
      model: 'test-dialogue-model',
    });

    const request = new Request('https://example.com/api/generate', {
      method: 'POST',
      body: JSON.stringify({
        youtubeUrl: 'https://www.youtube.com/watch?v=xRh2sVcNXQ8',
        readingMode: 'full',
      }),
      headers: {
        'content-type': 'application/json',
      },
    });
    const env: Env = {
      GEMINI_API_KEY: 'test-gemini-key',
    };
    const { ctx, waitForAll } = createExecutionContext();

    const response = await handleGenerateRoute(request, env, ctx);
    const bodyPromise = response.text();
    await waitForAll();

    const body = await bodyPromise;
    expect(body).toContain('"target":"dialogue","html":"<div class=\\"dialogue-section-block\\" data-dialogue-section-id=\\"dialogue-section-1\\">');
    expect(body).toContain('Gemini 正在打磨中文表达');
    expect(body).toContain('会优先保持自然、直接、适合阅读的中文语感。');
    expect(body).toContain('"target":"dialogue-replace"');
    expect(body).toContain('"sectionId":"dialogue-section-1"');
    expect(body).toContain('section-theme-title');
    expect(body).toContain('section-theme-summary');
    expect(body).toContain('开场判断');
    expect(body).toContain('先交代核心背景。');
    expect(body).toContain('dialogue-subtopic-title');
    expect(body).toContain('投资判断');
    expect(body).toContain('开场白。');
  });
});
