import { describe, expect, it } from 'vitest';

import {
  buildStoredFullRendering,
  buildStoredQuickRendering,
  buildStoredTranslationContent,
  isStoredTranslationContent,
} from '../src/services/render-content';
import type { TranscriptDialogueSliceResult, TranscriptSection } from '../src/services/gemini';
import type { TranscriptBundle } from '../src/services/youtube';

function createBundle(): TranscriptBundle {
  return {
    videoId: 'xRh2sVcNXQ8',
    sourceTitle: 'Marc Andreessen 2026 Outlook',
    sourceAuthor: 'TBPN',
    channelId: 'channel',
    languageCode: 'en',
    languageName: 'English',
    isAutoGenerated: true,
    durationSeconds: 120,
    viewCount: 42,
    thumbnailUrl: 'https://example.com/thumb.jpg',
    segments: [],
    chunks: [],
    transcriptText: 'Example transcript',
  };
}

describe('render-content', () => {
  it('builds a quick rendering snapshot with translated section copy only', () => {
    const sections: TranscriptSection[] = [
      {
        startLabel: '00:00',
        endLabel: '01:00',
        subtitle: 'Opening',
        summary: 'Intro',
        transcript: '[00:00] Example',
        topicTitleZh: '开场提问',
        topicSummaryZh: '先定问题',
        subtitleZh: '开场提问',
        summaryZh: '先定问题',
      },
    ];

    expect(buildStoredQuickRendering(createBundle(), sections, {
      translatedTitleZh: 'Marc Andreessen 2026 展望',
      summaryZh: '先讲 AI 增长速度。',
      summary: 'AI companies are growing very quickly.',
      speakers: ['Host', 'Guest'],
      model: 'gemini-3.1-flash-lite-preview',
    })).toEqual({
      readingMode: 'quick',
      hero: {
        translatedTitleZh: 'Marc Andreessen 2026 展望',
        displayTitle: 'Marc Andreessen 2026 展望',
        summaryZh: '先讲 AI 增长速度。',
      },
      summary: 'AI companies are growing very quickly.',
      speakers: ['Host', 'Guest'],
      model: 'gemini-3.1-flash-lite-preview',
      geminiTranslationComplete: true,
      translationNeedsRefresh: false,
      sections: [
        {
          id: 'quick-section-1',
          startLabel: '00:00',
          endLabel: '01:00',
          titleZh: '开场提问',
          summaryZh: '先定问题',
        },
      ],
    });
  });

  it('builds a full rendering snapshot that preserves translated dialogue groups', () => {
    const slices: TranscriptDialogueSliceResult[] = [
      {
        section: {
          startLabel: '00:00',
          endLabel: '02:00',
          subtitle: 'Opening',
          summary: 'Intro',
          transcript: '[00:10] Example',
          topicTitleZh: '采用分歧',
          topicSummaryZh: '先谈谨慎',
          subtitleZh: '采用分歧',
          summaryZh: '先谈谨慎',
        },
        turns: [
          {
            timestamp: '00:10',
            speaker: 'Host',
            textZh: '为什么企业变得更谨慎？',
          },
          {
            timestamp: '00:30',
            speaker: 'Guest',
            textZh: '因为大家开始看真实落地，而不是只看热度。',
          },
        ],
        groups: [
          {
            topicTitleZh: '采用阻力',
            question: {
              timestamp: '00:10',
              speaker: 'Host',
              textZh: '为什么企业变得更谨慎？',
            },
            answers: [
              {
                timestamp: '00:30',
                speaker: 'Guest',
                textZh: '因为大家开始看真实落地，而不是只看热度。',
              },
            ],
            turns: [
              {
                timestamp: '00:10',
                speaker: 'Host',
                textZh: '为什么企业变得更谨慎？',
              },
              {
                timestamp: '00:30',
                speaker: 'Guest',
                textZh: '因为大家开始看真实落地，而不是只看热度。',
              },
            ],
          },
        ],
        model: 'gemini-3.1-flash-lite-preview',
      },
    ];

    const rendering = buildStoredFullRendering(createBundle(), slices, {
      translatedTitleZh: 'Marc Andreessen 2026 展望',
      summaryZh: 'AI 回到真实需求。',
      summary: 'AI is moving from hype to workflows.',
      speakers: ['Host', 'Guest'],
      model: 'gemini-3.1-flash-lite-preview',
    });

    expect(rendering.sections[0]).toEqual({
      id: 'full-section-1',
      startLabel: '00:00',
      endLabel: '02:00',
      titleZh: '采用分歧',
      summaryZh: '先谈谨慎',
      groups: [
        {
          topicTitleZh: '采用阻力',
          question: {
            timestamp: '00:10',
            speaker: 'Host',
            textZh: '为什么企业变得更谨慎？',
          },
          answers: [
            {
              timestamp: '00:30',
              speaker: 'Guest',
              textZh: '因为大家开始看真实落地，而不是只看热度。',
            },
          ],
          turns: [
            {
              timestamp: '00:10',
              speaker: 'Host',
              textZh: '为什么企业变得更谨慎？',
            },
            {
              timestamp: '00:30',
              speaker: 'Guest',
              textZh: '因为大家开始看真实落地，而不是只看热度。',
            },
          ],
        },
      ],
      turns: [
        {
          timestamp: '00:10',
          speaker: 'Host',
          textZh: '为什么企业变得更谨慎？',
        },
        {
          timestamp: '00:30',
          speaker: 'Guest',
          textZh: '因为大家开始看真实落地，而不是只看热度。',
        },
      ],
    });
  });

  it('validates the stored translation content envelope', () => {
    const bundle = createBundle();
    const content = buildStoredTranslationContent(bundle, {
      quick: buildStoredQuickRendering(bundle, [
        {
          startLabel: '00:00',
          endLabel: '01:00',
          subtitle: 'Opening',
          summary: 'Intro',
          transcript: '[00:00] Example',
          topicTitleZh: '开场提问',
          topicSummaryZh: '先定问题',
          subtitleZh: '开场提问',
          summaryZh: '先定问题',
        },
      ], {
        translatedTitleZh: 'Marc Andreessen 2026 展望',
        summaryZh: '先讲 AI 增长速度。',
      }),
    });

    expect(isStoredTranslationContent(content)).toBe(true);
    expect(content.source.youtubeUrl).toBe('https://www.youtube.com/watch?v=xRh2sVcNXQ8');
  });
});
