import { isAbortError, throwIfAborted } from '../services/abort';
import type { Env } from '../index';
import { AppError, formatErrorMessage } from '../services/errors';
import {
  generateTranscriptSections,
  generateTranscriptInsights,
  summarizeQuickTranscriptSection,
  type QuickTranscriptSectionSummaryResult,
  type TranscriptDialogueSliceResult,
  type TranscriptSection,
  translateTranscriptSectionToZh,
} from '../services/gemini';
import { renderMarkdownDocument } from '../services/markdown';
import { createSseResponse, sendSseEvent } from '../services/sse';
import {
  buildTranscriptTextFromChunks,
  extractVideoId,
  fetchTranscriptBundle,
  formatTime,
} from '../services/youtube';
import type { TranscriptBundle, TranscriptChunk } from '../services/youtube';

interface GenerateRequestBody {
  youtubeUrl?: string;
  cachedTranscript?: TranscriptBundle;
  readingMode?: 'quick' | 'full';
  geminiApiKey?: string;
}

type ReadingMode = 'quick' | 'full';
const DEFAULT_READING_MODE: ReadingMode = 'quick';
const SUPPORTED_READING_MODES: ReadingMode[] = ['quick', 'full'];
const READING_MODE_LABELS: Record<ReadingMode, string> = {
  quick: '速读版',
  full: '详细版',
};

const FIRST_CALL_TRANSCRIPT_LIMIT_SECONDS = 30 * 60;
const MANUAL_SECTION_WINDOW_SECONDS = 20 * 60;
const QUICK_SECTIONING_SLICE_SECONDS = 18 * 60;
const MANUAL_SECTION_MODEL = 'manual_time_slice';
const MANUAL_SECTION_SUBTITLE_PATTERN = /^Transcript Section (\d+)$/i;
const MANUAL_SECTION_SUMMARY_PATTERN = /^Transcript content from (.+) to (.+)\.$/i;

function isTranscriptChunkArray(value: unknown): value is TranscriptChunk[] {
  return Array.isArray(value) && value.every((item) => {
    if (!item || typeof item !== 'object') {
      return false;
    }

    const chunk = item as Record<string, unknown>;
    return (
      typeof chunk.start === 'number' &&
      typeof chunk.end === 'number' &&
      typeof chunk.text === 'string'
    );
  });
}

function isTranscriptBundle(value: unknown): value is TranscriptBundle {
  if (!value || typeof value !== 'object') {
    return false;
  }

  const bundle = value as Record<string, unknown>;
  return (
    typeof bundle.videoId === 'string' &&
    typeof bundle.sourceTitle === 'string' &&
    typeof bundle.sourceAuthor === 'string' &&
    typeof bundle.channelId === 'string' &&
    typeof bundle.languageCode === 'string' &&
    typeof bundle.languageName === 'string' &&
    typeof bundle.isAutoGenerated === 'boolean' &&
    typeof bundle.durationSeconds === 'number' &&
    typeof bundle.viewCount === 'number' &&
    typeof bundle.thumbnailUrl === 'string' &&
    Array.isArray(bundle.segments) &&
    isTranscriptChunkArray(bundle.chunks) &&
    typeof bundle.transcriptText === 'string'
  );
}

function getUsableCachedTranscript(body: GenerateRequestBody, youtubeUrl: string): TranscriptBundle | null {
  if (!isTranscriptBundle(body.cachedTranscript)) {
    return null;
  }

  const expectedVideoId = extractVideoId(youtubeUrl);
  if (body.cachedTranscript.videoId !== expectedVideoId) {
    return null;
  }

  if (!body.cachedTranscript.chunks.length || !body.cachedTranscript.transcriptText.trim()) {
    return null;
  }

  return body.cachedTranscript;
}

async function parseRequestBody(request: Request): Promise<GenerateRequestBody> {
  try {
    return (await request.json()) as GenerateRequestBody;
  } catch {
    throw new AppError('invalid_json', '请求体不是合法的 JSON。', 400);
  }
}

function escapeHtml(input: string): string {
  return input
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}

function normalizeReadingMode(value: unknown): ReadingMode {
  return SUPPORTED_READING_MODES.includes(value as ReadingMode)
    ? value as ReadingMode
    : DEFAULT_READING_MODE;
}

function getReadingModeLabel(readingMode: ReadingMode): string {
  return READING_MODE_LABELS[normalizeReadingMode(readingMode)];
}

export function usesGeminiReadingFlow(readingMode: ReadingMode): boolean {
  return SUPPORTED_READING_MODES.includes(normalizeReadingMode(readingMode));
}

function getEffectiveGeminiEnv(
  env: Env,
  body: GenerateRequestBody,
): Env {
  const geminiApiKey = body.geminiApiKey?.trim();
  if (!geminiApiKey) {
    return env;
  }

  return {
    ...env,
    GEMINI_API_KEY: geminiApiKey,
  };
}

function buildBundleMeta(bundle: TranscriptBundle, readingMode: ReadingMode): Record<string, unknown> {
  return {
    videoId: bundle.videoId,
    sourceTitle: bundle.sourceTitle,
    sourceAuthor: bundle.sourceAuthor,
    sourceLanguage: bundle.languageName,
    sourceLanguageCode: bundle.languageCode,
    isAutoGenerated: bundle.isAutoGenerated,
    thumbnailUrl: bundle.thumbnailUrl,
    durationSeconds: bundle.durationSeconds,
    transcriptChunks: bundle.chunks.length,
    resultMode: 'transcript',
    readingMode,
    readingModeLabel: getReadingModeLabel(readingMode),
  };
}

function getTranscriptDurationSeconds(bundle: TranscriptBundle): number {
  return Math.max(
    bundle.durationSeconds,
    Math.ceil(bundle.chunks.at(-1)?.end ?? 0),
  );
}

export function shouldSliceFirstGeminiCall(bundle: TranscriptBundle): boolean {
  return getTranscriptDurationSeconds(bundle) > FIRST_CALL_TRANSCRIPT_LIMIT_SECONDS;
}

export function buildFirstCallTranscriptBundle(bundle: TranscriptBundle): TranscriptBundle {
  if (!shouldSliceFirstGeminiCall(bundle)) {
    return bundle;
  }

  const chunks = bundle.chunks
    .filter((chunk) => chunk.start < FIRST_CALL_TRANSCRIPT_LIMIT_SECONDS)
    .map((chunk) => ({
      ...chunk,
      end: Math.min(chunk.end, FIRST_CALL_TRANSCRIPT_LIMIT_SECONDS),
    }));

  return {
    ...bundle,
    chunks,
    durationSeconds: Math.min(getTranscriptDurationSeconds(bundle), FIRST_CALL_TRANSCRIPT_LIMIT_SECONDS),
    transcriptText: buildTranscriptTextFromChunks(chunks),
  };
}

export function buildManualTranscriptSections(
  bundle: TranscriptBundle,
  windowSeconds = MANUAL_SECTION_WINDOW_SECONDS,
): TranscriptSection[] {
  if (!bundle.chunks.length) {
    return [];
  }

  const sections: TranscriptSection[] = [];
  let chunkIndex = 0;

  while (chunkIndex < bundle.chunks.length) {
    const firstChunk = bundle.chunks[chunkIndex];
    const windowStart = Math.floor(firstChunk.start / windowSeconds) * windowSeconds;
    const windowEnd = windowStart + windowSeconds;
    const sectionChunks: TranscriptChunk[] = [];

    while (chunkIndex < bundle.chunks.length && bundle.chunks[chunkIndex].start < windowEnd) {
      sectionChunks.push(bundle.chunks[chunkIndex]);
      chunkIndex += 1;
    }

    if (!sectionChunks.length) {
      continue;
    }

    const isLastSection = chunkIndex >= bundle.chunks.length;
    const sectionEndSeconds = isLastSection
      ? Math.ceil(sectionChunks.at(-1)?.end ?? windowEnd)
      : windowEnd;
    const startLabel = formatTime(windowStart);
    const endLabel = formatTime(sectionEndSeconds);

    sections.push({
      startLabel,
      endLabel,
      subtitle: `Transcript Section ${sections.length + 1}`,
      summary: `Transcript content from ${startLabel} to ${endLabel}.`,
      transcript: sectionChunks
        .map((chunk) => `[${formatTime(chunk.start)}] ${chunk.text}`)
        .join('\n'),
    });
  }

  return sections;
}

export function buildTranscriptSliceBundles(
  bundle: TranscriptBundle,
  windowSeconds = QUICK_SECTIONING_SLICE_SECONDS,
): TranscriptBundle[] {
  if (!bundle.chunks.length) {
    return [];
  }

  const slices: TranscriptBundle[] = [];
  let chunkIndex = 0;

  while (chunkIndex < bundle.chunks.length) {
    const firstChunk = bundle.chunks[chunkIndex];
    const windowStart = Math.floor(firstChunk.start / windowSeconds) * windowSeconds;
    const windowEnd = windowStart + windowSeconds;
    const sliceChunks: TranscriptChunk[] = [];

    while (chunkIndex < bundle.chunks.length && bundle.chunks[chunkIndex].start < windowEnd) {
      sliceChunks.push(bundle.chunks[chunkIndex]);
      chunkIndex += 1;
    }

    if (!sliceChunks.length) {
      continue;
    }

    slices.push({
      ...bundle,
      chunks: sliceChunks,
      durationSeconds: Math.ceil(sliceChunks.at(-1)?.end ?? windowEnd),
      transcriptText: buildTranscriptTextFromChunks(sliceChunks),
    });
  }

  return slices;
}

function renumberManualPlaceholderSections(sections: TranscriptSection[]): TranscriptSection[] {
  let manualIndex = 0;

  return sections.map((section) => {
    if (
      MANUAL_SECTION_SUBTITLE_PATTERN.test(section.subtitle.trim())
      && MANUAL_SECTION_SUMMARY_PATTERN.test(section.summary.trim())
    ) {
      manualIndex += 1;
      return {
        ...section,
        subtitle: `Transcript Section ${manualIndex}`,
        summary: `Transcript content from ${section.startLabel} to ${section.endLabel}.`,
      };
    }

    return section;
  });
}

function renderTranscriptIntro(
  bundle: TranscriptBundle,
  readingMode: ReadingMode,
  translatedTitleZh?: string,
  summaryZh?: string,
): string[] {
  const displayTitle = translatedTitleZh?.trim() || bundle.sourceTitle;
  const introText = summaryZh?.trim()
    || (readingMode === 'quick'
      ? '按内容结构速读视频内容，每段优先呈现中心问题与答案。'
      : '直接阅读视频原始字幕，点击时间戳即可跳回对应片段。');
  const thumbnailUrl = bundle.thumbnailUrl || `https://i.ytimg.com/vi/${bundle.videoId}/hqdefault.jpg`;
  const youtubeUrl = `https://www.youtube.com/watch?v=${bundle.videoId}`;

  return [
    [
      '<header class="article-hero" data-article-hero>',
      `<h1 data-article-title>${escapeHtml(displayTitle)}</h1>`,
      '<blockquote class="article-pullquote">',
      '<p class="transcript-kicker">',
      `<span data-article-kicker>${escapeHtml(introText)}</span>`,
      '</p>',
      '</blockquote>',
      '<figure class="article-media">',
      `<img class="article-media-image" data-article-thumb src="${escapeHtml(thumbnailUrl)}" alt="${escapeHtml(displayTitle)} 缩略图" loading="eager" referrerpolicy="no-referrer" />`,
      '</figure>',
      '</header>',
    ].join(''),
  ];
}

function joinChunkText(left: string, right: string): string {
  if (!left) {
    return right;
  }

  if (/[-/([]$/.test(left) || /^[,.;:!?)]/.test(right)) {
    return `${left}${right}`;
  }

  return `${left} ${right}`;
}

function buildQuickReadChunks(chunks: TranscriptChunk[]): TranscriptChunk[] {
  const grouped: TranscriptChunk[] = [];
  let current: TranscriptChunk | null = null;

  for (const chunk of chunks) {
    if (!current) {
      current = { ...chunk };
      continue;
    }

    const gap = chunk.start - current.end;
    const nextLength = current.text.length + 1 + chunk.text.length;
    const nextDuration = chunk.end - current.start;
    const shouldSplit =
      gap > 12 ||
      nextLength > 900 ||
      nextDuration > 150 ||
      (current.text.length > 420 && /[.!?。！？]$/.test(current.text));

    if (shouldSplit) {
      grouped.push(current);
      current = { ...chunk };
      continue;
    }

    current.end = chunk.end;
    current.text = joinChunkText(current.text, chunk.text);
  }

  if (current) {
    grouped.push(current);
  }

  return grouped;
}

function renderDetailedTranscriptChunk(chunk: TranscriptChunk): string {
  return [
    '<section class="qa transcript-line">',
    `<div class="qa-time"><span class="timestamp compact">${escapeHtml(formatTime(chunk.start))}</span></div>`,
    `<div class="qa-body transcript-body"><p>${escapeHtml(chunk.text)}</p></div>`,
    '</section>',
  ].join('');
}

function renderQuickReadChunk(chunk: TranscriptChunk): string {
  return [
    '<section class="qa">',
    `<div class="qa-time"><span class="timestamp">${escapeHtml(formatTime(chunk.start))}</span></div>`,
    `<div class="qa-body"><p>${escapeHtml(chunk.text)}</p></div>`,
    '</section>',
  ].join('');
}

function renderSectionIntroHtml(
  section: { subtitle: string; summary: string; subtitleZh?: string; summaryZh?: string },
): string {
  const normalizedSubtitle = section.subtitle.trim();
  const normalizedSummary = section.summary.trim();
  const manualSubtitleMatch = normalizedSubtitle.match(MANUAL_SECTION_SUBTITLE_PATTERN);
  const manualSummaryMatch = normalizedSummary.match(MANUAL_SECTION_SUMMARY_PATTERN);
  const displaySubtitle = section.subtitleZh?.trim()
    || (manualSubtitleMatch ? `片段 ${manualSubtitleMatch[1]}` : section.subtitle);
  const displaySummary = section.summaryZh?.trim()
    || (manualSummaryMatch ? `该片段覆盖 ${manualSummaryMatch[1]} 到 ${manualSummaryMatch[2]} 的原文内容。` : section.summary);
  return renderMarkdownDocument(`## ${displaySubtitle}\n\n${displaySummary}`);
}

function renderDialogueSliceMarkdown(
  section: { subtitle: string; summary: string; subtitleZh?: string; summaryZh?: string },
  turns: Array<{ timestamp: string; speaker: string; textZh: string }>,
  showSpeakerNames = true,
): string {
  const lines: string[] = [];
  const mergedTurns = mergeConsecutiveDialogueTurns(turns);
  const speakerDisplayNames = showSpeakerNames ? buildSpeakerDisplayNames(mergedTurns) : new Map<string, string>();
  const displaySubtitle = section.subtitleZh?.trim() || section.subtitle;
  const displaySummary = section.summaryZh?.trim() || section.summary;

  lines.push(`## ${displaySubtitle}`);
  lines.push('');
  lines.push(displaySummary);

  for (const turn of mergedTurns) {
    if (lines.length) {
      lines.push('');
    }

    const speaker = turn.speaker.trim();
    if (!showSpeakerNames || !speaker) {
      lines.push(`[${turn.timestamp}] ${turn.textZh}`);
      continue;
    }

    lines.push(`[${turn.timestamp}] ${speakerDisplayNames.get(speaker) || getSpeakerDisplayName(speaker)}: ${turn.textZh}`);
  }

  return renderMarkdownDocument(lines.join('\n'));
}

function getSpeakerFirstToken(speaker: string): string {
  const normalized = speaker.trim();
  if (!normalized || !normalized.includes(' ')) {
    return normalized;
  }

  const [firstToken] = normalized.split(/\s+/);
  return firstToken || normalized;
}

function getSpeakerDisplayName(speaker: string): string {
  return getSpeakerFirstToken(speaker);
}

function buildSpeakerDisplayNames(
  turns: Array<{ timestamp: string; speaker: string; textZh: string }>,
): Map<string, string> {
  const groupedByFirstName = new Map<string, Set<string>>();

  for (const turn of turns) {
    const normalized = turn.speaker.trim();
    if (!normalized) {
      continue;
    }

    const firstToken = getSpeakerFirstToken(normalized);
    const existing = groupedByFirstName.get(firstToken) || new Set<string>();
    existing.add(normalized);
    groupedByFirstName.set(firstToken, existing);
  }

  const displayNames = new Map<string, string>();
  for (const turn of turns) {
    const normalized = turn.speaker.trim();
    if (!normalized || displayNames.has(normalized)) {
      continue;
    }

    const firstToken = getSpeakerFirstToken(normalized);
    const collidingSpeakers = groupedByFirstName.get(firstToken);
    if (normalized.includes(' ') && collidingSpeakers && collidingSpeakers.size > 1) {
      displayNames.set(normalized, normalized);
    } else {
      displayNames.set(normalized, firstToken);
    }
  }

  return displayNames;
}

function mergeConsecutiveDialogueTurns(
  turns: Array<{ timestamp: string; speaker: string; textZh: string }>,
): Array<{ timestamp: string; speaker: string; textZh: string }> {
  const merged: Array<{ timestamp: string; speaker: string; textZh: string }> = [];

  for (const turn of turns) {
    const speaker = turn.speaker.trim();
    const textZh = turn.textZh.trim();
    if (!textZh) {
      continue;
    }

    const previous = merged[merged.length - 1];
    if (previous && speaker && previous.speaker.trim() === speaker) {
      previous.textZh = joinDialogueText(previous.textZh, textZh);
      continue;
    }

    merged.push({
      timestamp: turn.timestamp,
      speaker,
      textZh,
    });
  }

  return merged;
}

function normalizeDialogueSliceTurns(
  slice: TranscriptDialogueSliceResult,
): TranscriptDialogueSliceResult {
  return {
    ...slice,
    turns: mergeConsecutiveDialogueTurns(slice.turns),
  };
}

export function mergeDialogueSectionBoundary(
  previous: TranscriptDialogueSliceResult,
  next: TranscriptDialogueSliceResult,
  showSpeakerNames: boolean,
): [TranscriptDialogueSliceResult, TranscriptDialogueSliceResult] {
  const normalizedPrevious = normalizeDialogueSliceTurns(previous);
  const normalizedNext = normalizeDialogueSliceTurns(next);

  if (!showSpeakerNames) {
    return [normalizedPrevious, normalizedNext];
  }

  const previousLastTurn = normalizedPrevious.turns.at(-1);
  const nextFirstTurn = normalizedNext.turns[0];
  const previousSpeaker = previousLastTurn?.speaker.trim() || '';
  const nextSpeaker = nextFirstTurn?.speaker.trim() || '';

  if (!previousLastTurn || !nextFirstTurn || !previousSpeaker || previousSpeaker !== nextSpeaker) {
    return [normalizedPrevious, normalizedNext];
  }

  return [
    {
      ...normalizedPrevious,
      turns: [
        ...normalizedPrevious.turns.slice(0, -1),
        {
          ...previousLastTurn,
          speaker: previousSpeaker,
          textZh: joinDialogueText(previousLastTurn.textZh, nextFirstTurn.textZh),
        },
      ],
    },
    {
      ...normalizedNext,
      turns: normalizedNext.turns.slice(1),
    },
  ];
}

function joinDialogueText(left: string, right: string): string {
  if (!left) {
    return right;
  }

  if (!right) {
    return left;
  }

  if (/[\s([{'"“‘-]$/.test(left) || /^[,.;:!?，。！？、；：)\]}%'"”’]/.test(right)) {
    return `${left}${right}`;
  }

  if (/[A-Za-z0-9.]$/.test(left) || /^[A-Za-z0-9]/.test(right)) {
    return `${left} ${right}`;
  }

  return `${left}${right}`;
}

function renderFallbackSliceHtml(
  startLabel: string,
  endLabel: string,
  chunks: TranscriptChunk[],
): string {
  return [
    `<h2 class="section-heading"><span class="section-rail"><span class="timestamp rail">${escapeHtml(`${startLabel}-${endLabel}`)}</span></span><span class="section-title">原文片段</span></h2>`,
    ...chunks.map(renderDetailedTranscriptChunk),
  ].join('');
}

function renderFallbackSectionHtml(
  section: {
    startLabel: string;
    endLabel: string;
    subtitle: string;
    summary: string;
    transcript: string;
    subtitleZh?: string;
    summaryZh?: string;
  },
): string {
  const lines = section.transcript
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean);
  const items = lines.map((line) => {
    const match = line.match(/^\[([0-9:]+(?:-[0-9:]+)?)\]\s*(.+)$/);
    if (!match) {
      return [
        '<section class="qa transcript-line">',
        `<div class="qa-body transcript-body"><p>${escapeHtml(line)}</p></div>`,
        '</section>',
      ].join('');
    }

    return [
      '<section class="qa transcript-line">',
      `<div class="qa-time"><span class="timestamp compact">${escapeHtml(match[1])}</span></div>`,
      `<div class="qa-body transcript-body"><p>${escapeHtml(match[2])}</p></div>`,
      '</section>',
    ].join('');
  });

  return [
    renderSectionIntroHtml(section),
    `<h2 class="section-heading"><span class="section-rail"><span class="timestamp rail">${escapeHtml(`${section.startLabel}-${section.endLabel}`)}</span></span><span class="section-title">原文片段</span></h2>`,
    ...items,
  ].join('');
}

function renderDialogueLoadingHtml(): string {
  return [
    '<section class="dialogue-loading-block" data-dialogue-loading>',
    '<div class="dialogue-loading-head">',
    '<span class="dialogue-loading-dot" aria-hidden="true"></span>',
    '<p class="dialogue-loading-title">正在继续生成内容</p>',
    '</div>',
    '<p class="dialogue-loading-copy">努力生成高质量的剩余内容中，请稍等。。。</p>',
    '</section>',
  ].join('');
}

function renderQuickSectionSummaryHtml(
  result: QuickTranscriptSectionSummaryResult,
): string {
  return [
    renderSectionIntroHtml(result.section),
    `<h2 class="section-heading"><span class="section-rail"><span class="timestamp rail">${escapeHtml(`${result.section.startLabel}-${result.section.endLabel}`)}</span></span><span class="section-title">核心问答</span></h2>`,
    '<section class="qa transcript-line">',
    '<div class="qa-time"><span class="timestamp compact">问题</span></div>',
    `<div class="qa-body transcript-body"><p>${escapeHtml(result.questionZh)}</p></div>`,
    '</section>',
    '<section class="qa transcript-line">',
    '<div class="qa-time"><span class="timestamp compact">回答</span></div>',
    `<div class="qa-body transcript-body"><p>${escapeHtml(result.answerZh)}</p></div>`,
    '</section>',
  ].join('');
}

function renderQuickSectionFallbackHtml(
  section: TranscriptSection,
): string {
  const displaySummary = section.summaryZh?.trim() || section.summary.trim();

  return [
    renderSectionIntroHtml(section),
    `<h2 class="section-heading"><span class="section-rail"><span class="timestamp rail">${escapeHtml(`${section.startLabel}-${section.endLabel}`)}</span></span><span class="section-title">核心内容</span></h2>`,
    '<section class="qa transcript-line">',
    '<div class="qa-time"><span class="timestamp compact">摘要</span></div>',
    `<div class="qa-body transcript-body"><p>${escapeHtml(displaySummary)}</p></div>`,
    '</section>',
  ].join('');
}

function logGenerate(event: string, details: Record<string, unknown>): void {
  console.log('[generate]', event, JSON.stringify(details));
}

export async function handleGenerateRoute(
  request: Request,
  env: Env,
  ctx: ExecutionContext,
): Promise<Response> {
  try {
    const body = await parseRequestBody(request);
    const youtubeUrl = body.youtubeUrl?.trim();
    const readingMode = normalizeReadingMode(body.readingMode);
    const effectiveEnv = getEffectiveGeminiEnv(env, body);
    if (!youtubeUrl) {
      throw new AppError('missing_url', '请输入一个带字幕的 YouTube 视频链接。', 400);
    }

    const { response, writer } = createSseResponse();
    const cachedTranscript = getUsableCachedTranscript(body, youtubeUrl);

    logGenerate('request_start', {
      youtubeUrl,
      cacheHit: Boolean(cachedTranscript),
      readingMode,
    });
    request.signal.addEventListener('abort', () => {
      logGenerate('request_aborted', { youtubeUrl, readingMode });
      void writer.abort(request.signal.reason).catch(() => {});
    }, { once: true });

    ctx.waitUntil(
      (async () => {
        try {
          throwIfAborted(request.signal);

          let transcriptBundle: TranscriptBundle;
          let translatedTitleZh = '';
          let summaryZh = '';
          let geminiTranslationComplete = false;

          if (cachedTranscript) {
            transcriptBundle = cachedTranscript;
            logGenerate('cache_hit', {
              videoId: transcriptBundle.videoId,
              chunks: transcriptBundle.chunks.length,
            });
            await sendSseEvent(writer, 'meta', {
              stage: 'cache_hit',
              statusText: '命中本地字幕缓存，正在准备内容',
              ...buildBundleMeta(transcriptBundle, readingMode),
              transcriptReady: true,
            });
          } else {
            throwIfAborted(request.signal);
            logGenerate('fetch_start', { youtubeUrl });
            await sendSseEvent(writer, 'meta', {
              stage: 'fetching',
              statusText: '正在抓取字幕与视频信息',
            });

            transcriptBundle = await fetchTranscriptBundle(youtubeUrl, {
              onPreviewReady: async (payload) => {
                throwIfAborted(request.signal);
                await sendSseEvent(writer, 'meta', {
                  stage: 'preview_ready',
                  statusText: '首批字幕已就绪，正在继续抓取完整内容',
                  videoId: payload.videoId,
                  sourceTitle: payload.sourceTitle,
                  sourceAuthor: payload.sourceAuthor,
                  sourceLanguage: payload.sourceLanguage,
                  sourceLanguageCode: payload.sourceLanguageCode,
                  isAutoGenerated: payload.isAutoGenerated,
                  thumbnailUrl: payload.thumbnailUrl,
                  transcriptReady: false,
                  resultMode: 'transcript',
                  readingMode,
                  readingModeLabel: getReadingModeLabel(readingMode),
                });
              },
            }, request.signal);

            await sendSseEvent(writer, 'cache', {
              videoId: transcriptBundle.videoId,
              bundle: transcriptBundle,
            });

            logGenerate('fetch_complete', {
              videoId: transcriptBundle.videoId,
              chunks: transcriptBundle.chunks.length,
              languageCode: transcriptBundle.languageCode,
            });
          }

          logGenerate('transcript_ready', {
            videoId: transcriptBundle.videoId,
            chunks: transcriptBundle.chunks.length,
          });
          console.log(
            '[generate] original_transcript',
            transcriptBundle.videoId,
            '\n' + transcriptBundle.transcriptText,
          );
          await sendSseEvent(writer, 'meta', {
            stage: 'transcript_ready',
            statusText: '字幕已抓取，正在排版内容',
            ...buildBundleMeta(transcriptBundle, readingMode),
            transcriptReady: true,
          });

          if (readingMode === 'quick') {
            throwIfAborted(request.signal);
            try {
              const sliceBundles = buildTranscriptSliceBundles(transcriptBundle);
              const aggregatedSections: TranscriptSection[] = [];
              const totalSlices = Math.max(1, sliceBundles.length);

              logGenerate('quick_sectioning_mode', {
                videoId: transcriptBundle.videoId,
                slices: totalSlices,
                durationSeconds: transcriptBundle.durationSeconds,
              });

              for (const html of renderTranscriptIntro(transcriptBundle, readingMode, translatedTitleZh, summaryZh)) {
                await sendSseEvent(writer, 'html', { target: 'article', html });
              }
              await sendSseEvent(writer, 'html', {
                target: 'dialogue-loading',
                html: renderDialogueLoadingHtml(),
              });

              for (let sliceIndex = 0; sliceIndex < sliceBundles.length; sliceIndex += 1) {
                throwIfAborted(request.signal);
                const sliceBundle = sliceBundles[sliceIndex];

                await sendSseEvent(writer, 'meta', {
                  stage: 'analyzing',
                  statusText: totalSlices > 1
                    ? `正在分析内容结构（${sliceIndex + 1}/${totalSlices}）`
                    : '正在分析内容结构',
                  ...buildBundleMeta(transcriptBundle, readingMode),
                });

                try {
                  const sectionsResult = await generateTranscriptSections(
                    sliceBundle,
                    effectiveEnv,
                    readingMode,
                    request.signal,
                  );
                  aggregatedSections.push(...sectionsResult.sections);
                } catch (error) {
                  if (isAbortError(error)) {
                    throw error;
                  }

                  const sliceError = AppError.from(error);
                  logGenerate('quick_sections_slice_failed', {
                    videoId: transcriptBundle.videoId,
                    sliceIndex,
                    code: sliceError.code,
                    message: sliceError.publicMessage,
                  });
                  aggregatedSections.push(...buildManualTranscriptSections(sliceBundle, QUICK_SECTIONING_SLICE_SECONDS));
                }
              }

              const sections = renumberManualPlaceholderSections(aggregatedSections);

              await sendSseEvent(writer, 'meta', {
                stage: 'writing',
                statusText: `正在写入${getReadingModeLabel(readingMode)}开头信息`,
                ...buildBundleMeta(transcriptBundle, readingMode),
              });

              await sendSseEvent(writer, 'meta', {
                stage: 'summarizing_sections',
                statusText: '正在整理每段的中心问题与答案',
                ...buildBundleMeta(transcriptBundle, readingMode),
              });

              let allSectionsTranslated = sections.length > 0;
              for (let index = 0; index < sections.length; index += 1) {
                throwIfAborted(request.signal);
                const section = sections[index];

                try {
                  const quickSummary = await summarizeQuickTranscriptSection(
                    transcriptBundle,
                    section,
                    effectiveEnv,
                    request.signal,
                  );
                  await sendSseEvent(writer, 'html', {
                    target: 'dialogue',
                    html: renderQuickSectionSummaryHtml(quickSummary),
                  });
                } catch (error) {
                  if (isAbortError(error)) {
                    throw error;
                  }

                  allSectionsTranslated = false;
                  const sliceError = AppError.from(error);
                  logGenerate('quick_summary_slice_failed', {
                    videoId: transcriptBundle.videoId,
                    slice: `${section.startLabel}-${section.endLabel}`,
                    code: sliceError.code,
                    message: sliceError.publicMessage,
                  });
                  if (sliceError.code === 'gemini_timeout') {
                    await sendSseEvent(writer, 'warning', {
                      code: sliceError.code,
                      message: sliceError.publicMessage,
                    });
                  }
                  await sendSseEvent(writer, 'html', {
                    target: 'dialogue',
                    html: renderQuickSectionFallbackHtml(section),
                  });
                }

                await sendSseEvent(writer, 'meta', {
                  stage: 'summarizing_sections',
                  statusText: `正在整理每段的中心问题与答案（${index + 1}/${sections.length}）`,
                  ...buildBundleMeta(transcriptBundle, readingMode),
                });
              }
              geminiTranslationComplete = allSectionsTranslated;
            } catch (error) {
              if (isAbortError(error)) {
                throw error;
              }

              const appError = AppError.from(error);
              logGenerate('quick_flow_failed', {
                videoId: transcriptBundle.videoId,
                code: appError.code,
                message: appError.publicMessage,
              });

              await sendSseEvent(writer, 'meta', {
                stage: 'writing',
                statusText: 'AI 分段失败，回退到原始速读内容',
                ...buildBundleMeta(transcriptBundle, readingMode),
              });

              for (const html of renderTranscriptIntro(transcriptBundle, readingMode)) {
                await sendSseEvent(writer, 'html', { target: 'article', html });
              }

              for (const chunk of buildQuickReadChunks(transcriptBundle.chunks)) {
                throwIfAborted(request.signal);
                await sendSseEvent(writer, 'html', {
                  target: 'article',
                  html: renderQuickReadChunk(chunk),
                });
              }
            }
          } else if (readingMode === 'full') {
            throwIfAborted(request.signal);
            await sendSseEvent(writer, 'meta', {
              stage: 'analyzing',
              statusText: '正在调用 Gemini 生成高质量内容',
              ...buildBundleMeta(transcriptBundle, readingMode),
            });

            try {
              const firstCallBundle = buildFirstCallTranscriptBundle(transcriptBundle);
              const usedSlicedFirstCall = firstCallBundle !== transcriptBundle;
              const manualSections = usedSlicedFirstCall ? buildManualTranscriptSections(transcriptBundle) : null;

              logGenerate('analysis_mode', {
                videoId: transcriptBundle.videoId,
                firstCallTranscriptSeconds: firstCallBundle.durationSeconds,
                firstCallSliced: usedSlicedFirstCall,
                manualSections: manualSections?.length ?? 0,
              });

              const insightsPromise = generateTranscriptInsights(firstCallBundle, effectiveEnv, readingMode, request.signal);
              const sectionsPromise = manualSections
                ? Promise.resolve({
                    sections: manualSections,
                    model: MANUAL_SECTION_MODEL,
                  })
                : generateTranscriptSections(transcriptBundle, effectiveEnv, readingMode, request.signal);
              const insights = await insightsPromise;
              const sectionsResult = await sectionsPromise;
              translatedTitleZh = insights.titleTranslationZh;
              summaryZh = insights.summaryZh;
              logGenerate('insights_ready', {
                videoId: transcriptBundle.videoId,
                model: insights.model,
                speakers: insights.speakers.length,
                sections: sectionsResult.sections.length,
                sectionsModel: sectionsResult.model,
              });
              await sendSseEvent(writer, 'insights', {
                ...insights,
                titleTranslationZh: translatedTitleZh,
              });

              await sendSseEvent(writer, 'meta', {
                stage: 'writing',
                statusText: `正在写入${getReadingModeLabel(readingMode)}开头信息`,
                ...buildBundleMeta(transcriptBundle, readingMode),
                translatedTitleZh,
                summaryZh,
              });

              for (const html of renderTranscriptIntro(transcriptBundle, readingMode, translatedTitleZh, summaryZh)) {
                await sendSseEvent(writer, 'html', { target: 'article', html });
              }
              await sendSseEvent(writer, 'html', {
                target: 'dialogue-loading',
                html: renderDialogueLoadingHtml(),
              });

              await sendSseEvent(writer, 'meta', {
                stage: 'translating_dialogue',
                statusText: '正在继续生成内容',
                ...buildBundleMeta(transcriptBundle, readingMode),
                translatedTitleZh,
                summaryZh,
              });

              const sections = sectionsResult.sections;
              const showSpeakerNames = insights.speakers.length > 0;
              let pendingDialogueSlice: TranscriptDialogueSliceResult | null = null;
              const flushPendingDialogueSlice = async (): Promise<void> => {
                if (!pendingDialogueSlice) {
                  return;
                }

                await sendSseEvent(writer, 'html', {
                  target: 'dialogue',
                  html: renderDialogueSliceMarkdown(
                    pendingDialogueSlice.section,
                    pendingDialogueSlice.turns,
                    showSpeakerNames,
                  ),
                });
                pendingDialogueSlice = null;
              };
              let allSectionsTranslated = true;
              for (let index = 0; index < sections.length; index += 1) {
                throwIfAborted(request.signal);
                const section = sections[index];

                try {
                  const translatedSlice = await translateTranscriptSectionToZh(
                    transcriptBundle,
                    section,
                    insights,
                    translatedTitleZh,
                    effectiveEnv,
                    readingMode,
                    request.signal,
                  );
                  if (pendingDialogueSlice) {
                    const [readySlice, nextPendingSlice] = mergeDialogueSectionBoundary(
                      pendingDialogueSlice,
                      translatedSlice,
                      showSpeakerNames,
                    );
                    pendingDialogueSlice = readySlice;
                    await flushPendingDialogueSlice();
                    pendingDialogueSlice = nextPendingSlice;
                  } else {
                    pendingDialogueSlice = normalizeDialogueSliceTurns(translatedSlice);
                  }
                } catch (error) {
                  if (isAbortError(error)) {
                    throw error;
                  }

                  allSectionsTranslated = false;
                  await flushPendingDialogueSlice();
                  const sliceError = AppError.from(error);
                  logGenerate('dialogue_slice_failed', {
                    videoId: transcriptBundle.videoId,
                    slice: `${section.startLabel}-${section.endLabel}`,
                    code: sliceError.code,
                    message: sliceError.publicMessage,
                  });
                  if (sliceError.code === 'gemini_timeout') {
                    await sendSseEvent(writer, 'warning', {
                      code: sliceError.code,
                      message: sliceError.publicMessage,
                    });
                  }
                  await sendSseEvent(writer, 'html', {
                    target: 'dialogue',
                    html: renderFallbackSectionHtml(section),
                  });
                }

                await sendSseEvent(writer, 'meta', {
                  stage: 'translating_dialogue',
                  statusText: `正在继续生成内容（${index + 1}/${sections.length}）`,
                  ...buildBundleMeta(transcriptBundle, readingMode),
                  translatedTitleZh,
                  summaryZh,
                });
              }
              await flushPendingDialogueSlice();
              geminiTranslationComplete = allSectionsTranslated;
            } catch (error) {
              if (isAbortError(error)) {
                throw error;
              }

              const appError = AppError.from(error);
              logGenerate('insights_failed', {
                videoId: transcriptBundle.videoId,
                code: appError.code,
                message: appError.publicMessage,
              });
              await sendSseEvent(writer, 'insights', {
                titleTranslationZh: '',
                summaryZh: '',
                summary: '',
                speakers: [],
                model: '',
                warning: appError.publicMessage,
              });

              await sendSseEvent(writer, 'meta', {
                stage: 'writing',
                statusText: 'AI 翻译失败，回退到原始字幕',
                ...buildBundleMeta(transcriptBundle, readingMode),
              });

              for (const html of renderTranscriptIntro(transcriptBundle, readingMode)) {
                await sendSseEvent(writer, 'html', { target: 'article', html });
              }

              for (const chunk of transcriptBundle.chunks) {
                throwIfAborted(request.signal);
                await sendSseEvent(writer, 'html', {
                  target: 'article',
                  html: renderDetailedTranscriptChunk(chunk),
                });
              }
            }
          }

          logGenerate('request_complete', {
            videoId: transcriptBundle.videoId,
            chunks: transcriptBundle.chunks.length,
            readingMode,
          });
          await sendSseEvent(writer, 'meta', {
            stage: 'complete',
            statusText: '内容已完成',
            ...buildBundleMeta(transcriptBundle, readingMode),
            translatedTitleZh,
            summaryZh,
            geminiTranslationComplete,
          });
          await sendSseEvent(writer, 'done', { ok: true });
        } catch (error) {
          if (isAbortError(error)) {
            logGenerate('request_cancelled', {
              youtubeUrl,
              readingMode,
            });
            return;
          }

          const appError = AppError.from(error);
          console.error('[generate] request_error', {
            code: appError.code,
            status: appError.status,
            message: appError.publicMessage,
            cause: error instanceof Error ? error.stack ?? error.message : error,
          });
          await sendSseEvent(writer, 'error', {
            code: appError.code,
            message: formatErrorMessage(appError),
          });
        } finally {
          await writer.close().catch(() => {});
        }
      })(),
    );

    return response;
  } catch (error) {
    const appError = AppError.from(error);
    return new Response(formatErrorMessage(appError), {
      status: appError.status,
      headers: {
        'content-type': 'text/plain; charset=utf-8',
      },
    });
  }
}
