import type { Env } from '../index';
import { MOCK_ARTICLE_MARKDOWN, MOCK_SOURCE } from '../mock/andreessen';
import { AppError, formatErrorMessage } from '../services/errors';
import { renderMarkdownBlock } from '../services/markdown';
import { createSseResponse, sendSseEvent } from '../services/sse';
import { extractVideoId, fetchTranscriptBundle } from '../services/youtube';
import type { TranscriptBundle } from '../services/youtube';
interface GenerateRequestBody {
  youtubeUrl?: string;
  cachedTranscript?: TranscriptBundle;
}

function isTranscriptChunkArray(value: unknown): value is TranscriptBundle['chunks'] {
  return Array.isArray(value) && value.every((item) => {
    if (!item || typeof item !== 'object') {
      return false;
    }

    const chunk = item as Record<string, unknown>;
    return (
      typeof chunk.start === 'number' &&
      typeof chunk.end === 'number' &&
      typeof chunk.text === 'string'
    );
  });
}

function isTranscriptBundle(value: unknown): value is TranscriptBundle {
  if (!value || typeof value !== 'object') {
    return false;
  }

  const bundle = value as Record<string, unknown>;
  return (
    typeof bundle.videoId === 'string' &&
    typeof bundle.sourceTitle === 'string' &&
    typeof bundle.sourceAuthor === 'string' &&
    typeof bundle.channelId === 'string' &&
    typeof bundle.languageCode === 'string' &&
    typeof bundle.languageName === 'string' &&
    typeof bundle.isAutoGenerated === 'boolean' &&
    typeof bundle.durationSeconds === 'number' &&
    typeof bundle.viewCount === 'number' &&
    typeof bundle.thumbnailUrl === 'string' &&
    Array.isArray(bundle.segments) &&
    isTranscriptChunkArray(bundle.chunks) &&
    typeof bundle.transcriptText === 'string'
  );
}

function getUsableCachedTranscript(body: GenerateRequestBody, youtubeUrl: string): TranscriptBundle | null {
  if (!isTranscriptBundle(body.cachedTranscript)) {
    return null;
  }

  const expectedVideoId = extractVideoId(youtubeUrl);
  if (body.cachedTranscript.videoId !== expectedVideoId) {
    return null;
  }

  if (!body.cachedTranscript.chunks.length || !body.cachedTranscript.transcriptText.trim()) {
    return null;
  }

  return body.cachedTranscript;
}

async function streamMockArticle(writer: WritableStreamDefaultWriter<Uint8Array>): Promise<void> {
  await sendSseEvent(writer, 'meta', {
    stage: 'transcript_ready',
    statusText: 'Mock 字幕已就绪，正在准备版面',
    ...MOCK_SOURCE,
    transcriptReady: true,
  });

  await sendSseEvent(writer, 'meta', {
    stage: 'writing',
    statusText: 'Mock 正文正在流式写入',
    ...MOCK_SOURCE,
  });

  const blocks = MOCK_ARTICLE_MARKDOWN
    .split(/\n{2,}/)
    .map((block) => block.trim())
    .filter(Boolean);

  for (const block of blocks) {
    await sendSseEvent(writer, 'html', {
      target: 'article',
      html: renderMarkdownBlock(block),
    });
  }

  await sendSseEvent(writer, 'meta', {
    stage: 'complete',
    statusText: 'Mock 结果已完成',
    ...MOCK_SOURCE,
  });
  await sendSseEvent(writer, 'done', { ok: true, mock: true });
}

async function parseRequestBody(request: Request): Promise<GenerateRequestBody> {
  try {
    return (await request.json()) as GenerateRequestBody;
  } catch {
    throw new AppError('invalid_json', '请求体不是合法的 JSON。', 400);
  }
}

function escapeHtml(input: string): string {
  return input
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}

function formatTimestamp(seconds: number): string {
  const whole = Math.max(0, Math.floor(seconds));
  const hours = Math.floor(whole / 3600);
  const minutes = Math.floor((whole % 3600) / 60);
  const remainder = whole % 60;

  if (hours > 0) {
    return `${String(hours).padStart(2, '0')}:${String(minutes).padStart(2, '0')}:${String(remainder).padStart(2, '0')}`;
  }

  return `${String(minutes).padStart(2, '0')}:${String(remainder).padStart(2, '0')}`;
}

function buildTranscriptArticleLead(bundle: TranscriptBundle): string[] {
  return [
    `<h1>${escapeHtml(bundle.sourceTitle)}</h1>`,
    `<p class="transcript-kicker">原始字幕实录。当前页面暂不使用 LLM 翻译或改写，只对字幕进行清洗、分段和时间轴排版，方便先检查内容与版式。</p>`,
  ];
}

function buildTranscriptLineHtml(bundle: TranscriptBundle, start: number, size = 18): string[] {
  return bundle.chunks.slice(start, start + size).map((chunk) => {
    const label = formatTimestamp(chunk.start);
    return `<div class="qa transcript-line"><div class="qa-time"><span class="timestamp rail compact">${label}</span></div><div class="qa-body transcript-body">${escapeHtml(chunk.text)}</div></div>`;
  });
}

export async function handleGenerateRoute(
  request: Request,
  _env: Env,
  ctx: ExecutionContext,
): Promise<Response> {
  try {
    const body = await parseRequestBody(request);
    const youtubeUrl = body.youtubeUrl?.trim();

    if (!youtubeUrl) {
      throw new AppError('missing_url', '请输入一个带字幕的 YouTube 视频链接。', 400);
    }

    const { response, writer } = createSseResponse();
    const cachedTranscript = getUsableCachedTranscript(body, youtubeUrl);

    ctx.waitUntil(
      (async () => {
        try {
          let transcriptBundle: TranscriptBundle;

          if (cachedTranscript) {
            transcriptBundle = cachedTranscript;
            await sendSseEvent(writer, 'meta', {
              stage: 'cache_hit',
              statusText: '命中本地字幕缓存，正在准备 transcript',
              videoId: transcriptBundle.videoId,
              sourceTitle: transcriptBundle.sourceTitle,
              sourceAuthor: transcriptBundle.sourceAuthor,
              sourceLanguage: transcriptBundle.languageName,
              sourceLanguageCode: transcriptBundle.languageCode,
              isAutoGenerated: transcriptBundle.isAutoGenerated,
              thumbnailUrl: transcriptBundle.thumbnailUrl,
              transcriptReady: true,
              usedCompression: false,
            });
          } else {
            await sendSseEvent(writer, 'meta', {
              stage: 'fetching',
              statusText: '正在抓取字幕与视频信息',
            });

            transcriptBundle = await fetchTranscriptBundle(youtubeUrl, {
              onPreviewReady: async (payload) => {
                await sendSseEvent(writer, 'meta', {
                  stage: 'preview_ready',
                  statusText: '首批字幕已就绪，正在继续抓取完整字幕',
                  videoId: payload.videoId,
                  sourceTitle: payload.sourceTitle,
                  sourceAuthor: payload.sourceAuthor,
                  sourceLanguage: payload.sourceLanguage,
                  sourceLanguageCode: payload.sourceLanguageCode,
                  isAutoGenerated: payload.isAutoGenerated,
                  thumbnailUrl: payload.thumbnailUrl,
                  transcriptReady: false,
                  usedCompression: false,
                });
              },
            });

            await sendSseEvent(writer, 'cache', {
              videoId: transcriptBundle.videoId,
              bundle: transcriptBundle,
            });
          }

          await sendSseEvent(writer, 'meta', {
            stage: 'transcript_ready',
            statusText: '字幕已抓取，正在准备 transcript',
            videoId: transcriptBundle.videoId,
            sourceTitle: transcriptBundle.sourceTitle,
            sourceAuthor: transcriptBundle.sourceAuthor,
            sourceLanguage: transcriptBundle.languageName,
            sourceLanguageCode: transcriptBundle.languageCode,
            isAutoGenerated: transcriptBundle.isAutoGenerated,
            thumbnailUrl: transcriptBundle.thumbnailUrl,
            transcriptChunks: transcriptBundle.chunks.length,
            transcriptReady: true,
            usedCompression: false,
          });

          await sendSseEvent(writer, 'meta', {
            stage: 'writing',
            statusText: '正在排版 transcript',
            videoId: transcriptBundle.videoId,
            sourceTitle: transcriptBundle.sourceTitle,
            sourceAuthor: transcriptBundle.sourceAuthor,
            sourceLanguage: transcriptBundle.languageName,
            sourceLanguageCode: transcriptBundle.languageCode,
            isAutoGenerated: transcriptBundle.isAutoGenerated,
            thumbnailUrl: transcriptBundle.thumbnailUrl,
            transcriptChunks: transcriptBundle.chunks.length,
            usedCompression: false,
          });

          for (const html of buildTranscriptArticleLead(transcriptBundle)) {
            await sendSseEvent(writer, 'html', { target: 'article', html });
          }

          for (let index = 0; index < transcriptBundle.chunks.length; index += 18) {
            const html = buildTranscriptLineHtml(transcriptBundle, index).join('');
            await sendSseEvent(writer, 'html', { target: 'article', html });
          }

          await sendSseEvent(writer, 'meta', {
            stage: 'complete',
            videoId: transcriptBundle.videoId,
            sourceTitle: transcriptBundle.sourceTitle,
            sourceAuthor: transcriptBundle.sourceAuthor,
            sourceLanguage: transcriptBundle.languageName,
            sourceLanguageCode: transcriptBundle.languageCode,
            isAutoGenerated: transcriptBundle.isAutoGenerated,
            thumbnailUrl: transcriptBundle.thumbnailUrl,
            transcriptChunks: transcriptBundle.chunks.length,
            usedCompression: false,
          });
          await sendSseEvent(writer, 'done', { ok: true });
        } catch (error) {
          const appError = AppError.from(error);
          await sendSseEvent(writer, 'error', {
            code: appError.code,
            message: formatErrorMessage(appError),
          });
        } finally {
          await writer.close();
        }
      })(),
    );

    return response;
  } catch (error) {
    const appError = AppError.from(error);
    return new Response(formatErrorMessage(appError), {
      status: appError.status,
      headers: {
        'content-type': 'text/plain; charset=utf-8',
      },
    });
  }
}

export async function handleMockGenerateRoute(_request: Request, _env: Env, ctx: ExecutionContext): Promise<Response> {
  const { response, writer } = createSseResponse();

  ctx.waitUntil(
    (async () => {
      try {
        await streamMockArticle(writer);
      } catch (error) {
        const appError = AppError.from(error);
        await sendSseEvent(writer, 'error', {
          code: appError.code,
          message: formatErrorMessage(appError),
        });
      } finally {
        await writer.close();
      }
    })(),
  );

  return response;
}
