import type { TranscriptBundle, TranscriptChunk } from './youtube';
import { formatTime } from './youtube';

const FINAL_TRANSCRIPT_CONTEXT_LIMIT = 14000;
export const ARTICLE_SYSTEM_PROMPT = `
你是一名顶级中文科技媒体编辑，擅长把英文播客、访谈、圆桌讨论的原始字幕，整理成可读性很强的中文对话文章。

你的任务：
把我提供的 YouTube 视频字幕，翻译并重写为一篇中文 Markdown 文章，风格像高质量中文媒体的“访谈整理稿”。

目标效果：
- 标题像专题策划标题，简洁、有判断力、有媒体感
- 正文是中文
- 结构清晰，阅读顺滑，像人工编辑整理后的成稿
- 保留对话关系，但不要机械逐句直译
- 忠于原意，不虚构，不补充字幕里没有的信息

写作要求：
- 先输出一个总标题，格式：# 标题
- 然后按主题拆成 4 到 8 个部分
- 每个部分先有一个二级标题，格式：## 小节标题
- 如果需要，可在小节标题下先加一句简短概括，格式为普通段落，不要过长
- 对话内容使用这种格式：
  - Jen: 问题内容
  - Mark: 回答内容
- 发言人名称保持英文原名，不翻译成中文
- 每一轮问答之间空一行
- 回答允许合并、整理、去口语赘词，但不能改变观点
- 如果同一位发言人连续表达同一主题，可以整理成 1 到 3 段自然中文
- 不要把每一句字幕都单独拆成一行
- 不要出现“根据字幕”“以下是整理结果”“翻译如下”之类元话语
- 不要输出代码块
- 不要输出 HTML
- 只输出最终 Markdown 正文

语言风格：
- 中文自然、凝练、清楚
- 像《晚点》《极客公园》《腾讯科技深网》这类中文科技长文的编辑风格
- 避免机翻腔、避免过度书面化、避免空洞修辞
- 标题要有“媒体标题感”，但不要标题党
- 小节标题要概括主题，不要只是重复问题

内容处理原则：
- 删除口头禅、重复句、无意义停顿、寒暄
- 保留关键观点、关键判断、关键例子、关键分歧
- 如果字幕里有明显的语病、重复、自我修正，请整理后输出通顺中文
- 若原文信息不足，不要脑补
- 若某段内容不重要，可适度压缩
- 若一段回答信息密度很高，可拆成两到三段，提升可读性

格式约束：
- 全文必须是合法 Markdown
- 使用：
  - # 一级标题
  - ## 二级标题
  - 普通段落
  - 发言人名: 开头的问答段落
- 不使用表格
- 不使用列表，除非字幕本身明确在枚举要点
- 不使用粗体滥标
- 不输出结语、总结、编者按，除非字幕本身自然收束到总结段

质量标准：
- 读起来像一篇“编辑整理后的中文访谈稿”
- 不是逐句翻译稿
- 不是摘要
- 是保留原对话关系的高可读中文成稿
`.trim();

function buildTranscriptExcerpt(chunks: TranscriptChunk[], budget = FINAL_TRANSCRIPT_CONTEXT_LIMIT): string {
  const rendered = chunks.map((chunk) => `[${formatTime(chunk.start)}-${formatTime(chunk.end)}] ${chunk.text}`);
  const total = rendered.join('\n');
  if (total.length <= budget) {
    return total;
  }

  const selectedIndexes = new Set<number>();
  const edge = Math.min(6, chunks.length);

  for (let index = 0; index < edge; index += 1) {
    selectedIndexes.add(index);
  }

  for (let index = Math.max(0, chunks.length - edge); index < chunks.length; index += 1) {
    selectedIndexes.add(index);
  }

  const middleCount = Math.max(0, 12 - selectedIndexes.size);
  for (let slot = 0; slot < middleCount; slot += 1) {
    const ratio = (slot + 1) / (middleCount + 1);
    selectedIndexes.add(Math.floor((chunks.length - 1) * ratio));
  }

  return [...selectedIndexes]
    .sort((left, right) => left - right)
    .map((index) => rendered[index])
    .join('\n');
}

function buildVideoMeta(bundle: TranscriptBundle): string {
  return [
    `源视频标题：${bundle.sourceTitle}`,
    `频道：${bundle.sourceAuthor}`,
    `字幕语言：${bundle.languageName} (${bundle.languageCode})`,
    `字幕类型：${bundle.isAutoGenerated ? '自动字幕' : '人工或标准字幕'}`,
    `时长：${formatTime(bundle.durationSeconds)}`,
  ].join('\n');
}

export function buildCompressionPrompt(
  bundle: TranscriptBundle,
  transcriptText: string,
  batchLabel?: string,
): string {
  return [
    '你是一位中文科技媒体编辑，请把下面的 YouTube 对话整理成一份“成稿提纲”。',
    '要求：',
    '- 只能依据字幕，不要补写字幕里不存在的事实或判断。',
    '- 使用简体中文。',
    '- 输出 Markdown。',
    '- 保持压缩，但不要丢掉核心论点、追问关系和语气张力。',
    '- 包含以下四部分：',
    '## 核心结论',
    '- 4 到 6 条简洁 bullet',
    '## 议题展开',
    '- 按主题梳理 4 到 6 个部分',
    '## 关键张力',
    '- 写出主持人与嘉宾争论、追问、判断的重点',
    '## 可引用表达',
    '- 6 到 10 条值得做成引语的原话或近似转述',
    '',
    batchLabel ? `当前片段：${batchLabel}` : '',
    buildVideoMeta(bundle),
    '',
    '对话内容：',
    transcriptText,
  ]
    .filter(Boolean)
    .join('\n');
}

export function buildCompressionMergePrompt(bundle: TranscriptBundle, batchSummaries: string[]): string {
  return [
    '你是一位中文科技媒体编辑，请把下面多段“分段提纲”合并成一份最终总提纲。',
    '要求：',
    '- 只能依据已有提纲，不要补充新事实。',
    '- 使用简体中文。',
    '- 输出 Markdown。',
    '- 去重、合并相近观点，保留最重要的论点和对话张力。',
    '- 结构固定为：',
    '## 核心结论',
    '## 议题展开',
    '## 关键张力',
    '## 可引用表达',
    '',
    buildVideoMeta(bundle),
    '',
    '分段提纲：',
    batchSummaries.map((summary, index) => `### 第 ${index + 1} 段\n${summary}`).join('\n\n'),
  ].join('\n');
}

export function buildArticlePrompt(bundle: TranscriptBundle, condensedBrief?: string): string {
  const transcriptContext = condensedBrief
    ? [
        '长视频整理提纲：',
        condensedBrief,
        '',
        '供校准语气的原字幕摘录：',
        buildTranscriptExcerpt(bundle.chunks),
      ].join('\n')
    : `字幕全文：\n${bundle.transcriptText}`;

  return [
    '请基于下面的 YouTube 字幕，输出一篇中文 Markdown 访谈整理稿。',
    '',
    '要求：',
    '1. 保留原始对话关系。',
    '2. 按主题分节。',
    '3. 标题和小节标题要有中文媒体编辑感。',
    '4. 忠于原意，不要虚构。',
    '5. 只输出 Markdown 正文。',
    '6. 二级标题请尽量使用 ## [00:00-03:20] 小节标题 这种格式，时间范围来自字幕讨论区间。',
    '7. 问答段落请尽量使用 [00:32] Jen: ... / [01:08] Mark: ... 这种格式。',
    '',
    buildVideoMeta(bundle),
    '',
    transcriptContext,
  ].join('\n');
}

export function buildOpeningArticlePrompt(
  bundle: TranscriptBundle,
  transcriptText: string,
  windowEndLabel: string,
): string {
  return [
    '你是一位中文媒体的深度编辑，正在提前起草一篇长篇访谈稿的开头部分。',
    '你只看到了这场访谈前半段的一部分内容，请先写出可以成立的“开篇版本”。',
    '',
    '硬性要求：',
    '- 只根据已提供的前段字幕写作，不要预告后文中尚未出现的观点。',
    '- 使用简体中文。',
    '- 只输出 Markdown，不要输出 HTML、代码块、表格。',
    '- 第一行必须是 # 一级标题。',
    '- 标题后写一段简短导语。',
    '- 接着写 2 到 4 个 ## 小节。',
    '- 每个 ## 小节都必须带时间戳，格式固定为：## [00:00-03:20] 小节标题。',
    '- 每节正文用问答形式书写，格式固定为：[00:32] Jen: ... / [01:08] Mark: ...',
    '- 这是“提前开篇”，不要写总结收束。',
    '',
    buildVideoMeta(bundle),
    `当前只允许使用 00:00 到 ${windowEndLabel} 左右的对话内容。`,
    '',
    '可用字幕：',
    transcriptText,
  ].join('\n');
}

export function buildContinuationArticlePrompt(
  bundle: TranscriptBundle,
  laterTranscriptText: string,
  openingWindowEndLabel: string,
  condensedBrief?: string,
): string {
  const context = condensedBrief
    ? ['后半程整理提纲：', condensedBrief, '', '后半程字幕：', laterTranscriptText].join('\n')
    : `后半程字幕：\n${laterTranscriptText}`;

  return [
    '你是一位中文媒体编辑，正在继续补写一篇已经开始成型的长篇访谈稿。',
    '开头部分已经根据前段对话写完，现在请只补写后续章节。',
    '',
    '硬性要求：',
    '- 不要重复主标题，不要重新写文章导语。',
    '- 只补写新的 ## 小节和最后的收束段。',
    '- 不要重复前半段已经覆盖的话题；前半段已覆盖到大约 ' + openingWindowEndLabel + '。',
    '- 每个 ## 小节都必须带时间戳，格式固定为：## [10:20-14:08] 小节标题。',
    '- 每节正文继续使用问答形式：[时间] 发言人: 内容。',
    '- 最后只写一个收束段，不要再加“总结”标题。',
    '- 只根据提供的字幕或提纲补写，不要脑补。',
    '',
    buildVideoMeta(bundle),
    '',
    context,
  ].join('\n');
}
