import type { TranscriptDialogueSliceResult, TranscriptSection } from './gemini';
import type { TranscriptBundle } from './youtube';

export const STORED_TRANSLATION_CONTENT_VERSION = 1;

export type StoredReadingMode = 'quick' | 'full';

export interface StoredTranslationSource {
  videoId: string;
  youtubeUrl: string;
  sourceTitle: string;
  sourceAuthor: string;
  sourceLanguageCode: string;
  sourceLanguage: string;
  isAutoGenerated: boolean;
  durationSeconds: number;
  thumbnailUrl: string;
}

export interface StoredTranslationHero {
  translatedTitleZh: string;
  displayTitle: string;
  summaryZh: string;
}

export interface StoredDialogueTurn {
  timestamp: string;
  speaker: string;
  textZh: string;
}

export interface StoredDialogueGroup {
  topicTitleZh: string;
  question?: StoredDialogueTurn;
  answers?: StoredDialogueTurn[];
  turns: StoredDialogueTurn[];
}

export interface StoredQuickSection {
  id: string;
  startLabel: string;
  endLabel: string;
  titleZh: string;
  summaryZh: string;
}

export interface StoredFullSection {
  id: string;
  startLabel: string;
  endLabel: string;
  titleZh: string;
  summaryZh: string;
  groups: StoredDialogueGroup[];
  turns: StoredDialogueTurn[];
}

interface StoredTranslationRenderingBase {
  readingMode: StoredReadingMode;
  hero: StoredTranslationHero;
  summary: string;
  speakers: string[];
  model: string;
  geminiTranslationComplete: boolean;
  translationNeedsRefresh: boolean;
}

export interface StoredQuickRendering extends StoredTranslationRenderingBase {
  readingMode: 'quick';
  sections: StoredQuickSection[];
}

export interface StoredFullRendering extends StoredTranslationRenderingBase {
  readingMode: 'full';
  sections: StoredFullSection[];
}

export interface StoredTranslationContent {
  version: number;
  cachedAt: number;
  source: StoredTranslationSource;
  renderings: Partial<{
    quick: StoredQuickRendering;
    full: StoredFullRendering;
  }>;
}

interface BuildRenderingBaseInput {
  translatedTitleZh?: string;
  summaryZh?: string;
  summary?: string;
  speakers?: string[];
  model?: string;
  geminiTranslationComplete?: boolean;
  translationNeedsRefresh?: boolean;
}

function normalizeString(value: string | undefined): string {
  return typeof value === 'string' ? value.trim() : '';
}

function normalizeStringArray(value: string[] | undefined): string[] {
  return Array.isArray(value)
    ? [...new Set(value.map((item) => normalizeString(item)).filter(Boolean))]
    : [];
}

function buildHero(sourceTitle: string, translatedTitleZh?: string, summaryZh?: string): StoredTranslationHero {
  const normalizedTranslatedTitle = normalizeString(translatedTitleZh);
  const normalizedSourceTitle = normalizeString(sourceTitle);
  return {
    translatedTitleZh: normalizedTranslatedTitle,
    displayTitle: normalizedTranslatedTitle || normalizedSourceTitle,
    summaryZh: normalizeString(summaryZh),
  };
}

function resolveSectionTitle(section: Pick<TranscriptSection, 'topicTitleZh' | 'subtitleZh' | 'subtitle'>): string {
  return normalizeString(section.topicTitleZh) || normalizeString(section.subtitleZh) || normalizeString(section.subtitle);
}

function resolveSectionSummary(section: Pick<TranscriptSection, 'topicSummaryZh' | 'summaryZh' | 'summary'>): string {
  return normalizeString(section.topicSummaryZh) || normalizeString(section.summaryZh) || normalizeString(section.summary);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === 'object' && !Array.isArray(value);
}

function isStoredDialogueTurn(value: unknown): value is StoredDialogueTurn {
  return isRecord(value)
    && typeof value.timestamp === 'string'
    && typeof value.speaker === 'string'
    && typeof value.textZh === 'string';
}

function isStoredDialogueGroup(value: unknown): value is StoredDialogueGroup {
  return isRecord(value)
    && typeof value.topicTitleZh === 'string'
    && Array.isArray(value.turns)
    && value.turns.every((item) => isStoredDialogueTurn(item))
    && (
      value.question === undefined
      || isStoredDialogueTurn(value.question)
    )
    && (
      value.answers === undefined
      || (Array.isArray(value.answers) && value.answers.every((item) => isStoredDialogueTurn(item)))
    );
}

function isStoredQuickSection(value: unknown): value is StoredQuickSection {
  return isRecord(value)
    && typeof value.id === 'string'
    && typeof value.startLabel === 'string'
    && typeof value.endLabel === 'string'
    && typeof value.titleZh === 'string'
    && typeof value.summaryZh === 'string';
}

function isStoredFullSection(value: unknown): value is StoredFullSection {
  return isRecord(value)
    && typeof value.id === 'string'
    && typeof value.startLabel === 'string'
    && typeof value.endLabel === 'string'
    && typeof value.titleZh === 'string'
    && typeof value.summaryZh === 'string'
    && Array.isArray(value.groups)
    && value.groups.every((item) => isStoredDialogueGroup(item))
    && Array.isArray(value.turns)
    && value.turns.every((item) => isStoredDialogueTurn(item));
}

function isStoredTranslationHero(value: unknown): value is StoredTranslationHero {
  return isRecord(value)
    && typeof value.translatedTitleZh === 'string'
    && typeof value.displayTitle === 'string'
    && typeof value.summaryZh === 'string';
}

function isStoredTranslationSource(value: unknown): value is StoredTranslationSource {
  return isRecord(value)
    && typeof value.videoId === 'string'
    && typeof value.youtubeUrl === 'string'
    && typeof value.sourceTitle === 'string'
    && typeof value.sourceAuthor === 'string'
    && typeof value.sourceLanguageCode === 'string'
    && typeof value.sourceLanguage === 'string'
    && typeof value.isAutoGenerated === 'boolean'
    && typeof value.durationSeconds === 'number'
    && typeof value.thumbnailUrl === 'string';
}

function isStoredTranslationRenderingBase(value: unknown): value is StoredTranslationRenderingBase {
  return isRecord(value)
    && (value.readingMode === 'quick' || value.readingMode === 'full')
    && isStoredTranslationHero(value.hero)
    && typeof value.summary === 'string'
    && Array.isArray(value.speakers)
    && value.speakers.every((item) => typeof item === 'string')
    && typeof value.model === 'string'
    && typeof value.geminiTranslationComplete === 'boolean'
    && typeof value.translationNeedsRefresh === 'boolean';
}

export function isStoredQuickRendering(value: unknown): value is StoredQuickRendering {
  if (!isStoredTranslationRenderingBase(value) || value.readingMode !== 'quick') {
    return false;
  }

  const record = value as unknown as Record<string, unknown>;
  return Array.isArray(record.sections) && record.sections.every((item) => isStoredQuickSection(item));
}

export function isStoredFullRendering(value: unknown): value is StoredFullRendering {
  if (!isStoredTranslationRenderingBase(value) || value.readingMode !== 'full') {
    return false;
  }

  const record = value as unknown as Record<string, unknown>;
  return Array.isArray(record.sections) && record.sections.every((item) => isStoredFullSection(item));
}

export function isStoredTranslationContent(value: unknown): value is StoredTranslationContent {
  if (!isRecord(value)) {
    return false;
  }

  const renderings = value.renderings;
  if (!isRecord(renderings)) {
    return false;
  }

  return (
    typeof value.version === 'number'
    && typeof value.cachedAt === 'number'
    && isStoredTranslationSource(value.source)
    && (renderings.quick === undefined || isStoredQuickRendering(renderings.quick))
    && (renderings.full === undefined || isStoredFullRendering(renderings.full))
  );
}

export function buildStoredTranslationSource(bundle: TranscriptBundle): StoredTranslationSource {
  return {
    videoId: bundle.videoId,
    youtubeUrl: `https://www.youtube.com/watch?v=${bundle.videoId}`,
    sourceTitle: normalizeString(bundle.sourceTitle),
    sourceAuthor: normalizeString(bundle.sourceAuthor),
    sourceLanguageCode: normalizeString(bundle.languageCode),
    sourceLanguage: normalizeString(bundle.languageName),
    isAutoGenerated: bundle.isAutoGenerated,
    durationSeconds: Math.max(0, Math.floor(bundle.durationSeconds)),
    thumbnailUrl: normalizeString(bundle.thumbnailUrl),
  };
}

export function buildStoredQuickRendering(
  bundle: TranscriptBundle,
  sections: TranscriptSection[],
  input: BuildRenderingBaseInput = {},
): StoredQuickRendering {
  return {
    readingMode: 'quick',
    hero: buildHero(bundle.sourceTitle, input.translatedTitleZh, input.summaryZh),
    summary: normalizeString(input.summary),
    speakers: normalizeStringArray(input.speakers),
    model: normalizeString(input.model),
    geminiTranslationComplete: input.geminiTranslationComplete !== false,
    translationNeedsRefresh: input.translationNeedsRefresh === true,
    sections: sections.map((section, index) => ({
      id: `quick-section-${index + 1}`,
      startLabel: normalizeString(section.startLabel),
      endLabel: normalizeString(section.endLabel),
      titleZh: resolveSectionTitle(section),
      summaryZh: resolveSectionSummary(section),
    })),
  };
}

export function buildStoredFullRendering(
  bundle: TranscriptBundle,
  slices: TranscriptDialogueSliceResult[],
  input: BuildRenderingBaseInput = {},
): StoredFullRendering {
  return {
    readingMode: 'full',
    hero: buildHero(bundle.sourceTitle, input.translatedTitleZh, input.summaryZh),
    summary: normalizeString(input.summary),
    speakers: normalizeStringArray(input.speakers),
    model: normalizeString(input.model),
    geminiTranslationComplete: input.geminiTranslationComplete !== false,
    translationNeedsRefresh: input.translationNeedsRefresh === true,
    sections: slices.map((slice, index) => ({
      id: `full-section-${index + 1}`,
      startLabel: normalizeString(slice.section.startLabel),
      endLabel: normalizeString(slice.section.endLabel),
      titleZh: resolveSectionTitle(slice.section),
      summaryZh: resolveSectionSummary(slice.section),
      groups: (slice.groups ?? []).map((group) => ({
        topicTitleZh: normalizeString(group.topicTitleZh),
        question: group.question
          ? {
              timestamp: normalizeString(group.question.timestamp),
              speaker: normalizeString(group.question.speaker),
              textZh: normalizeString(group.question.textZh),
            }
          : undefined,
        answers: (group.answers ?? []).map((answer) => ({
          timestamp: normalizeString(answer.timestamp),
          speaker: normalizeString(answer.speaker),
          textZh: normalizeString(answer.textZh),
        })),
        turns: group.turns.map((turn) => ({
          timestamp: normalizeString(turn.timestamp),
          speaker: normalizeString(turn.speaker),
          textZh: normalizeString(turn.textZh),
        })),
      })),
      turns: slice.turns.map((turn) => ({
        timestamp: normalizeString(turn.timestamp),
        speaker: normalizeString(turn.speaker),
        textZh: normalizeString(turn.textZh),
      })),
    })),
  };
}

export function buildStoredTranslationContent(
  bundle: TranscriptBundle,
  renderings: StoredTranslationContent['renderings'],
  cachedAt = Date.now(),
): StoredTranslationContent {
  return {
    version: STORED_TRANSLATION_CONTENT_VERSION,
    cachedAt,
    source: buildStoredTranslationSource(bundle),
    renderings,
  };
}
