import { AppError } from './errors';

const DEFAULT_USER_AGENT =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';

const VIDEO_ID_PATTERN = /^[a-zA-Z0-9_-]{11}$/;
const YOUTUBE_URL_PATTERN =
  /(?:v=|\/|v\/|embed\/|watch\?.*v=|youtu\.be\/|watch\?.*vi?=|\/embed\/|vi?\/)([a-zA-Z0-9_-]{11})/i;
const XML_TEXT_PATTERN = /<text start="([^"]*)" dur="([^"]*)">([\s\S]*?)<\/text>/g;

const XML_ENTITIES: Record<string, string> = {
  '&amp;': '&',
  '&lt;': '<',
  '&gt;': '>',
  '&quot;': '"',
  '&#39;': "'",
  '&apos;': "'",
};

const IGNORED_CUES = new Set(['[music]', '[applause]', '[laughter]', '[音樂]', '[音乐]', '[掌声]', '[笑声]']);

interface YoutubeCaptionTrack {
  baseUrl?: string;
  languageCode?: string;
  kind?: string;
  vssId?: string;
  name?: {
    simpleText?: string;
    runs?: Array<{ text?: string }>;
  };
}

interface YoutubeVideoDetails {
  title?: string;
  author?: string;
  channelId?: string;
  lengthSeconds?: string;
  viewCount?: string;
  thumbnail?: {
    thumbnails?: Array<{ url?: string }>;
  };
}

interface TranscriptSegment {
  text: string;
  duration: number;
  offset: number;
  lang: string;
}

export interface TranscriptChunk {
  start: number;
  end: number;
  text: string;
}

export interface TranscriptPreviewItem {
  startLabel: string;
  endLabel: string;
  text: string;
}

export interface TranscriptBundle {
  videoId: string;
  sourceTitle: string;
  sourceAuthor: string;
  channelId: string;
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
  durationSeconds: number;
  viewCount: number;
  thumbnailUrl: string;
  segments: TranscriptSegment[];
  chunks: TranscriptChunk[];
  transcriptText: string;
}

export interface TranscriptFetchCallbacks {
  onPreviewReady?: (payload: {
    videoId: string;
    sourceTitle: string;
    sourceAuthor: string;
    sourceLanguage: string;
    sourceLanguageCode: string;
    isAutoGenerated: boolean;
    thumbnailUrl: string;
    transcriptPreview: TranscriptPreviewItem[];
  }) => Promise<void> | void;
  onEarlyWindowReady?: (payload: {
    videoId: string;
    sourceTitle: string;
    sourceAuthor: string;
    sourceLanguage: string;
    sourceLanguageCode: string;
    isAutoGenerated: boolean;
    thumbnailUrl: string;
    chunks: TranscriptChunk[];
    transcriptText: string;
    windowEndLabel: string;
  }) => Promise<void> | void;
}

function decodeXmlEntities(text: string): string {
  return text.replace(/&(?:amp|lt|gt|quot|apos|#39);/g, (entity) => XML_ENTITIES[entity] ?? entity);
}

function normalizeWhitespace(text: string): string {
  return text.replace(/\s+/g, ' ').trim();
}

export function extractVideoId(input: string): string {
  if (VIDEO_ID_PATTERN.test(input)) {
    return input;
  }

  const match = input.match(YOUTUBE_URL_PATTERN);
  if (match?.[1]) {
    return match[1];
  }

  throw new AppError('invalid_video_id', '这不是一个合法的 YouTube 视频链接。', 400);
}

function readTrackName(track: YoutubeCaptionTrack): string {
  if (track.name?.simpleText) {
    return track.name.simpleText;
  }

  if (track.name?.runs?.length) {
    return track.name.runs.map((item) => item.text ?? '').join('').trim();
  }

  return track.languageCode ?? 'Unknown';
}

function isAutoTrack(track: YoutubeCaptionTrack): boolean {
  return track.kind === 'asr' || track.vssId?.startsWith('a.') === true;
}

function chooseCaptionTrack(tracks: YoutubeCaptionTrack[]): YoutubeCaptionTrack {
  const scoredTracks = [...tracks].sort((left, right) => scoreTrack(right) - scoreTrack(left));
  const track = scoredTracks[0];

  if (!track) {
    throw new AppError('missing_captions', '这个视频没有可用字幕。', 422);
  }

  return track;
}

function scoreTrack(track: YoutubeCaptionTrack): number {
  const languageCode = track.languageCode ?? '';
  let score = 0;

  if (!isAutoTrack(track)) {
    score += 100;
  }

  if (languageCode.startsWith('en')) {
    score += 60;
  }

  if (languageCode.startsWith('zh')) {
    score += 40;
  }

  if (track.kind !== 'forced') {
    score += 5;
  }

  return score;
}

function cleanSegmentText(text: string): string {
  const normalized = normalizeWhitespace(decodeXmlEntities(text));
  if (!normalized) {
    return '';
  }

  const lowered = normalized.toLowerCase();
  if (IGNORED_CUES.has(lowered)) {
    return '';
  }

  return normalized;
}

export function buildTranscriptChunks(segments: TranscriptSegment[]): TranscriptChunk[] {
  const chunks: TranscriptChunk[] = [];

  let current: TranscriptChunk | null = null;

  for (const segment of segments) {
    const text = cleanSegmentText(segment.text);
    if (!text) {
      continue;
    }

    const start = segment.offset;
    const end = segment.offset + segment.duration;

    if (!current) {
      current = { start, end, text };
      continue;
    }

    const gap = start - current.end;
    const nextLength = current.text.length + 1 + text.length;
    const shouldSplit =
      gap > 6 ||
      nextLength > 300 ||
      (current.text.length > 150 && /[.!?。！？]$/.test(current.text));

    if (shouldSplit) {
      chunks.push(current);
      current = { start, end, text };
      continue;
    }

    current.end = end;
    current.text = joinTranscriptText(current.text, text);
  }

  if (current) {
    chunks.push(current);
  }

  return chunks;
}

function joinTranscriptText(left: string, right: string): string {
  if (!left) {
    return right;
  }

  if (/[-/([]$/.test(left) || /^[,.;:!?)]/.test(right)) {
    return `${left}${right}`;
  }

  return `${left} ${right}`;
}

function formatTrackLanguage(track: YoutubeCaptionTrack): { languageCode: string; languageName: string } {
  return {
    languageCode: track.languageCode ?? 'unknown',
    languageName: readTrackName(track),
  };
}

async function fetchText(url: string, init?: RequestInit): Promise<string> {
  const response = await fetchResponse(url, init);
  return response.text();
}

async function fetchResponse(url: string, init?: RequestInit): Promise<Response> {
  const response = await fetch(url, {
    ...init,
    headers: {
      'user-agent': DEFAULT_USER_AGENT,
      ...(init?.headers ?? {}),
    },
  });

  if (!response.ok) {
    throw new AppError('youtube_fetch_failed', '抓取 YouTube 信息失败，请稍后重试。', 502);
  }

  return response;
}

async function fetchJson<T>(url: string, init?: RequestInit): Promise<T> {
  const response = await fetch(url, {
    ...init,
    headers: {
      'content-type': 'application/json',
      'user-agent': DEFAULT_USER_AGENT,
      ...(init?.headers ?? {}),
    },
  });

  if (!response.ok) {
    throw new AppError('youtube_player_failed', '读取 YouTube 播放信息失败。', 502);
  }

  return (await response.json()) as T;
}

function parseTranscriptXml(xml: string, languageCode: string): TranscriptSegment[] {
  const segments = [...xml.matchAll(XML_TEXT_PATTERN)].map((match) => ({
    text: match[3],
    duration: Number.parseFloat(match[2] ?? '0'),
    offset: Number.parseFloat(match[1] ?? '0'),
    lang: languageCode,
  }));

  if (!segments.length) {
    throw new AppError('empty_transcript', '字幕抓取成功，但没有解析到可读文本。', 422);
  }

  return segments;
}

function extractSegmentsFromBuffer(buffer: string, languageCode: string): { segments: TranscriptSegment[]; rest: string } {
  const segments: TranscriptSegment[] = [];
  let lastCompleteEnd = 0;

  XML_TEXT_PATTERN.lastIndex = 0;
  let match: RegExpExecArray | null;
  while ((match = XML_TEXT_PATTERN.exec(buffer))) {
    segments.push({
      text: match[3],
      duration: Number.parseFloat(match[2] ?? '0'),
      offset: Number.parseFloat(match[1] ?? '0'),
      lang: languageCode,
    });
    lastCompleteEnd = match.index + match[0].length;
  }

  return {
    segments,
    rest: lastCompleteEnd > 0 ? buffer.slice(lastCompleteEnd) : buffer,
  };
}

async function parseTranscriptResponse(
  response: Response,
  languageCode: string,
  callbacks?: TranscriptFetchCallbacks,
  previewMeta?: {
    videoId: string;
    sourceTitle: string;
    sourceAuthor: string;
    sourceLanguage: string;
    sourceLanguageCode: string;
    isAutoGenerated: boolean;
    thumbnailUrl: string;
  },
): Promise<TranscriptSegment[]> {
  if (!response.body) {
    return parseTranscriptXml(await response.text(), languageCode);
  }

  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  const segments: TranscriptSegment[] = [];
  let buffer = '';
  let previewSent = false;
  let earlyWindowSent = false;
  const EARLY_WINDOW_SECONDS = 8 * 60;

  while (true) {
    const { value, done } = await reader.read();
    if (done) {
      break;
    }

    buffer += decoder.decode(value, { stream: true });
    const extracted = extractSegmentsFromBuffer(buffer, languageCode);
    buffer = extracted.rest;
    segments.push(...extracted.segments);

    if (!previewSent && previewMeta) {
      const previewChunks = buildTranscriptChunks(segments);
      if (previewChunks.length >= 3) {
        previewSent = true;
        await callbacks?.onPreviewReady?.({
          ...previewMeta,
          transcriptPreview: buildTranscriptPreview(previewChunks, 6),
        });
      }
    }

    if (!earlyWindowSent && previewMeta) {
      const currentChunks = buildTranscriptChunks(segments);
      const earlyChunks = currentChunks.filter((chunk) => chunk.start < EARLY_WINDOW_SECONDS);
      const lastEarlyChunk = earlyChunks.at(-1);
      if (earlyChunks.length >= 6 && (lastEarlyChunk?.end ?? 0) >= EARLY_WINDOW_SECONDS) {
        earlyWindowSent = true;
        await callbacks?.onEarlyWindowReady?.({
          ...previewMeta,
          chunks: earlyChunks,
          transcriptText: buildTranscriptTextFromChunks(earlyChunks),
          windowEndLabel: formatTime(lastEarlyChunk?.end ?? EARLY_WINDOW_SECONDS),
        });
      }
    }
  }

  buffer += decoder.decode();
  const trailing = extractSegmentsFromBuffer(buffer, languageCode);
  segments.push(...trailing.segments);

  if (!segments.length) {
    throw new AppError('empty_transcript', '字幕抓取成功，但没有解析到可读文本。', 422);
  }

  if (!previewSent && previewMeta) {
    const previewChunks = buildTranscriptChunks(segments);
    if (previewChunks.length) {
      await callbacks?.onPreviewReady?.({
        ...previewMeta,
        transcriptPreview: buildTranscriptPreview(previewChunks, 6),
      });
    }
  }

  if (!earlyWindowSent && previewMeta) {
    const currentChunks = buildTranscriptChunks(segments);
    if (currentChunks.length) {
      const lastChunk = currentChunks.at(-1);
      await callbacks?.onEarlyWindowReady?.({
        ...previewMeta,
        chunks: currentChunks,
        transcriptText: buildTranscriptTextFromChunks(currentChunks),
        windowEndLabel: formatTime(lastChunk?.end ?? 0),
      });
    }
  }

  return segments;
}

function extractInnertubeApiKey(watchHtml: string): string {
  const match =
    watchHtml.match(/"INNERTUBE_API_KEY":"([^"]+)"/) ??
    watchHtml.match(/INNERTUBE_API_KEY\\":\\"([^\\"]+)\\"/);

  if (!match?.[1]) {
    throw new AppError('missing_innertube_key', '无法从 YouTube 页面中提取字幕接口。', 422);
  }

  return match[1];
}

function extractPlayerCaptionTracks(playerJson: Record<string, any>): YoutubeCaptionTrack[] {
  const renderer =
    playerJson.captions?.playerCaptionsTracklistRenderer ?? playerJson.playerCaptionsTracklistRenderer;

  if (!renderer) {
    const status = playerJson.playabilityStatus?.status;
    if (status && status !== 'OK') {
      throw new AppError('video_unavailable', '这个视频当前不可访问，无法提取字幕。', 422);
    }

    throw new AppError('captions_disabled', '这个视频没有开放可抓取字幕。', 422);
  }

  const tracks = renderer.captionTracks;
  if (!Array.isArray(tracks) || tracks.length === 0) {
    throw new AppError('captions_missing', '这个视频没有可用字幕轨道。', 422);
  }

  return tracks as YoutubeCaptionTrack[];
}

function formatSourceTitle(videoId: string, details?: YoutubeVideoDetails): string {
  return details?.title?.trim() || `YouTube 视频 ${videoId}`;
}

function formatSourceAuthor(details?: YoutubeVideoDetails): string {
  return details?.author?.trim() || 'Unknown Channel';
}

export function buildTranscriptTextFromChunks(chunks: TranscriptChunk[]): string {
  return chunks.map((chunk) => chunk.text).join('\n');
}

export function formatTime(seconds: number): string {
  const rounded = Math.max(0, Math.floor(seconds));
  const hour = Math.floor(rounded / 3600);
  const minute = Math.floor((rounded % 3600) / 60);
  const second = rounded % 60;

  if (hour > 0) {
    return `${String(hour).padStart(2, '0')}:${String(minute).padStart(2, '0')}:${String(second).padStart(2, '0')}`;
  }

  return `${String(minute).padStart(2, '0')}:${String(second).padStart(2, '0')}`;
}

export function buildTranscriptPreview(
  chunks: TranscriptChunk[],
  maxItems = 10,
  maxTextLength = 220,
): TranscriptPreviewItem[] {
  return chunks.slice(0, maxItems).map((chunk) => {
    const text = chunk.text.length > maxTextLength ? `${chunk.text.slice(0, maxTextLength).trim()}...` : chunk.text;
    return {
      startLabel: formatTime(chunk.start),
      endLabel: formatTime(chunk.end),
      text,
    };
  });
}

export async function fetchTranscriptBundle(input: string, callbacks?: TranscriptFetchCallbacks): Promise<TranscriptBundle> {
  const videoId = extractVideoId(input);
  const watchHtml = await fetchText(`https://www.youtube.com/watch?v=${videoId}`);

  if (watchHtml.includes('g-recaptcha')) {
    throw new AppError('youtube_rate_limited', 'YouTube 暂时触发了风控，请稍后再试。', 429);
  }

  const apiKey = extractInnertubeApiKey(watchHtml);
  const playerJson = await fetchJson<Record<string, any>>(
    `https://www.youtube.com/youtubei/v1/player?key=${apiKey}`,
    {
      method: 'POST',
      body: JSON.stringify({
        context: {
          client: {
            clientName: 'ANDROID',
            clientVersion: '20.10.38',
          },
        },
        videoId,
      }),
    },
  );

  const tracks = extractPlayerCaptionTracks(playerJson);
  const selectedTrack = chooseCaptionTrack(tracks);
  const { languageCode, languageName } = formatTrackLanguage(selectedTrack);
  const transcriptUrl = (selectedTrack.baseUrl ?? '').replace(/&fmt=[^&]+/, '');

  if (!transcriptUrl) {
    throw new AppError('missing_transcript_url', '找到了字幕轨道，但无法读取字幕内容。', 422);
  }

  const details = playerJson.videoDetails as YoutubeVideoDetails | undefined;
  const thumbnails = details?.thumbnail?.thumbnails ?? [];
  const previewMeta = {
    videoId,
    sourceTitle: formatSourceTitle(videoId, details),
    sourceAuthor: formatSourceAuthor(details),
    sourceLanguage: languageName,
    sourceLanguageCode: languageCode,
    isAutoGenerated: isAutoTrack(selectedTrack),
    thumbnailUrl: thumbnails.at(-1)?.url ?? '',
  };
  const transcriptResponse = await fetchResponse(transcriptUrl);
  const segments = await parseTranscriptResponse(transcriptResponse, languageCode, callbacks, previewMeta);
  const chunks = buildTranscriptChunks(segments);

  if (!chunks.length) {
    throw new AppError('empty_transcript_after_cleanup', '字幕内容过于稀薄，无法整理成 transcript。', 422);
  }

  return {
    videoId,
    sourceTitle: formatSourceTitle(videoId, details),
    sourceAuthor: formatSourceAuthor(details),
    channelId: details?.channelId ?? '',
    languageCode,
    languageName,
    isAutoGenerated: isAutoTrack(selectedTrack),
    durationSeconds: Number.parseInt(details?.lengthSeconds ?? '0', 10) || Math.ceil(chunks.at(-1)?.end ?? 0),
    viewCount: Number.parseInt(details?.viewCount ?? '0', 10) || 0,
    thumbnailUrl: thumbnails.at(-1)?.url ?? '',
    segments,
    chunks,
    transcriptText: buildTranscriptTextFromChunks(chunks),
  };
}
