import {
  fetchTranscript as fetchTranscriptPlus,
  YoutubeTranscriptDisabledError,
  YoutubeTranscriptInvalidVideoIdError,
  YoutubeTranscriptNotAvailableError,
  YoutubeTranscriptNotAvailableLanguageError,
  YoutubeTranscriptTooManyRequestError,
  YoutubeTranscriptVideoUnavailableError,
  type FetchParams as YoutubeTranscriptFetchParams,
  type TranscriptResult as YoutubeTranscriptPlusResult,
} from 'youtube-transcript-plus';
import { createAbortError, isAbortError, throwIfAborted } from './abort';
import { AppError } from './errors';

const DEFAULT_USER_AGENT =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';
const DEFAULT_ACCEPT_LANGUAGE = 'en-US,en;q=0.9';
const YOUTUBE_FETCH_MAX_ATTEMPTS = 3;
const YOUTUBE_FETCH_RETRY_BASE_MS = 250;
const RETRYABLE_YOUTUBE_STATUSES = new Set([429, 500, 502, 503, 504]);

const VIDEO_ID_PATTERN = /^[a-zA-Z0-9_-]{11}$/;
const YOUTUBE_URL_PATTERN =
  /(?:v=|\/|v\/|embed\/|watch\?.*v=|youtu\.be\/|watch\?.*vi?=|\/embed\/|vi?\/)([a-zA-Z0-9_-]{11})/i;
const XML_TEXT_PATTERN = /<text start="([^"]*)" dur="([^"]*)">([\s\S]*?)<\/text>/g;

const XML_ENTITIES: Record<string, string> = {
  '&amp;': '&',
  '&lt;': '<',
  '&gt;': '>',
  '&quot;': '"',
  '&#39;': "'",
  '&apos;': "'",
};
const HTML_ENTITIES: Record<string, string> = {
  ...XML_ENTITIES,
  '&nbsp;': ' ',
};

const IGNORED_CUES = new Set(['[music]', '[applause]', '[laughter]', '[音樂]', '[音乐]', '[掌声]', '[笑声]']);

interface YoutubeCaptionTrack {
  baseUrl?: string;
  languageCode?: string;
  kind?: string;
  vssId?: string;
  name?: {
    simpleText?: string;
    runs?: Array<{ text?: string }>;
  };
}

interface YoutubeVideoDetails {
  title?: string;
  author?: string;
  channelId?: string;
  lengthSeconds?: string;
  viewCount?: string;
  thumbnail?: {
    thumbnails?: Array<{ url?: string }>;
  };
}

interface YoutubePlayabilityStatus {
  status?: string;
  reason?: unknown;
  messages?: unknown[];
  errorScreen?: {
    playerErrorMessageRenderer?: {
      reason?: unknown;
      subreason?: unknown;
    };
  };
}

interface TranscriptSegment {
  text: string;
  duration: number;
  offset: number;
  lang: string;
}

export interface TranscriptChunk {
  start: number;
  end: number;
  text: string;
}

export interface TranscriptPreviewItem {
  startLabel: string;
  endLabel: string;
  text: string;
}

export interface TranscriptBundle {
  videoId: string;
  sourceTitle: string;
  sourceAuthor: string;
  channelId: string;
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
  durationSeconds: number;
  viewCount: number;
  thumbnailUrl: string;
  segments: TranscriptSegment[];
  chunks: TranscriptChunk[];
  transcriptText: string;
}

function isTranscriptChunkArray(value: unknown): value is TranscriptChunk[] {
  return Array.isArray(value) && value.every((item) => {
    if (!item || typeof item !== 'object') {
      return false;
    }

    const chunk = item as Record<string, unknown>;
    return (
      typeof chunk.start === 'number' &&
      typeof chunk.end === 'number' &&
      typeof chunk.text === 'string'
    );
  });
}

export function isTranscriptBundle(value: unknown): value is TranscriptBundle {
  if (!value || typeof value !== 'object') {
    return false;
  }

  const bundle = value as Record<string, unknown>;
  return (
    typeof bundle.videoId === 'string' &&
    typeof bundle.sourceTitle === 'string' &&
    typeof bundle.sourceAuthor === 'string' &&
    typeof bundle.channelId === 'string' &&
    typeof bundle.languageCode === 'string' &&
    typeof bundle.languageName === 'string' &&
    typeof bundle.isAutoGenerated === 'boolean' &&
    typeof bundle.durationSeconds === 'number' &&
    typeof bundle.viewCount === 'number' &&
    typeof bundle.thumbnailUrl === 'string' &&
    Array.isArray(bundle.segments) &&
    isTranscriptChunkArray(bundle.chunks) &&
    typeof bundle.transcriptText === 'string'
  );
}

export interface TranscriptFetchCallbacks {
  onPreviewReady?: (payload: {
    videoId: string;
    sourceTitle: string;
    sourceAuthor: string;
    sourceLanguage: string;
    sourceLanguageCode: string;
    isAutoGenerated: boolean;
    thumbnailUrl: string;
    transcriptPreview: TranscriptPreviewItem[];
  }) => Promise<void> | void;
  onEarlyWindowReady?: (payload: {
    videoId: string;
    sourceTitle: string;
    sourceAuthor: string;
    sourceLanguage: string;
    sourceLanguageCode: string;
    isAutoGenerated: boolean;
    thumbnailUrl: string;
    chunks: TranscriptChunk[];
    transcriptText: string;
    windowEndLabel: string;
  }) => Promise<void> | void;
}

type SupadataTranscriptMode = 'native' | 'auto' | 'generate';

export interface TranscriptProviderOptions {
  supadataApiKey?: string;
  supadataMode?: string;
}

interface SupadataTranscriptSegment {
  text?: unknown;
  offset?: unknown;
  duration?: unknown;
  lang?: unknown;
}

interface SupadataTranscriptResponse {
  content?: unknown;
  lang?: unknown;
  availableLangs?: unknown;
  jobId?: unknown;
  status?: unknown;
  error?: unknown;
  result?: unknown;
}

const SUPADATA_API_BASE_URL = 'https://api.supadata.ai/v1';
const SUPADATA_POLL_INTERVAL_MS = 1000;
const SUPADATA_MAX_POLL_ATTEMPTS = 65;
const GENERAL_YOUTUBE_FAILURE_CODES = new Set([
  'youtube_fetch_failed',
  'youtube_rate_limited',
  'youtube_player_failed',
  'missing_innertube_key',
]);

export function buildVideoBootstrapUrls(videoId: string): string[] {
  const watchQuery = `v=${videoId}&hl=en&persist_hl=1&bpctr=9999999999&has_verified=1`;
  return [
    `https://www.youtube.com/watch?${watchQuery}`,
    `https://m.youtube.com/watch?${watchQuery}`,
    `https://www.youtube.com/embed/${videoId}?hl=en`,
  ];
}

function decodeXmlEntities(text: string): string {
  return text.replace(/&(?:amp|lt|gt|quot|apos|#39);/g, (entity) => XML_ENTITIES[entity] ?? entity);
}

function normalizeWhitespace(text: string): string {
  return text.replace(/\s+/g, ' ').trim();
}

function decodeHtmlEntities(text: string): string {
  return text
    .replace(/&#(\d+);/g, (_match, codePoint) => String.fromCodePoint(Number.parseInt(codePoint, 10)))
    .replace(/&#x([0-9a-f]+);/gi, (_match, codePoint) => String.fromCodePoint(Number.parseInt(codePoint, 16)))
    .replace(/&(?:amp|lt|gt|quot|apos|nbsp|#39);/g, (entity) => HTML_ENTITIES[entity] ?? entity);
}

function escapeRegExp(text: string): string {
  return text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function normalizeHtmlContent(text: string): string {
  return normalizeWhitespace(decodeHtmlEntities(text));
}

function stripYoutubeTitleSuffix(text: string): string {
  return normalizeWhitespace(text.replace(/\s*-\s*YouTube$/i, ''));
}

function normalizeComparableTitle(text: string): string {
  return stripYoutubeTitleSuffix(text).toLowerCase();
}

function isGenericYoutubeTitle(text: string): boolean {
  const normalized = normalizeComparableTitle(text);
  return (
    normalized === 'youtube'
    || normalized === 'youtube video'
    || normalized === 'youtube videos'
    || normalized === 'youtube 视频'
    || normalized === 'youtube 影片'
    || normalized === 'youtube 影集'
  );
}

function extractMetaTagContent(source: string, attribute: 'property' | 'name' | 'itemprop', value: string): string {
  const escapedValue = escapeRegExp(value);
  const patterns = [
    new RegExp(`<meta[^>]*${attribute}=["']${escapedValue}["'][^>]*content=["']([^"']+)["'][^>]*>`, 'i'),
    new RegExp(`<meta[^>]*content=["']([^"']+)["'][^>]*${attribute}=["']${escapedValue}["'][^>]*>`, 'i'),
  ];

  for (const pattern of patterns) {
    const match = source.match(pattern);
    if (match?.[1]) {
      return normalizeHtmlContent(match[1]);
    }
  }

  return '';
}

function extractLinkTagValue(
  source: string,
  attribute: 'itemprop' | 'rel',
  value: string,
  targetAttribute: 'href' | 'content',
): string {
  const escapedValue = escapeRegExp(value);
  const patterns = [
    new RegExp(`<link[^>]*${attribute}=["']${escapedValue}["'][^>]*${targetAttribute}=["']([^"']+)["'][^>]*>`, 'i'),
    new RegExp(`<link[^>]*${targetAttribute}=["']([^"']+)["'][^>]*${attribute}=["']${escapedValue}["'][^>]*>`, 'i'),
  ];

  for (const pattern of patterns) {
    const match = source.match(pattern);
    if (match?.[1]) {
      return normalizeHtmlContent(match[1]);
    }
  }

  return '';
}

function extractTitleTagContent(source: string): string {
  const match = source.match(/<title>([\s\S]*?)<\/title>/i);
  return match?.[1] ? stripYoutubeTitleSuffix(normalizeHtmlContent(match[1])) : '';
}

function extractWatchHtmlVideoDetails(source: string): YoutubeVideoDetails | undefined {
  const rawTitle = stripYoutubeTitleSuffix(
    extractMetaTagContent(source, 'property', 'og:title')
      || extractMetaTagContent(source, 'itemprop', 'name')
      || extractMetaTagContent(source, 'name', 'title')
      || extractTitleTagContent(source),
  );
  const title = rawTitle && !isGenericYoutubeTitle(rawTitle) ? rawTitle : '';
  const authorMatch = source.match(
    /<span[^>]*itemprop=["']author["'][^>]*>[\s\S]*?<link[^>]*itemprop=["']name["'][^>]*content=["']([^"']+)["']/i,
  );
  const author = authorMatch?.[1] ? normalizeHtmlContent(authorMatch[1]) : '';
  const thumbnailUrl = extractMetaTagContent(source, 'property', 'og:image')
    || extractLinkTagValue(source, 'itemprop', 'thumbnailUrl', 'href');

  if (!title && !author && !thumbnailUrl) {
    return undefined;
  }

  return {
    title: title || undefined,
    author: author || undefined,
    thumbnail: thumbnailUrl
      ? {
          thumbnails: [{ url: thumbnailUrl }],
        }
      : undefined,
  };
}

function hasVideoTitle(details?: YoutubeVideoDetails): boolean {
  return Boolean(details?.title?.trim());
}

function hasMeaningfulVideoTitle(details?: YoutubeVideoDetails): boolean {
  const title = details?.title?.trim() ?? '';
  return Boolean(title) && !isGenericYoutubeTitle(title);
}

function hasVideoAuthor(details?: YoutubeVideoDetails): boolean {
  return Boolean(details?.author?.trim());
}

function hasVideoThumbnail(details?: YoutubeVideoDetails): boolean {
  return Boolean(details?.thumbnail?.thumbnails?.some((thumbnail) => Boolean(thumbnail.url?.trim())));
}

function mergeVideoDetails(
  primary?: YoutubeVideoDetails,
  fallback?: YoutubeVideoDetails,
): YoutubeVideoDetails | undefined {
  if (!primary && !fallback) {
    return undefined;
  }

  const primaryThumbnails = (primary?.thumbnail?.thumbnails ?? [])
    .filter((thumbnail) => Boolean(thumbnail.url?.trim()))
    .map((thumbnail) => ({ url: thumbnail.url?.trim() }));
  const fallbackThumbnails = (fallback?.thumbnail?.thumbnails ?? [])
    .filter((thumbnail) => Boolean(thumbnail.url?.trim()))
    .map((thumbnail) => ({ url: thumbnail.url?.trim() }));

  return {
    title: hasMeaningfulVideoTitle(primary)
      ? primary?.title?.trim()
      : hasMeaningfulVideoTitle(fallback)
        ? fallback?.title?.trim()
        : primary?.title?.trim() || fallback?.title?.trim(),
    author: primary?.author?.trim() || fallback?.author?.trim(),
    channelId: primary?.channelId?.trim() || fallback?.channelId?.trim(),
    lengthSeconds: primary?.lengthSeconds?.trim() || fallback?.lengthSeconds?.trim(),
    viewCount: primary?.viewCount?.trim() || fallback?.viewCount?.trim(),
    thumbnail: primaryThumbnails.length
      ? { thumbnails: primaryThumbnails }
      : fallbackThumbnails.length
        ? { thumbnails: fallbackThumbnails }
        : undefined,
  };
}

export function extractVideoId(input: string): string {
  if (VIDEO_ID_PATTERN.test(input)) {
    return input;
  }

  const match = input.match(YOUTUBE_URL_PATTERN);
  if (match?.[1]) {
    return match[1];
  }

  throw new AppError('invalid_video_id', '这不是一个合法的 YouTube 视频链接。', 400);
}

function readTrackName(track: YoutubeCaptionTrack): string {
  if (track.name?.simpleText) {
    return track.name.simpleText;
  }

  if (track.name?.runs?.length) {
    return track.name.runs.map((item) => item.text ?? '').join('').trim();
  }

  return track.languageCode ?? 'Unknown';
}

function readTextValue(value: unknown): string {
  if (typeof value === 'string') {
    return normalizeWhitespace(value);
  }

  if (!value || typeof value !== 'object') {
    return '';
  }

  const record = value as Record<string, unknown>;
  if (typeof record.simpleText === 'string') {
    return normalizeWhitespace(record.simpleText);
  }

  if (Array.isArray(record.runs)) {
    return normalizeWhitespace(
      record.runs
        .map((item) => (
          item
          && typeof item === 'object'
          && typeof (item as { text?: unknown }).text === 'string'
        ) ? String((item as { text: string }).text) : '')
        .join(''),
    );
  }

  return '';
}

function isAutoTrack(track: YoutubeCaptionTrack): boolean {
  return track.kind === 'asr' || track.vssId?.startsWith('a.') === true;
}

function chooseCaptionTrack(tracks: YoutubeCaptionTrack[]): YoutubeCaptionTrack {
  const scoredTracks = [...tracks].sort((left, right) => scoreTrack(right) - scoreTrack(left));
  const track = scoredTracks[0];

  if (!track) {
    throw new AppError('missing_captions', '这个视频没有可用字幕。', 422);
  }

  return track;
}

function scoreTrack(track: YoutubeCaptionTrack): number {
  const languageCode = track.languageCode ?? '';
  let score = 0;

  if (!isAutoTrack(track)) {
    score += 100;
  }

  if (languageCode.startsWith('en')) {
    score += 60;
  }

  if (languageCode.startsWith('zh')) {
    score += 40;
  }

  if (track.kind !== 'forced') {
    score += 5;
  }

  return score;
}

function cleanSegmentText(text: string): string {
  const normalized = normalizeWhitespace(decodeXmlEntities(text));
  if (!normalized) {
    return '';
  }

  const lowered = normalized.toLowerCase();
  if (IGNORED_CUES.has(lowered)) {
    return '';
  }

  return normalized;
}

export function buildTranscriptChunks(segments: TranscriptSegment[]): TranscriptChunk[] {
  const chunks: TranscriptChunk[] = [];

  let current: TranscriptChunk | null = null;

  for (const segment of segments) {
    const text = cleanSegmentText(segment.text);
    if (!text) {
      continue;
    }

    const start = segment.offset;
    const end = segment.offset + segment.duration;

    if (!current) {
      current = { start, end, text };
      continue;
    }

    const gap = start - current.end;
    const nextLength = current.text.length + 1 + text.length;
    const shouldSplit =
      gap > 6 ||
      nextLength > 300 ||
      (current.text.length > 150 && /[.!?。！？]$/.test(current.text));

    if (shouldSplit) {
      chunks.push(current);
      current = { start, end, text };
      continue;
    }

    current.end = end;
    current.text = joinTranscriptText(current.text, text);
  }

  if (current) {
    chunks.push(current);
  }

  return chunks;
}

function joinTranscriptText(left: string, right: string): string {
  if (!left) {
    return right;
  }

  if (/[-/([]$/.test(left) || /^[,.;:!?)]/.test(right)) {
    return `${left}${right}`;
  }

  return `${left} ${right}`;
}

function formatTrackLanguage(track: YoutubeCaptionTrack): { languageCode: string; languageName: string } {
  return {
    languageCode: track.languageCode ?? 'unknown',
    languageName: readTrackName(track),
  };
}

function normalizeSupadataMode(value?: string): SupadataTranscriptMode {
  if (value === 'auto' || value === 'generate') {
    return value;
  }

  return 'native';
}

function shouldUseSupadataFallback(options?: TranscriptProviderOptions): boolean {
  return Boolean(options?.supadataApiKey?.trim());
}

function shouldAttemptSupadataFallback(error: AppError, options?: TranscriptProviderOptions): boolean {
  if (!shouldUseSupadataFallback(options)) {
    return false;
  }

  return (
    GENERAL_YOUTUBE_FAILURE_CODES.has(error.code)
    || error.code === 'video_unavailable'
    || error.code === 'captions_disabled'
    || error.code === 'captions_missing'
    || error.code === 'missing_captions'
    || error.code === 'missing_transcript_url'
    || error.code === 'empty_transcript'
    || error.code === 'empty_transcript_after_cleanup'
  );
}

function preferSupadataError(primary: AppError, fallback: AppError): boolean {
  if (!GENERAL_YOUTUBE_FAILURE_CODES.has(primary.code)) {
    return false;
  }

  return !GENERAL_YOUTUBE_FAILURE_CODES.has(fallback.code);
}

function formatLanguageName(languageCode: string): string {
  return normalizeWhitespace(languageCode) || 'unknown';
}

function resolveThumbnailUrl(videoId: string, details?: YoutubeVideoDetails, explicitUrl?: string): string {
  const trimmedExplicitUrl = explicitUrl?.trim();
  if (trimmedExplicitUrl) {
    return trimmedExplicitUrl;
  }

  const thumbnails = details?.thumbnail?.thumbnails ?? [];
  const detailThumbnailUrl = thumbnails.at(-1)?.url?.trim();
  if (detailThumbnailUrl) {
    return detailThumbnailUrl;
  }

  return `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`;
}

function buildPreviewMeta(
  videoId: string,
  details: YoutubeVideoDetails | undefined,
  languageCode: string,
  languageName: string,
  isAutoGenerated: boolean,
  thumbnailUrl?: string,
) {
  return {
    videoId,
    sourceTitle: formatSourceTitle(videoId, details),
    sourceAuthor: formatSourceAuthor(details),
    sourceLanguage: languageName,
    sourceLanguageCode: languageCode,
    isAutoGenerated,
    thumbnailUrl: resolveThumbnailUrl(videoId, details, thumbnailUrl),
  };
}

function buildTranscriptBundleResult(
  videoId: string,
  details: YoutubeVideoDetails | undefined,
  languageCode: string,
  languageName: string,
  isAutoGenerated: boolean,
  segments: TranscriptSegment[],
  chunks: TranscriptChunk[],
  thumbnailUrl?: string,
): TranscriptBundle {
  return {
    videoId,
    sourceTitle: formatSourceTitle(videoId, details),
    sourceAuthor: formatSourceAuthor(details),
    channelId: details?.channelId ?? '',
    languageCode,
    languageName,
    isAutoGenerated,
    durationSeconds: Number.parseInt(details?.lengthSeconds ?? '0', 10) || Math.ceil(chunks.at(-1)?.end ?? 0),
    viewCount: Number.parseInt(details?.viewCount ?? '0', 10) || 0,
    thumbnailUrl: resolveThumbnailUrl(videoId, details, thumbnailUrl),
    segments,
    chunks,
    transcriptText: buildTranscriptTextFromChunks(chunks),
  };
}

async function fetchText(url: string, init?: RequestInit): Promise<string> {
  const response = await fetchResponse(url, init);
  return response.text();
}

function sleep(ms: number, signal?: AbortSignal): Promise<void> {
  if (ms <= 0) {
    return Promise.resolve();
  }

  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => {
      signal?.removeEventListener('abort', onAbort);
      resolve();
    }, ms);

    const onAbort = () => {
      clearTimeout(timer);
      reject(createAbortError(signal?.reason));
    };

    if (signal) {
      if (signal.aborted) {
        onAbort();
        return;
      }
      signal.addEventListener('abort', onAbort, { once: true });
    }
  });
}

function shouldRetryYoutubeStatus(status: number): boolean {
  return RETRYABLE_YOUTUBE_STATUSES.has(status);
}

function buildYoutubeHeaders(init?: RequestInit): Headers {
  const headers = new Headers(init?.headers);
  if (!headers.has('user-agent')) {
    headers.set('user-agent', DEFAULT_USER_AGENT);
  }
  if (!headers.has('accept-language')) {
    headers.set('accept-language', DEFAULT_ACCEPT_LANGUAGE);
  }
  if (!headers.has('accept')) {
    headers.set('accept', '*/*');
  }
  return headers;
}

function readCaptionTracksFromPlayerJson(playerJson: Record<string, any> | null | undefined): YoutubeCaptionTrack[] {
  if (!playerJson || typeof playerJson !== 'object') {
    return [];
  }

  const renderer =
    playerJson.captions?.playerCaptionsTracklistRenderer ?? playerJson.playerCaptionsTracklistRenderer;
  const tracks = renderer?.captionTracks;
  return Array.isArray(tracks) ? tracks as YoutubeCaptionTrack[] : [];
}

function cloneTextResponse(response: Response, body: string): Response {
  return new Response(body, {
    status: response.status,
    statusText: response.statusText,
    headers: response.headers,
  });
}

async function fetchYoutubeTranscriptPlusRequest(params: YoutubeTranscriptFetchParams): Promise<Response> {
  const headers = buildYoutubeHeaders({
    headers: {
      ...(params.headers ?? {}),
      referer: 'https://www.youtube.com/',
      ...(params.lang ? { 'accept-language': params.lang } : {}),
      ...(params.userAgent ? { 'user-agent': params.userAgent } : {}),
    },
  });

  try {
    return await fetch(params.url, {
      method: params.method ?? 'GET',
      headers,
      body: params.body,
      signal: params.signal,
    });
  } catch (error: unknown) {
    if (params.signal?.aborted || isAbortError(error)) {
      throw createAbortError(params.signal?.reason ?? error);
    }

    throw error;
  }
}

async function fetchYoutubeTranscriptPlusWatchPage(
  params: YoutubeTranscriptFetchParams,
): Promise<Response> {
  const videoId = extractVideoId(params.url);
  let lastResponse: Response | null = null;
  let lastBody = '';

  for (const url of buildVideoBootstrapUrls(videoId)) {
    const response = await fetchYoutubeTranscriptPlusRequest({
      ...params,
      url,
      method: 'GET',
      body: undefined,
    });
    const body = await response.text();

    if (
      response.ok
      && (
        body.includes('"INNERTUBE_API_KEY"')
        || body.includes('INNERTUBE_API_KEY\\":\\"')
        || body.includes('g-recaptcha')
      )
    ) {
      return cloneTextResponse(response, body);
    }

    lastResponse = response;
    lastBody = body;
  }

  if (lastResponse) {
    return cloneTextResponse(lastResponse, lastBody);
  }

  return new Response('', { status: 502, statusText: 'Bad Gateway' });
}

function mapYoutubeTranscriptPlusError(error: unknown, videoId: string): AppError {
  if (error instanceof AppError) {
    return error;
  }

  if (error instanceof YoutubeTranscriptInvalidVideoIdError) {
    return new AppError('invalid_video_id', '这不是一个合法的 YouTube 视频链接。', 400, { cause: error });
  }

  if (error instanceof YoutubeTranscriptTooManyRequestError) {
    return new AppError('youtube_rate_limited', 'YouTube 暂时触发了风控，请稍后再试。', 429, { cause: error });
  }

  if (error instanceof YoutubeTranscriptVideoUnavailableError) {
    return new AppError('video_unavailable', '这个视频当前不可访问，无法提取字幕。', 422, { cause: error });
  }

  if (error instanceof YoutubeTranscriptDisabledError) {
    return new AppError('captions_disabled', '这个视频没有开放可抓取字幕。', 422, { cause: error });
  }

  if (error instanceof YoutubeTranscriptNotAvailableLanguageError) {
    return new AppError('captions_missing', '这个视频没有所需语言的字幕轨道。', 422, { cause: error });
  }

  if (error instanceof YoutubeTranscriptNotAvailableError) {
    return new AppError('captions_missing', '这个视频没有可用字幕轨道。', 422, { cause: error });
  }

  if (error instanceof Error) {
    return new AppError('youtube_fetch_failed', error.message || '抓取 YouTube 信息失败，请稍后重试。', 502, {
      cause: error,
    });
  }

  return new AppError('youtube_fetch_failed', '抓取 YouTube 信息失败，请稍后重试。', 502, {
    cause: error,
  });
}

async function fetchResponse(url: string, init?: RequestInit): Promise<Response> {
  throwIfAborted(init?.signal);
  let lastStatus = 0;
  let lastStatusText = '';

  for (let attempt = 1; attempt <= YOUTUBE_FETCH_MAX_ATTEMPTS; attempt += 1) {
    throwIfAborted(init?.signal);

    let response: Response;
    try {
      response = await fetch(url, {
        ...init,
        headers: buildYoutubeHeaders(init),
      });
    } catch (error: unknown) {
      if (init?.signal?.aborted || isAbortError(error)) {
        throw createAbortError(init?.signal?.reason ?? error);
      }

      console.warn('[youtube] fetch_exception', JSON.stringify({
        url,
        attempt,
        error: error instanceof Error ? error.message : String(error),
      }));

      if (attempt < YOUTUBE_FETCH_MAX_ATTEMPTS) {
        await sleep(YOUTUBE_FETCH_RETRY_BASE_MS * attempt, init?.signal ?? undefined);
        continue;
      }

      throw error;
    }

    if (response.ok) {
      return response;
    }

    lastStatus = response.status;
    lastStatusText = response.statusText;
    console.warn('[youtube] fetch_non_ok', JSON.stringify({
      url,
      attempt,
      status: response.status,
      statusText: response.statusText,
    }));
    await response.body?.cancel().catch(() => {});

    if (attempt < YOUTUBE_FETCH_MAX_ATTEMPTS && shouldRetryYoutubeStatus(response.status)) {
      await sleep(YOUTUBE_FETCH_RETRY_BASE_MS * attempt, init?.signal ?? undefined);
      continue;
    }

    break;
  }

  if (lastStatus === 429) {
    throw new AppError('youtube_rate_limited', 'YouTube 暂时触发了风控，请稍后再试。', 429);
  }

  throw new AppError(
    'youtube_fetch_failed',
    `抓取 YouTube 信息失败，请稍后重试。${lastStatus ? `（HTTP ${lastStatus}${lastStatusText ? ` ${lastStatusText}` : ''}）` : ''}`,
    502,
  );
}

async function fetchJson<T>(url: string, init?: RequestInit): Promise<T> {
  throwIfAborted(init?.signal);
  let lastStatus = 0;
  let lastStatusText = '';

  for (let attempt = 1; attempt <= YOUTUBE_FETCH_MAX_ATTEMPTS; attempt += 1) {
    throwIfAborted(init?.signal);

    let response: Response;
    try {
      const headers = buildYoutubeHeaders(init);
      if (!headers.has('content-type')) {
        headers.set('content-type', 'application/json');
      }

      response = await fetch(url, {
        ...init,
        headers,
      });
    } catch (error: unknown) {
      if (init?.signal?.aborted || isAbortError(error)) {
        throw createAbortError(init?.signal?.reason ?? error);
      }

      console.warn('[youtube] player_exception', JSON.stringify({
        url,
        attempt,
        error: error instanceof Error ? error.message : String(error),
      }));

      if (attempt < YOUTUBE_FETCH_MAX_ATTEMPTS) {
        await sleep(YOUTUBE_FETCH_RETRY_BASE_MS * attempt, init?.signal ?? undefined);
        continue;
      }

      throw error;
    }

    if (response.ok) {
      return (await response.json()) as T;
    }

    lastStatus = response.status;
    lastStatusText = response.statusText;
    console.warn('[youtube] player_non_ok', JSON.stringify({
      url,
      attempt,
      status: response.status,
      statusText: response.statusText,
    }));
    await response.body?.cancel().catch(() => {});

    if (attempt < YOUTUBE_FETCH_MAX_ATTEMPTS && shouldRetryYoutubeStatus(response.status)) {
      await sleep(YOUTUBE_FETCH_RETRY_BASE_MS * attempt, init?.signal ?? undefined);
      continue;
    }

    break;
  }

  if (lastStatus === 429) {
    throw new AppError('youtube_rate_limited', 'YouTube 暂时触发了风控，请稍后再试。', 429);
  }

  throw new AppError(
    'youtube_player_failed',
    `读取 YouTube 播放信息失败。${lastStatus ? `（HTTP ${lastStatus}${lastStatusText ? ` ${lastStatusText}` : ''}）` : ''}`,
    502,
  );
}

async function fetchOEmbedVideoDetails(
  videoId: string,
  signal?: AbortSignal,
): Promise<YoutubeVideoDetails | undefined> {
  const oEmbedUrl = `https://www.youtube.com/oembed?url=${encodeURIComponent(`https://www.youtube.com/watch?v=${videoId}`)}&format=json`;

  try {
    const payload = await fetchJson<Record<string, unknown>>(oEmbedUrl, { signal });
    const title = typeof payload.title === 'string' ? normalizeWhitespace(payload.title) : '';
    const author = typeof payload.author_name === 'string' ? normalizeWhitespace(payload.author_name) : '';
    const thumbnailUrl = typeof payload.thumbnail_url === 'string' ? normalizeWhitespace(payload.thumbnail_url) : '';

    if (!title && !author && !thumbnailUrl) {
      return undefined;
    }

    return {
      title: title || undefined,
      author: author || undefined,
      thumbnail: thumbnailUrl
        ? {
            thumbnails: [{ url: thumbnailUrl }],
          }
        : undefined,
    };
  } catch (error) {
    console.warn('[youtube] oembed_details_lookup_failed', JSON.stringify({
      videoId,
      error: error instanceof Error ? error.message : String(error),
    }));
    return undefined;
  }
}

async function resolveVideoDetails(
  videoId: string,
  details: YoutubeVideoDetails | undefined,
  watchHtml: string | undefined,
  signal?: AbortSignal,
): Promise<YoutubeVideoDetails | undefined> {
  let resolved = mergeVideoDetails(details, watchHtml ? extractWatchHtmlVideoDetails(watchHtml) : undefined);

  if (hasMeaningfulVideoTitle(resolved) && hasVideoAuthor(resolved) && hasVideoThumbnail(resolved)) {
    return resolved;
  }

  return mergeVideoDetails(resolved, await fetchOEmbedVideoDetails(videoId, signal));
}

function parseTranscriptXml(xml: string, languageCode: string): TranscriptSegment[] {
  const segments = [...xml.matchAll(XML_TEXT_PATTERN)].map((match) => ({
    text: match[3],
    duration: Number.parseFloat(match[2] ?? '0'),
    offset: Number.parseFloat(match[1] ?? '0'),
    lang: languageCode,
  }));

  if (!segments.length) {
    throw new AppError('empty_transcript', '字幕抓取成功，但没有解析到可读文本。', 422);
  }

  return segments;
}

function extractSegmentsFromBuffer(buffer: string, languageCode: string): { segments: TranscriptSegment[]; rest: string } {
  const segments: TranscriptSegment[] = [];
  let lastCompleteEnd = 0;

  XML_TEXT_PATTERN.lastIndex = 0;
  let match: RegExpExecArray | null;
  while ((match = XML_TEXT_PATTERN.exec(buffer))) {
    segments.push({
      text: match[3],
      duration: Number.parseFloat(match[2] ?? '0'),
      offset: Number.parseFloat(match[1] ?? '0'),
      lang: languageCode,
    });
    lastCompleteEnd = match.index + match[0].length;
  }

  return {
    segments,
    rest: lastCompleteEnd > 0 ? buffer.slice(lastCompleteEnd) : buffer,
  };
}

async function parseTranscriptResponse(
  response: Response,
  languageCode: string,
  callbacks?: TranscriptFetchCallbacks,
  previewMeta?: {
    videoId: string;
    sourceTitle: string;
    sourceAuthor: string;
    sourceLanguage: string;
    sourceLanguageCode: string;
    isAutoGenerated: boolean;
    thumbnailUrl: string;
  },
  signal?: AbortSignal,
): Promise<TranscriptSegment[]> {
  throwIfAborted(signal);

  if (!response.body) {
    return parseTranscriptXml(await response.text(), languageCode);
  }

  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  const segments: TranscriptSegment[] = [];
  let buffer = '';
  let previewSent = false;
  let earlyWindowSent = false;
  const EARLY_WINDOW_SECONDS = 8 * 60;

  while (true) {
    throwIfAborted(signal);

    const { value, done } = await reader.read().catch((error: unknown) => {
      if (signal?.aborted || isAbortError(error)) {
        throw createAbortError(signal?.reason ?? error);
      }

      throw error;
    });
    if (done) {
      break;
    }

    buffer += decoder.decode(value, { stream: true });
    const extracted = extractSegmentsFromBuffer(buffer, languageCode);
    buffer = extracted.rest;
    segments.push(...extracted.segments);

    if (!previewSent && previewMeta) {
      const previewChunks = buildTranscriptChunks(segments);
      if (previewChunks.length >= 3) {
        previewSent = true;
        await callbacks?.onPreviewReady?.({
          ...previewMeta,
          transcriptPreview: buildTranscriptPreview(previewChunks, 6),
        });
      }
    }

    if (!earlyWindowSent && previewMeta) {
      const currentChunks = buildTranscriptChunks(segments);
      const earlyChunks = currentChunks.filter((chunk) => chunk.start < EARLY_WINDOW_SECONDS);
      const lastEarlyChunk = earlyChunks.at(-1);
      if (earlyChunks.length >= 6 && (lastEarlyChunk?.end ?? 0) >= EARLY_WINDOW_SECONDS) {
        earlyWindowSent = true;
        await callbacks?.onEarlyWindowReady?.({
          ...previewMeta,
          chunks: earlyChunks,
          transcriptText: buildTranscriptTextFromChunks(earlyChunks),
          windowEndLabel: formatTime(lastEarlyChunk?.end ?? EARLY_WINDOW_SECONDS),
        });
      }
    }
  }

  buffer += decoder.decode();
  const trailing = extractSegmentsFromBuffer(buffer, languageCode);
  segments.push(...trailing.segments);

  if (!segments.length) {
    throw new AppError('empty_transcript', '字幕抓取成功，但没有解析到可读文本。', 422);
  }

  if (!previewSent && previewMeta) {
    const previewChunks = buildTranscriptChunks(segments);
    if (previewChunks.length) {
      await callbacks?.onPreviewReady?.({
        ...previewMeta,
        transcriptPreview: buildTranscriptPreview(previewChunks, 6),
      });
    }
  }

  if (!earlyWindowSent && previewMeta) {
    const currentChunks = buildTranscriptChunks(segments);
    if (currentChunks.length) {
      const lastChunk = currentChunks.at(-1);
      await callbacks?.onEarlyWindowReady?.({
        ...previewMeta,
        chunks: currentChunks,
        transcriptText: buildTranscriptTextFromChunks(currentChunks),
        windowEndLabel: formatTime(lastChunk?.end ?? 0),
      });
    }
  }

  return segments;
}

async function fetchSupadataResponse(url: string, apiKey: string, signal?: AbortSignal): Promise<Response> {
  throwIfAborted(signal);

  let response: Response;
  try {
    response = await fetch(url, {
      method: 'GET',
      headers: {
        accept: 'application/json',
        'x-api-key': apiKey,
      },
      signal,
    });
  } catch (error: unknown) {
    if (signal?.aborted || isAbortError(error)) {
      throw createAbortError(signal?.reason ?? error);
    }

    throw new AppError('supadata_request_failed', '第三方字幕服务请求失败，请稍后重试。', 502, {
      cause: error,
    });
  }

  return response;
}

async function readSupadataBody(response: Response): Promise<SupadataTranscriptResponse> {
  let payload: unknown = null;
  try {
    payload = await response.json();
  } catch {
    payload = null;
  }

  return payload && typeof payload === 'object' && !Array.isArray(payload)
    ? payload as SupadataTranscriptResponse
    : {};
}

function mapSupadataError(response: Response, payload: SupadataTranscriptResponse): AppError {
  const errorText = normalizeWhitespace(
    typeof payload.error === 'string'
      ? payload.error
      : typeof payload.result === 'string'
        ? payload.result
        : '',
  );

  if (response.status === 401 || response.status === 403) {
    return new AppError(
      'video_unavailable',
      '这个视频需要公开可访问后才能提取字幕，第三方字幕服务也无法访问。',
      422,
    );
  }

  if (response.status === 404) {
    return new AppError('video_unavailable', '这个视频不存在、是私密视频，或当前不可公开访问。', 422);
  }

  if (response.status === 206) {
    return new AppError('captions_missing', '第三方字幕服务未找到可用字幕。', 422);
  }

  if (response.status === 429) {
    return new AppError('supadata_rate_limited', '第三方字幕服务当前限流，请稍后再试。', 429);
  }

  return new AppError(
    'supadata_request_failed',
    errorText || `第三方字幕服务请求失败。${response.status ? `（HTTP ${response.status} ${response.statusText || ''}）` : ''}`.trim(),
    response.status >= 400 && response.status < 600 ? response.status : 502,
  );
}

function buildSupadataTranscriptRequestUrl(input: string, mode: SupadataTranscriptMode): string {
  const url = new URL(`${SUPADATA_API_BASE_URL}/transcript`);
  url.searchParams.set('url', input);
  url.searchParams.set('text', 'false');
  url.searchParams.set('mode', mode);
  return url.toString();
}

function buildSupadataTranscriptJobUrl(jobId: string): string {
  return `${SUPADATA_API_BASE_URL}/transcript/${encodeURIComponent(jobId)}`;
}

function extractSupadataResolvedPayload(payload: SupadataTranscriptResponse): SupadataTranscriptResponse {
  const result = payload.result;
  if (result && typeof result === 'object' && !Array.isArray(result)) {
    return result as SupadataTranscriptResponse;
  }

  return payload;
}

async function resolveSupadataTranscriptPayload(
  input: string,
  apiKey: string,
  mode: SupadataTranscriptMode,
  signal?: AbortSignal,
): Promise<SupadataTranscriptResponse> {
  const initialResponse = await fetchSupadataResponse(buildSupadataTranscriptRequestUrl(input, mode), apiKey, signal);
  const initialPayload = await readSupadataBody(initialResponse);

  if (initialResponse.status === 200) {
    return extractSupadataResolvedPayload(initialPayload);
  }

  if (initialResponse.status !== 202) {
    throw mapSupadataError(initialResponse, initialPayload);
  }

  const jobId = typeof initialPayload.jobId === 'string' ? initialPayload.jobId.trim() : '';
  if (!jobId) {
    throw new AppError('supadata_invalid_job', '第三方字幕服务返回了无法识别的任务结果。', 502);
  }

  for (let attempt = 1; attempt <= SUPADATA_MAX_POLL_ATTEMPTS; attempt += 1) {
    throwIfAborted(signal);
    await sleep(SUPADATA_POLL_INTERVAL_MS, signal);

    const jobResponse = await fetchSupadataResponse(buildSupadataTranscriptJobUrl(jobId), apiKey, signal);
    const jobPayload = await readSupadataBody(jobResponse);

    if (!jobResponse.ok) {
      throw mapSupadataError(jobResponse, jobPayload);
    }

    const status = normalizeWhitespace(typeof jobPayload.status === 'string' ? jobPayload.status : '').toLowerCase();
    if (status === 'completed') {
      return extractSupadataResolvedPayload(jobPayload);
    }

    if (status === 'failed') {
      throw new AppError(
        'supadata_job_failed',
        normalizeWhitespace(typeof jobPayload.error === 'string' ? jobPayload.error : '') || '第三方字幕服务处理失败，请稍后重试。',
        502,
      );
    }

    if (status !== 'queued' && status !== 'active') {
      throw new AppError('supadata_invalid_job', '第三方字幕服务返回了未知的任务状态。', 502);
    }
  }

  throw new AppError('supadata_timeout', '第三方字幕服务处理超时，请稍后重试。', 504);
}

function normalizeSupadataSegments(content: unknown, fallbackLanguageCode: string): TranscriptSegment[] {
  if (typeof content === 'string') {
    const text = normalizeWhitespace(content);
    return text
      ? [{ text, duration: 0, offset: 0, lang: fallbackLanguageCode }]
      : [];
  }

  if (!Array.isArray(content)) {
    return [];
  }

  return content.flatMap((item) => {
    if (!item || typeof item !== 'object' || Array.isArray(item)) {
      return [];
    }

    const segment = item as SupadataTranscriptSegment;
    const text = normalizeWhitespace(typeof segment.text === 'string' ? segment.text : '');
    if (!text) {
      return [];
    }

    const offsetMs = typeof segment.offset === 'number' ? segment.offset : Number(segment.offset ?? 0);
    const durationMs = typeof segment.duration === 'number' ? segment.duration : Number(segment.duration ?? 0);
    const languageCode = normalizeWhitespace(
      typeof segment.lang === 'string' ? segment.lang : fallbackLanguageCode,
    ) || fallbackLanguageCode;

    return [{
      text,
      duration: Number.isFinite(durationMs) ? Math.max(0, durationMs / 1000) : 0,
      offset: Number.isFinite(offsetMs) ? Math.max(0, offsetMs / 1000) : 0,
      lang: languageCode,
    }];
  });
}

async function emitPreparedTranscriptCallbacks(
  chunks: TranscriptChunk[],
  callbacks: TranscriptFetchCallbacks | undefined,
  previewMeta: {
    videoId: string;
    sourceTitle: string;
    sourceAuthor: string;
    sourceLanguage: string;
    sourceLanguageCode: string;
    isAutoGenerated: boolean;
    thumbnailUrl: string;
  },
): Promise<void> {
  if (!chunks.length) {
    return;
  }

  await callbacks?.onPreviewReady?.({
    ...previewMeta,
    transcriptPreview: buildTranscriptPreview(chunks, 6),
  });

  const EARLY_WINDOW_SECONDS = 8 * 60;
  const earlyChunks = chunks.filter((chunk) => chunk.start < EARLY_WINDOW_SECONDS);
  const fallbackChunks = earlyChunks.length ? earlyChunks : chunks;
  const lastChunk = fallbackChunks.at(-1);

  await callbacks?.onEarlyWindowReady?.({
    ...previewMeta,
    chunks: fallbackChunks,
    transcriptText: buildTranscriptTextFromChunks(fallbackChunks),
    windowEndLabel: formatTime(lastChunk?.end ?? 0),
  });
}

async function fetchTranscriptBundleWithYoutubeTranscriptPlus(
  input: string,
  callbacks?: TranscriptFetchCallbacks,
  signal?: AbortSignal,
): Promise<TranscriptBundle> {
  const videoId = extractVideoId(input);
  let capturedPlayerJson: Record<string, any> | null = null;
  let capturedTracks: YoutubeCaptionTrack[] = [];
  let capturedWatchHtml = '';

  const result = await fetchTranscriptPlus(input, {
    videoDetails: true,
    retries: 0,
    retryDelay: YOUTUBE_FETCH_RETRY_BASE_MS,
    signal,
    videoFetch: async (params) => {
      const response = await fetchYoutubeTranscriptPlusWatchPage(params);
      if (response.ok) {
        try {
          capturedWatchHtml = await response.clone().text();
        } catch {
        }
      }
      return response;
    },
    playerFetch: async (params) => {
      const response = await fetchYoutubeTranscriptPlusRequest(params);
      if (response.ok) {
        try {
          const parsed = await response.clone().json();
          if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) {
            capturedPlayerJson = parsed as Record<string, any>;
            capturedTracks = readCaptionTracksFromPlayerJson(capturedPlayerJson);
          }
        } catch {
        }
      }
      return response;
    },
    transcriptFetch: async (params) => fetchYoutubeTranscriptPlusRequest(params),
  }) as YoutubeTranscriptPlusResult;

  const segments = result.segments.map((segment) => ({
    text: segment.text,
    duration: segment.duration,
    offset: segment.offset,
    lang: segment.lang,
  }));
  const chunks = buildTranscriptChunks(segments);

  if (!chunks.length) {
    throw new AppError('empty_transcript_after_cleanup', '字幕内容过于稀薄，无法整理成 transcript。', 422);
  }

  const details: YoutubeVideoDetails = {
    title: result.videoDetails.title,
    author: result.videoDetails.author,
    channelId: result.videoDetails.channelId,
    lengthSeconds: String(result.videoDetails.lengthSeconds ?? 0),
    viewCount: String(result.videoDetails.viewCount ?? 0),
    thumbnail: {
      thumbnails: result.videoDetails.thumbnails?.map((thumbnail) => ({ url: thumbnail.url })) ?? [],
    },
  };
  const playerVideoDetails =
    ((capturedPlayerJson as Record<string, any> | null)?.videoDetails as YoutubeVideoDetails | undefined);
  const resolvedDetails = await resolveVideoDetails(videoId, playerVideoDetails || details, capturedWatchHtml, signal);
  const languageCode = normalizeWhitespace(segments[0]?.lang ?? '') || 'unknown';
  const selectedTrack = capturedTracks.find((track) => track.languageCode === languageCode) ?? capturedTracks[0];
  const language = selectedTrack
    ? formatTrackLanguage(selectedTrack)
    : { languageCode, languageName: formatLanguageName(languageCode) };
  const previewMeta = buildPreviewMeta(
    videoId,
    resolvedDetails,
    language.languageCode,
    language.languageName,
    selectedTrack ? isAutoTrack(selectedTrack) : false,
  );

  await emitPreparedTranscriptCallbacks(chunks, callbacks, previewMeta);

  return buildTranscriptBundleResult(
    videoId,
    resolvedDetails,
    language.languageCode,
    language.languageName,
    selectedTrack ? isAutoTrack(selectedTrack) : false,
    segments,
    chunks,
  );
}

async function fetchTranscriptBundleFromSupadata(
  input: string,
  videoId: string,
  callbacks: TranscriptFetchCallbacks | undefined,
  signal: AbortSignal | undefined,
  options: TranscriptProviderOptions,
  seedPlayerJson?: Record<string, any> | null,
  seedWatchHtml?: string,
): Promise<TranscriptBundle> {
  const apiKey = options.supadataApiKey?.trim();
  if (!apiKey) {
    throw new AppError('supadata_missing_key', '未配置第三方字幕服务 API key。', 500);
  }

  const mode = normalizeSupadataMode(options.supadataMode);
  const payload = await resolveSupadataTranscriptPayload(input, apiKey, mode, signal);
  const languageCode = normalizeWhitespace(typeof payload.lang === 'string' ? payload.lang : '') || 'unknown';
  const segments = normalizeSupadataSegments(payload.content, languageCode);

  if (!segments.length) {
    throw new AppError('empty_transcript_after_cleanup', '第三方字幕服务没有返回可用字幕内容。', 422);
  }

  const chunks = buildTranscriptChunks(segments);
  if (!chunks.length) {
    throw new AppError('empty_transcript_after_cleanup', '第三方字幕服务返回的字幕内容过于稀薄。', 422);
  }

  const details = seedPlayerJson?.videoDetails as YoutubeVideoDetails | undefined;
  const resolvedDetails = await resolveVideoDetails(videoId, details, seedWatchHtml, signal);
  const thumbnailUrl = resolveThumbnailUrl(videoId, resolvedDetails);
  const previewMeta = buildPreviewMeta(
    videoId,
    resolvedDetails,
    languageCode,
    formatLanguageName(languageCode),
    mode === 'generate',
    thumbnailUrl,
  );

  await emitPreparedTranscriptCallbacks(chunks, callbacks, previewMeta);

  return buildTranscriptBundleResult(
    videoId,
    resolvedDetails,
    languageCode,
    formatLanguageName(languageCode),
    mode === 'generate',
    segments,
    chunks,
    thumbnailUrl,
  );
}

function extractInnertubeApiKey(watchHtml: string): string {
  const match =
    watchHtml.match(/"INNERTUBE_API_KEY":"([^"]+)"/) ??
    watchHtml.match(/INNERTUBE_API_KEY\\":\\"([^\\"]+)\\"/);

  if (!match?.[1]) {
    throw new AppError('missing_innertube_key', '无法从 YouTube 页面中提取字幕接口。', 422);
  }

  return match[1];
}

function extractJsonObjectLiteral(source: string, marker: string): string | null {
  const markerIndex = source.indexOf(marker);
  if (markerIndex === -1) {
    return null;
  }

  const braceStart = source.indexOf('{', markerIndex + marker.length);
  if (braceStart === -1) {
    return null;
  }

  let depth = 0;
  let inString = false;
  let quoteChar = '"';
  let escaped = false;

  for (let index = braceStart; index < source.length; index += 1) {
    const char = source[index];

    if (inString) {
      if (escaped) {
        escaped = false;
        continue;
      }

      if (char === '\\') {
        escaped = true;
        continue;
      }

      if (char === quoteChar) {
        inString = false;
      }
      continue;
    }

    if (char === '"' || char === '\'') {
      inString = true;
      quoteChar = char;
      continue;
    }

    if (char === '{') {
      depth += 1;
      continue;
    }

    if (char === '}') {
      depth -= 1;
      if (depth === 0) {
        return source.slice(braceStart, index + 1);
      }
    }
  }

  return null;
}

function extractInitialPlayerResponse(watchHtml: string): Record<string, any> | null {
  const markers = [
    'var ytInitialPlayerResponse = ',
    'ytInitialPlayerResponse = ',
    'window["ytInitialPlayerResponse"] = ',
  ];

  for (const marker of markers) {
    const rawJson = extractJsonObjectLiteral(watchHtml, marker);
    if (!rawJson) {
      continue;
    }

    try {
      const parsed = JSON.parse(rawJson);
      if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) {
        return parsed as Record<string, any>;
      }
    } catch (error) {
      console.warn('[youtube] initial_player_response_parse_failed', JSON.stringify({
        marker,
        error: error instanceof Error ? error.message : String(error),
      }));
    }
  }

  return null;
}

function hasCaptionRenderer(playerJson: Record<string, any> | null | undefined): boolean {
  if (!playerJson || typeof playerJson !== 'object') {
    return false;
  }

  return Boolean(
    playerJson.captions?.playerCaptionsTracklistRenderer
    || playerJson.playerCaptionsTracklistRenderer,
  );
}

function buildVideoUnavailableMessage(playerJson: Record<string, any>): string {
  const playability = (playerJson.playabilityStatus ?? {}) as YoutubePlayabilityStatus;
  const reasons = [
    readTextValue(playability.reason),
    ...(Array.isArray(playability.messages) ? playability.messages.map((item) => readTextValue(item)) : []),
    readTextValue(playability.errorScreen?.playerErrorMessageRenderer?.reason),
    readTextValue(playability.errorScreen?.playerErrorMessageRenderer?.subreason),
  ].filter(Boolean);

  const reason = reasons[0] || '';
  const normalizedReason = reason.toLowerCase();
  const status = normalizeWhitespace(playability.status ?? '').toUpperCase();

  if (
    normalizedReason.includes('sign in')
    || normalizedReason.includes('confirm your age')
    || normalizedReason.includes('age-restricted')
    || normalizedReason.includes('age restricted')
    || status === 'LOGIN_REQUIRED'
  ) {
    return '这个视频需要登录或年龄验证后才能观看，当前无法提取字幕。';
  }

  if (normalizedReason.includes('private')) {
    return '这是一个私密视频，当前无法提取字幕。';
  }

  if (normalizedReason.includes('members-only') || normalizedReason.includes('members only')) {
    return '这是会员专享视频，当前无法提取字幕。';
  }

  if (normalizedReason.includes('not available in your country') || normalizedReason.includes('not available in your region')) {
    return '这个视频在当前地区不可用，无法提取字幕。';
  }

  if (normalizedReason.includes('live stream') && (normalizedReason.includes('offline') || normalizedReason.includes('recording'))) {
    return '这个直播当前未开播或回放不可用，暂时无法提取字幕。';
  }

  if (reason) {
    return `这个视频当前不可访问，无法提取字幕。YouTube 提示：${reason}`;
  }

  return '这个视频当前不可访问，无法提取字幕。';
}

async function fetchWatchHtmlWithFallback(videoId: string, signal?: AbortSignal): Promise<string> {
  let lastError: unknown = new AppError('youtube_fetch_failed', '抓取 YouTube 信息失败，请稍后重试。', 502);

  for (const url of buildVideoBootstrapUrls(videoId)) {
    try {
      const watchHtml = await fetchText(url, {
        signal,
        headers: {
          referer: 'https://www.youtube.com/',
        },
      });

      if (watchHtml.includes('g-recaptcha')) {
        throw new AppError('youtube_rate_limited', 'YouTube 暂时触发了风控，请稍后再试。', 429);
      }

      extractInnertubeApiKey(watchHtml);
      return watchHtml;
    } catch (error) {
      lastError = error;
      const appError = AppError.from(error);
      console.warn('[youtube] bootstrap_fallback_failed', JSON.stringify({
        url,
        code: appError.code,
        message: appError.publicMessage,
      }));
    }
  }

  throw AppError.from(lastError);
}

function extractPlayerCaptionTracks(playerJson: Record<string, any>): YoutubeCaptionTrack[] {
  const renderer =
    playerJson.captions?.playerCaptionsTracklistRenderer ?? playerJson.playerCaptionsTracklistRenderer;

  if (!renderer) {
    const status = playerJson.playabilityStatus?.status;
    if (status && status !== 'OK') {
      throw new AppError('video_unavailable', buildVideoUnavailableMessage(playerJson), 422);
    }

    throw new AppError('captions_disabled', '这个视频没有开放可抓取字幕。', 422);
  }

  const tracks = renderer.captionTracks;
  if (!Array.isArray(tracks) || tracks.length === 0) {
    throw new AppError('captions_missing', '这个视频没有可用字幕轨道。', 422);
  }

  return tracks as YoutubeCaptionTrack[];
}

function formatSourceTitle(_videoId: string, details?: YoutubeVideoDetails): string {
  const title = details?.title?.trim();
  if (title && !isGenericYoutubeTitle(title)) {
    return title;
  }

  throw new AppError('missing_video_title', '无法读取 YouTube 原始标题，请稍后重试。', 502);
}

function formatSourceAuthor(details?: YoutubeVideoDetails): string {
  return details?.author?.trim() || 'Unknown Channel';
}

export function buildTranscriptTextFromChunks(chunks: TranscriptChunk[]): string {
  return chunks.map((chunk) => chunk.text).join('\n');
}

export function formatTime(seconds: number): string {
  const rounded = Math.max(0, Math.floor(seconds));
  const hour = Math.floor(rounded / 3600);
  const minute = Math.floor((rounded % 3600) / 60);
  const second = rounded % 60;

  if (hour > 0) {
    return `${String(hour).padStart(2, '0')}:${String(minute).padStart(2, '0')}:${String(second).padStart(2, '0')}`;
  }

  return `${String(minute).padStart(2, '0')}:${String(second).padStart(2, '0')}`;
}

export function buildTranscriptPreview(
  chunks: TranscriptChunk[],
  maxItems = 10,
  maxTextLength = 220,
): TranscriptPreviewItem[] {
  return chunks.slice(0, maxItems).map((chunk) => {
    const text = chunk.text.length > maxTextLength ? `${chunk.text.slice(0, maxTextLength).trim()}...` : chunk.text;
    return {
      startLabel: formatTime(chunk.start),
      endLabel: formatTime(chunk.end),
      text,
    };
  });
}

export async function fetchTranscriptBundle(
  input: string,
  callbacks?: TranscriptFetchCallbacks,
  signal?: AbortSignal,
  options?: TranscriptProviderOptions,
): Promise<TranscriptBundle> {
  throwIfAborted(signal);

  const videoId = extractVideoId(input);
  try {
    const bundle = await fetchTranscriptBundleWithYoutubeTranscriptPlus(input, callbacks, signal);
    console.log('[youtube] transcript_plus_success', JSON.stringify({ videoId }));
    return bundle;
  } catch (error) {
    if (signal?.aborted || isAbortError(error)) {
      throw createAbortError(signal?.reason ?? error);
    }

    const transcriptPlusError = mapYoutubeTranscriptPlusError(error, videoId);
    console.warn('[youtube] transcript_plus_failed', JSON.stringify({
      videoId,
      code: transcriptPlusError.code,
      message: transcriptPlusError.publicMessage,
    }));
  }

  let initialPlayerJson: Record<string, any> | null = null;
  let initialWatchHtml = '';

  try {
    const watchHtml = await fetchWatchHtmlWithFallback(videoId, signal);
    initialWatchHtml = watchHtml;
    initialPlayerJson = extractInitialPlayerResponse(watchHtml);
    let playerJson = initialPlayerJson;

    if (!hasCaptionRenderer(playerJson)) {
      const apiKey = extractInnertubeApiKey(watchHtml);
      playerJson = await fetchJson<Record<string, any>>(
        `https://www.youtube.com/youtubei/v1/player?key=${apiKey}`,
        {
          method: 'POST',
          body: JSON.stringify({
            context: {
              client: {
                clientName: 'ANDROID',
                clientVersion: '20.10.38',
              },
            },
            videoId,
          }),
          signal,
        },
      );
    } else {
      console.log('[youtube] using_initial_player_response', JSON.stringify({ videoId }));
    }

    if (!playerJson) {
      throw new AppError('youtube_player_failed', '读取 YouTube 播放信息失败。', 502);
    }

    const tracks = extractPlayerCaptionTracks(playerJson);
    const selectedTrack = chooseCaptionTrack(tracks);
    const { languageCode, languageName } = formatTrackLanguage(selectedTrack);
    const transcriptUrl = (selectedTrack.baseUrl ?? '').replace(/&fmt=[^&]+/, '');

    if (!transcriptUrl) {
      throw new AppError('missing_transcript_url', '找到了字幕轨道，但无法读取字幕内容。', 422);
    }

    const details = playerJson.videoDetails as YoutubeVideoDetails | undefined;
    const resolvedDetails = await resolveVideoDetails(videoId, details, watchHtml, signal);
    const previewMeta = buildPreviewMeta(
      videoId,
      resolvedDetails,
      languageCode,
      languageName,
      isAutoTrack(selectedTrack),
    );
    const transcriptResponse = await fetchResponse(transcriptUrl, { signal });
    const segments = await parseTranscriptResponse(transcriptResponse, languageCode, callbacks, previewMeta, signal);
    const chunks = buildTranscriptChunks(segments);

    if (!chunks.length) {
      throw new AppError('empty_transcript_after_cleanup', '字幕内容过于稀薄，无法整理成 transcript。', 422);
    }

    return buildTranscriptBundleResult(
      videoId,
      resolvedDetails,
      languageCode,
      languageName,
      isAutoTrack(selectedTrack),
      segments,
      chunks,
    );
  } catch (error) {
    if (signal?.aborted || isAbortError(error)) {
      throw createAbortError(signal?.reason ?? error);
    }

    const directError = AppError.from(error);
    if (!shouldAttemptSupadataFallback(directError, options)) {
      throw directError;
    }

    try {
      const bundle = await fetchTranscriptBundleFromSupadata(
        input,
        videoId,
        callbacks,
        signal,
        options ?? {},
        initialPlayerJson,
        initialWatchHtml,
      );

      console.log('[youtube] supadata_fallback_success', JSON.stringify({
        videoId,
        directCode: directError.code,
        mode: normalizeSupadataMode(options?.supadataMode),
      }));

      return bundle;
    } catch (fallbackError) {
      if (signal?.aborted || isAbortError(fallbackError)) {
        throw createAbortError(signal?.reason ?? fallbackError);
      }

      const fallbackAppError = AppError.from(fallbackError);
      console.warn('[youtube] supadata_fallback_failed', JSON.stringify({
        videoId,
        directCode: directError.code,
        fallbackCode: fallbackAppError.code,
        fallbackMessage: fallbackAppError.publicMessage,
      }));
      throw preferSupadataError(directError, fallbackAppError) ? fallbackAppError : directError;
    }
  }
}
