import type { TranscriptDialogueSliceResult, TranscriptSection } from '../services/gemini';
import {
  buildStoredFullRendering,
  buildStoredQuickRendering,
  buildStoredTranslationContent,
  type StoredTranslationContent,
} from '../services/render-content';
import type { TranscriptBundle } from '../services/youtube';

const CURATED_MODEL = 'manual_curated_translation';
const JENSEN_UPDATED_AT = 1775362792700;
const JENSEN_VIDEO_ID = 'Pkj-BLHs6dE';

function joinText(parts: string[]): string {
  return parts.join('');
}

function createDialogueSlice(input: {
  startLabel: string;
  endLabel: string;
  titleZh: string;
  summaryZh: string;
  topicTitleZh: string;
  questionSpeaker: string;
  question: string;
  answerSpeaker: string;
  answer: string;
}): TranscriptDialogueSliceResult {
  return {
    section: {
      startLabel: input.startLabel,
      endLabel: input.endLabel,
      subtitle: input.titleZh,
      summary: input.summaryZh,
      transcript: '',
      topicTitleZh: input.titleZh,
      topicSummaryZh: input.summaryZh,
      subtitleZh: input.titleZh,
      summaryZh: input.summaryZh,
    },
    turns: [
      {
        timestamp: input.startLabel,
        speaker: input.questionSpeaker,
        textZh: input.question,
      },
      {
        timestamp: input.endLabel,
        speaker: input.answerSpeaker,
        textZh: input.answer,
      },
    ],
    groups: [
      {
        topicTitleZh: input.topicTitleZh,
        question: {
          timestamp: input.startLabel,
          speaker: input.questionSpeaker,
          textZh: input.question,
        },
        answers: [
          {
            timestamp: input.endLabel,
            speaker: input.answerSpeaker,
            textZh: input.answer,
          },
        ],
        turns: [
          {
            timestamp: input.startLabel,
            speaker: input.questionSpeaker,
            textZh: input.question,
          },
          {
            timestamp: input.endLabel,
            speaker: input.answerSpeaker,
            textZh: input.answer,
          },
        ],
      },
    ],
    model: CURATED_MODEL,
  };
}

const sourceBundle: TranscriptBundle = {
  videoId: JENSEN_VIDEO_ID,
  sourceTitle: 'Jensen Huang of Nvidia on the Future of A.I. | DealBook Summit 2023',
  sourceAuthor: 'New York Times Events',
  channelId: '',
  languageCode: 'en',
  languageName: 'English (auto-generated)',
  isAutoGenerated: true,
  durationSeconds: 1689,
  viewCount: 0,
  thumbnailUrl: 'https://i.ytimg.com/vi_webp/Pkj-BLHs6dE/sddefault.webp',
  segments: [],
  chunks: [],
  transcriptText: '',
};

const fullDialogueSlices: TranscriptDialogueSliceResult[] = [
  createDialogueSlice({
    startLabel: '01:28',
    endLabel: '02:52',
    titleZh: '首台AI超算与OpenAI的早期合作',
    summaryZh: 'DGX从内部项目变成OpenAI的首台AI超算',
    topicTitleZh: '首台AI超算',
    questionSpeaker: 'Andrew',
    question: '英伟达最早是如何把DGX这类AI超级计算机交付给OpenAI的？',
    answerSpeaker: 'Jensen',
    answer: joinText([
      '黄仁勋说，DGX原本是英伟达从2012年开始为内部工程师打造的机器，前后研发了五年。',
      '它后来在一次会议上被埃隆·马斯克看到，马斯克表示自己想要一台，并把他介绍给了OpenAI。',
      '这台机器重约70磅、由3.5万个零件构成，售价25万美元，甚至需要另一台超级计算机来测试。',
      '最终，英伟达把这台“世界第一台AI超级计算机”交付给了OpenAI，也由此开启了更早期的合作。',
    ]),
  }),
  createDialogueSlice({
    startLabel: '03:31',
    endLabel: '03:47',
    titleZh: 'AlexNet如何改变AI与软件的写法',
    summaryZh: '从手写逻辑转向用样本训练神经网络',
    topicTitleZh: '深度学习突破',
    questionSpeaker: 'Andrew',
    question: '2012年AlexNet真正打动你的地方是什么？',
    answerSpeaker: 'Jensen',
    answer: joinText([
      '他认为AlexNet最非凡的地方在于，它让人们不再通过手写逻辑来定义软件，而是通过展示期望结果来训练模型。',
      'Alex、Ilya Sutskever和Geoffrey Hinton在计算机视觉上的结果，第一次明显超过了传统专家系统所能达到的水平。',
      '英伟达当时意识到，这不只是一次学术突破，而是对未来计算方式和软件开发范式的根本改变。',
    ]),
  }),
  createDialogueSlice({
    startLabel: '05:04',
    endLabel: '06:38',
    titleZh: '当前AI能力边界与推理突破方向',
    summaryZh: '模型擅长感知，真正的多步推理仍在攻关',
    topicTitleZh: 'AI发展前景',
    questionSpeaker: 'Andrew',
    question: '今天的AI距离真正的人类式智能和推理能力还有多远？',
    answerSpeaker: 'Jensen',
    answer: joinText([
      '黄仁勋认为，12年前没有人真正预见到今天的进展速度，因此也不应夸大我们对未来节奏的把握。',
      '他强调，当前模型已经很擅长感知和即时反应，比如识别图像、补全文本，但这和真正的人类式智能仍有差距。',
      '现在全球研究者都在尝试让AI把目标拆成多个步骤、构建决策树、遍历路径并迭代求解，这才更接近人类推理的方式。',
    ]),
  }),
  createDialogueSlice({
    startLabel: '07:08',
    endLabel: '08:04',
    titleZh: 'AGI时间判断与AI对芯片设计的反哺',
    summaryZh: '五年内或见人类水平测试表现，芯片设计已离不开AI',
    topicTitleZh: '十年愿景',
    questionSpeaker: 'Andrew',
    question: '你如何判断AGI的时间线，以及AI是否会反过来设计芯片？',
    answerSpeaker: 'Jensen',
    answer: joinText([
      '他的答案是，AGI是否实现取决于定义方式。',
      '如果把AGI理解为一种能够通过一系列测试、并展现出与普通人类相当智能水平的软件，那么未来五年内就可能看到这样的系统。',
      '与此同时，黄仁勋直言，英伟达今天交付的H100若没有AI辅助根本做不出来，AI已经深度参与算法优化、晶体管集成、软件编写和芯片设计。',
    ]),
  }),
  createDialogueSlice({
    startLabel: '08:34',
    endLabel: '09:36',
    titleZh: 'OpenAI事件背后的治理启示',
    summaryZh: '公司治理不是附属品，而是企业能否穿越周期的骨架',
    topicTitleZh: '公司治理',
    questionSpeaker: 'Andrew',
    question: 'OpenAI的风波，让你更在意公司治理这件事吗？',
    answerSpeaker: 'Jensen',
    answer: joinText([
      '黄仁勋先表示，自己很高兴看到OpenAI的问题得到解决，因为那是一支优秀且重要的团队。',
      '他随后把重点放在治理上，认为一家创业公司如果想穿越长期逆境，就必须像设计产品一样设计组织与治理架构。',
      '他提到英伟达30年来历经多次险境，如果不是29岁时建立起的治理结构，公司很可能活不到今天。',
    ]),
  }),
  createDialogueSlice({
    startLabel: '10:08',
    endLabel: '10:08',
    titleZh: '为什么AI需要像自动驾驶一样被监管',
    summaryZh: '监管重点应是设计、测试、压力测试和持续监控',
    topicTitleZh: 'AI监管',
    questionSpeaker: 'Andrew',
    question: '人工智能究竟应不应该被监管，核心原则是什么？',
    answerSpeaker: 'Jensen',
    answer: joinText([
      '黄仁勋的看法非常明确：AI应该被监管。',
      '在他看来，AI本质上是一种自主信息系统，和自动驾驶汽车、工厂机器人、具备自动驾驶与自动着陆能力的飞机属于同一类问题。',
      '因此治理重点不该只是口号，而应落实到正确设计、充分测试、压力测试、运行监控、内外部安全机制，以及冗余和多样性这些工程原则上。',
    ]),
  }),
  createDialogueSlice({
    startLabel: '11:14',
    endLabel: '12:04',
    titleZh: '通用模型与行业专用模型会长期并存',
    summaryZh: '基础模型普及，专业领域价值来自私有数据与工艺诀窍',
    topicTitleZh: 'AI未来格局',
    questionSpeaker: 'Andrew',
    question: '未来AI会不会全部趋同并商品化，还是会分化出不同层次？',
    answerSpeaker: 'Jensen',
    answer: joinText([
      '黄仁勋不愿给朋友们排名，但他明确认为这个行业不会简单收敛成完全同质化的商品。',
      '未来当然会出现能力很强的通用现成AI，能解决大量普适问题。',
      '但医疗、药物研发、芯片设计等专业领域仍会建立在基础模型之上，通过监督微调和私有数据训练出更擅长特定任务的智能系统。',
      '在他看来，真正的壁垒恰恰来自那些不在互联网上的内部数据、经验和工艺诀窍。',
    ]),
  }),
  createDialogueSlice({
    startLabel: '12:51',
    endLabel: '13:25',
    titleZh: '芯片供应链完全独立为何还很遥远',
    summaryZh: '值得追求，但十到二十年内都不现实',
    topicTitleZh: '芯片独立',
    questionSpeaker: 'Andrew',
    question: '美国本土制造和供应链独立，现实上到底走到了哪一步？',
    answerSpeaker: 'Jensen',
    answer: joinText([
      '黄仁勋强调，英伟达的系统包含3.5万个零件，其中只有8个来自台积电，但整条供应链仍然分布在世界各地。',
      '这意味着“完全独立”不是简单多建几座厂就能实现的目标，而是一项跨越十到二十年的系统工程。',
      '他认为这件事当然值得努力，但在未来十年甚至二十年内，想实现供应链彻底独立并不现实。',
    ]),
  }),
  createDialogueSlice({
    startLabel: '14:00',
    endLabel: '14:29',
    titleZh: '出口管制下的商业与国家安全平衡',
    summaryZh: '最先进技术不会卖给中国，但合规产品仍会继续研发',
    topicTitleZh: '出口管制',
    questionSpeaker: 'Andrew',
    question: '面对对华芯片出口限制，企业该如何平衡商业利益和国家安全？',
    answerSpeaker: 'Jensen',
    answer: joinText([
      '黄仁勋说，作为公司，他们当然希望尽可能和所有人做生意。',
      '但另一方面，国家安全和国家竞争力同样重要，法规的目标正是要在两者之间找到平衡。',
      '他的表态也很直接：英伟达最尖端的技术不会提供给中国，但公司会针对新法规研发合规芯片，只要满足要求，就会重新进入市场继续服务客户。',
    ]),
  }),
  createDialogueSlice({
    startLabel: '15:35',
    endLabel: '17:21',
    titleZh: '限制、替代与中国半导体追赶速度',
    summaryZh: '限制可能催生本土替代，中国与领先水平仍有代差',
    topicTitleZh: '技术竞争',
    questionSpeaker: 'Andrew',
    question: '技术限制会不会反而催生更强的竞争对手，中国现在又大概落后多少？',
    answerSpeaker: 'Jensen',
    answer: joinText([
      '黄仁勋认为，这类复杂系统中的政策干预总会带来意料之外的后果。',
      '如果中国拿不到英伟达技术，就可能通过其他路径获得，或者反过来加速本土产业投入；他提到中国已有大约50家公司在做相关方向。',
      '对于华为7纳米芯片，他说业内并不意外，因为旧技术本身就可以通过工程优化被不断压榨潜力。',
      '但他仍判断，与全球领先水平相比，中国半导体大约还有十年左右差距，不过全球工程师都足够聪明，追赶不会停止。',
    ]),
  }),
  createDialogueSlice({
    startLabel: '17:55',
    endLabel: '20:47',
    titleZh: '危机感、专注力与黄仁勋的领导方式',
    summaryZh: '真正经历过濒临倒闭的人，会把危机感带一辈子',
    topicTitleZh: '危机管理',
    questionSpeaker: 'Andrew',
    question: '经历过长期危机之后，你为什么依然保持如此强烈的紧迫感？',
    answerSpeaker: 'Jensen',
    answer: joinText([
      '一方面，他并不担心ASML的垄断，因为他认为这家公司产品卓越、激励一致，而且愿意向全球供货。',
      '另一方面，他坦言，真正从白手起家一路经历多次濒临倒闭后，那种担忧和警觉会伴随终生。',
      '他说自己每天早上醒来并不是先感到骄傲，而是先感到担心；在逆境里，他反而更专注、表现更好，甚至会半开玩笑地告诉妻子自己今天又“拯救了公司”。',
    ]),
  }),
];

const quickSections: TranscriptSection[] = fullDialogueSlices.map((slice) => slice.section);

export const jensenCuratedHotItem = {
  videoId: JENSEN_VIDEO_ID,
  title: '英伟达CEO黄仁勋谈人工智能的未来 | 2023年DealBook峰会',
  author: sourceBundle.sourceAuthor,
  thumbnailUrl: sourceBundle.thumbnailUrl,
  youtubeUrl: `https://www.youtube.com/watch?v=${JENSEN_VIDEO_ID}`,
  viewCount: 0,
  updatedAt: JENSEN_UPDATED_AT,
};

export const jensenCuratedTranslationContent: StoredTranslationContent = buildStoredTranslationContent(
  sourceBundle,
  {
    quick: buildStoredQuickRendering(sourceBundle, quickSections, {
      translatedTitleZh: '英伟达CEO黄仁勋谈人工智能的未来 | 2023年DealBook峰会',
      summaryZh: '如果你在1993年就知道创业过程会面临如此多的艰难险阻，你可能根本就不会开始。',
      summary: 'Jensen Huang reflects on DGX, AlexNet, AI limits, governance, regulation, export controls, and the mindset required to build Nvidia through repeated crises.',
      speakers: ['Andrew', 'Jensen'],
      model: CURATED_MODEL,
      geminiTranslationComplete: true,
      translationNeedsRefresh: false,
    }),
    full: buildStoredFullRendering(sourceBundle, fullDialogueSlices, {
      translatedTitleZh: '英伟达CEO黄仁勋谈人工智能的未来 | 2023年DealBook峰会',
      summaryZh: '如果你在1993年就知道创业过程会面临如此多的艰难险阻，你可能根本就不会开始。',
      summary: 'Jensen Huang reflects on DGX, AlexNet, AI limits, governance, regulation, export controls, and the mindset required to build Nvidia through repeated crises.',
      speakers: ['Andrew', 'Jensen'],
      model: CURATED_MODEL,
      geminiTranslationComplete: true,
      translationNeedsRefresh: false,
    }),
  },
  JENSEN_UPDATED_AT,
);

export const jensenCuratedGeneratedArticle = {
  articleHtml: String.raw`<header class="article-hero" data-article-hero=""><h1 data-article-title="">英伟达CEO黄仁勋谈人工智能的未来 | 2023年DealBook峰会</h1><blockquote class="article-pullquote"><p class="transcript-kicker"><span data-article-kicker="">如果你在1993年就知道创业过程会面临如此多的艰难险阻，你可能根本就不会开始。</span></p></blockquote><figure class="article-media"><img class="article-media-image" data-article-thumb="" src="https://i.ytimg.com/vi_webp/Pkj-BLHs6dE/sddefault.webp" alt="Jensen Huang of Nvidia on the Future of A.I. | DealBook Summit 2023 缩略图" loading="eager" referrerpolicy="no-referrer"></figure></header><div class="dialogue-section-block" data-dialogue-section-id="dialogue-section-1"><section class="section-theme-block"><h2 class="section-theme-title"><span class="section-theme-title-text">首台超算</span><span class="section-theme-divider">: </span><span class="section-theme-summary">黄仁勋交付了全球首台AI超级计算机。</span></h2></section><section class="dialogue-subtopic-block"><h3 class="dialogue-subtopic-title">首台AI超算的交付</h3><section class="qa"><div class="qa-meta"><div class="qa-speaker">Andrew</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=88s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">01:28</a></div></div><div class="qa-body"><p>您曾向OpenAI的创始人之一埃隆·马斯克交付了首批芯片，当时究竟发生了什么？</p></div></section><section class="qa"><div class="qa-meta"><div class="qa-speaker">Jensen</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=126s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">02:06</a></div></div><div class="qa-body"><p>我当时交付给他的是世界上第一台AI超级计算机，我们称之为DGX。这台机器耗时五年研发，如今已遍布全球。人们常以为我们只制造GPU，但DGX重达70磅，由3.5万个零件组成，其中仅有8个芯片来自台积电。它极其精密，需要机器人组装，功耗高达1万安培，售价25万美元。由于它是首创的超级计算机，我们甚至需要另一台超级计算机来测试它。</p></div></section></section><section class="dialogue-subtopic-block"><h3 class="dialogue-subtopic-title">研发历程与早期客户</h3><section class="qa"><div class="qa-meta"><div class="qa-speaker">Andrew</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=172s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">02:52</a></div></div><div class="qa-body"><p>这台超级计算机的研发背景是怎样的，又是如何与OpenAI产生联系的？</p></div></section><section class="qa"><div class="qa-meta"><div class="qa-speaker">Jensen</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=172s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">02:52</a></div></div><div class="qa-body"><p>我们从2012年开始研发，历时五年，最初是为我们自己的工程师打造的。在一次会议上我介绍了它，埃隆看到后表示想要一台，并向我介绍了OpenAI。当时我还认识OpenAI的早期成员、伯克利教授彼得·比尔，以及我在AlexNet时期就结识的伊利亚·苏茨克维。最终，我将这台世界首创的AI超级计算机交付给了OpenAI。</p></div></section></section></div><div class="dialogue-section-block" data-dialogue-section-id="dialogue-section-2"><section class="section-theme-block"><h2 class="section-theme-title"><span class="section-theme-title-text">深度学习</span><span class="section-theme-divider">: </span><span class="section-theme-summary">AlexNet开启深度学习时代。</span></h2></section><section class="dialogue-subtopic-block"><h3 class="dialogue-subtopic-title">AlexNet的突破性</h3><section class="qa"><div class="qa-meta"><div class="qa-speaker">Andrew</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=211s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">03:31</a></div></div><div class="qa-body"><p>在2012年AlexNet发布之前的五年里，你究竟看到了什么，才让你意识到它的潜力？</p></div></section><section class="qa"><div class="qa-meta"><div class="qa-speaker">Jensen</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=227s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">03:47</a></div></div><div class="qa-body"><p>AlexNet做了一件非凡的事情。它是一个神经网络，其编程方式与以往完全不同：你不再是编写代码来定义逻辑，而是通过展示你想要的结果来训练它。在它出现之前，工程师必须手动编写软件并进行测试，但AlexNet通过学习示例来掌握预期的输出。当Alex、Ilya Sutskever和Geoffrey Hinton展示出其在计算机视觉识别方面取得的惊人成果时，那是此前任何专家都无法企及的。我们当时意识到这不仅是一个显著的成就，更重要的是，我们退后一步思考了它对计算机未来的深远影响，并得出了正确的结论。</p></div></section></section></div><div class="dialogue-section-block" data-dialogue-section-id="dialogue-section-3"><section class="section-theme-block"><h2 class="section-theme-title"><span class="section-theme-title-text">AI发展前景</span><span class="section-theme-divider">: </span><span class="section-theme-summary">AI目前擅长感知但尚不具备推理能力。</span></h2></section><section class="dialogue-subtopic-block"><h3 class="dialogue-subtopic-title">AI革命的风险认知</h3><section class="qa"><div class="qa-meta"><div class="qa-speaker">Andrew</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=304s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">05:04</a></div></div><div class="qa-body"><p>当意识到这项技术将彻底改变计算方式、软件编写及应用开发时，你是否曾感到过恐惧或担忧其潜在的危险性？</p></div></section><section class="qa"><div class="qa-meta"><div class="qa-speaker">Jensen</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=343s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">05:43</a></div></div><div class="qa-body"><p>12年前没人能预见到今天的结果，如果当时有人那样说，那绝对是夸大了我们对技术进步速度的理解。虽然目前的进步速度确实很快，但我们必须意识到，目前的模型能力与真正的智能之间仍有区别。我们现在非常擅长感知和即时反应，比如识别出一只狗或补全句子，但我们还无法进行人类擅长的多步推理。</p></div></section></section><section class="dialogue-subtopic-block"><h3 class="dialogue-subtopic-title">AI推理能力的突破</h3><section class="qa"><div class="qa-meta"><div class="qa-speaker">Andrew</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=398s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">06:38</a></div></div><div class="qa-body"><p>你认为我们距离实现AI的多步推理能力还有多远？</p></div></section><section class="qa"><div class="qa-meta"><div class="qa-speaker">Jensen</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=398s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">06:38</a></div></div><div class="qa-body"><p>目前全球的研究人员都在致力于解决这个问题。我们正在探索如何将一个目标拆解为多个步骤，构建决策树，并通过遍历决策树来找到最优路径，这正是人类进行推理和迭代思考的方式。</p></div></section></section></div><div class="dialogue-section-block" data-dialogue-section-id="dialogue-section-4"><section class="section-theme-block"><h2 class="section-theme-title"><span class="section-theme-title-text">十年愿景</span><span class="section-theme-divider">: </span><span class="section-theme-summary">五年内AI将达人类水平。</span></h2></section><section class="dialogue-subtopic-block"><h3 class="dialogue-subtopic-title">十年内实现AGI吗？</h3><section class="qa"><div class="qa-meta"><div class="qa-speaker">Andrew</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=428s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">07:08</a></div></div><div class="qa-body"><p>考虑到您现在必须进行的投资和技术布局，您认为十年后我们能实现通用人工智能（AGI）吗？</p></div></section><section class="qa"><div class="qa-meta"><div class="qa-speaker">Jensen</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=443s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">07:23</a></div></div><div class="qa-body"><p>这取决于你如何定义AGI。如果我们将AGI定义为一种能够通过一系列测试并展现出与普通人类相当的智能水平的软件，那么我认为在未来五年内，你就会看到能够完成这些测试并达到人类水平的AI。</p></div></section></section><section class="dialogue-subtopic-block"><h3 class="dialogue-subtopic-title">AI在芯片设计中的作用</h3><section class="qa"><div class="qa-meta"><div class="qa-speaker">Andrew</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=484s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">08:04</a></div></div><div class="qa-body"><p>未来的AI是否能够设计出您现在正在制造的这种芯片，甚至取代现在的设计团队？</p></div></section><section class="qa"><div class="qa-meta"><div class="qa-speaker">Jensen</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=484s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">08:04</a></div></div><div class="qa-body"><p>事实上，我们今天交付的H100芯片如果没有AI的辅助是不可能完成的。我们利用了大量的AI来优化算法并实现晶体管的高密度集成。可以说，现在的软件编写和芯片设计都离不开AI，没有AI，这一切都无法实现。</p></div></section></section></div><div class="dialogue-section-block" data-dialogue-section-id="dialogue-section-5"><section class="section-theme-block"><h2 class="section-theme-title"><span class="section-theme-title-text">公司治理</span><span class="section-theme-divider">: </span><span class="section-theme-summary">治理架构决定企业成败。</span></h2></section><section class="dialogue-subtopic-block"><h3 class="dialogue-subtopic-title">对OpenAI事件的看法</h3><section class="qa"><div class="qa-meta"><div class="qa-speaker">Andrew</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=514s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">08:34</a></div></div><div class="qa-body"><p>你如何看待OpenAI近期发生的山姆·奥特曼被罢免又回归这一系列事件？</p></div></section><section class="qa"><div class="qa-meta"><div class="qa-speaker">Jensen</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=522s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">08:42</a></div></div><div class="qa-body"><p>首先，我很高兴看到他们的问题得到了解决，希望一切尘埃落定。他们是一个非常优秀的团队，正在从事重要的工作并取得了卓越的成果，我真心为他们感到高兴。</p></div></section></section><section class="dialogue-subtopic-block"><h3 class="dialogue-subtopic-title">企业治理的重要性</h3><section class="qa"><div class="qa-meta"><div class="qa-speaker">Andrew</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=532s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">08:52</a></div></div><div class="qa-body"><p>这件事是否让你联想到了公司治理的重要性？</p></div></section><section class="qa"><div class="qa-meta"><div class="qa-speaker">Jensen</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=532s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">08:52</a></div></div><div class="qa-body"><p>确实如此。英伟达成立至今已有30年，期间经历过许多逆境。如果当初没有建立起完善的公司治理架构，很难想象我们能走到今天。在开创一个行业时，你需要将那种智慧同样应用于构建公司架构。我为英伟达的治理结构感到自豪，如果不是我29岁时确立的那套架构，公司可能无法存续至今。</p></div></section></section><section class="dialogue-subtopic-block"><h3 class="dialogue-subtopic-title">AI企业的治理模式</h3><div class="qa"><div class="qa-meta"><div class="qa-speaker">Andrew:</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=576s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">09:36</a></div></div><div class="qa-body">鉴于OpenAI以非营利组织架构运作，你认为AI企业是否需要这种非营利模式，还是说激励机制应该完全转向营利性？有趣的是，OpenAI在治理层面实际上是以非营利组织的方式运作的，其初衷是因为创始人认为AI技术具有危险性，因此需要这种架构来约束。</div></div></section></div><div class="dialogue-section-block" data-dialogue-section-id="dialogue-section-6"><section class="section-theme-block"><h2 class="section-theme-title"><span class="section-theme-title-text">AI监管</span><span class="section-theme-divider">: </span><span class="section-theme-summary">应像对待自动驾驶一样规范AI系统安全。</span></h2></section><section class="dialogue-subtopic-block"><h3 class="dialogue-subtopic-title">AI监管原则</h3><section class="qa"><div class="qa-meta"><div class="qa-speaker">Andrew</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=608s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">10:08</a></div></div><div class="qa-body"><p>现在很多人认为资本已经接管了一切，我们是否应该对人工智能进行监管？</p></div></section><section class="qa"><div class="qa-meta"><div class="qa-speaker">Jensen</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=608s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">10:08</a></div></div><div class="qa-body"><p>监管机构并非以营利为目的，我们确实应该进行监管。首先，我们需要退后一步思考什么是人工智能。人工智能本质上是一个自主信息系统。我们今天已经拥有许多自主系统，比如自动驾驶汽车、工厂里的机器人、以及具备自动驾驶和自动着陆功能的飞机。我们应该确保将自主系统的基本原则应用于人工智能，即进行正确的设计、测试、压力测试和监控。这包括内部和外部的安全机制，就像美国联邦航空管理局（FAA）对空中交通管制所做的那样，我们需要建立冗余、多样性等一系列系统，有很多行业经验值得我们借鉴。</p></div></section></section></div><div class="dialogue-section-block" data-dialogue-section-id="dialogue-section-7"><section class="section-theme-block"><h2 class="section-theme-title"><span class="section-theme-title-text">AI未来格局</span><span class="section-theme-divider">: </span><span class="section-theme-summary">通用与专用模型将并存。</span></h2></section><section class="dialogue-subtopic-block"><h3 class="dialogue-subtopic-title">AI竞争格局评价</h3><section class="qa"><div class="qa-meta"><div class="qa-speaker">Andrew</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=674s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">11:14</a></div></div><div class="qa-body"><p>鉴于您对行业的深刻洞察，您如何评价当前AI领域各家公司的竞争表现及排名？</p></div></section><section class="qa"><div class="qa-meta"><div class="qa-speaker">Jensen</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=707s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">11:47</a></div></div><div class="qa-body"><p>我不会对朋友们进行排名，但我可以谈谈这些技术是否会趋同并最终走向商品化。我认为不会出现这种情况。</p></div></section></section><section class="dialogue-subtopic-block"><h3 class="dialogue-subtopic-title">AI模型发展趋势</h3><section class="qa"><div class="qa-meta"><div class="qa-speaker">Andrew</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=707s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">11:47</a></div></div><div class="qa-body"><p>您认为未来这些AI技术是否会趋同，从而导致行业走向商品化？</p></div></section><section class="qa"><div class="qa-meta"><div class="qa-speaker">Jensen</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=724s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">12:04</a></div></div><div class="qa-body"><p>未来我们将拥有非常出色的通用型现成AI，它们能解决许多通用问题。但与此同时，医疗保健等特定行业的公司会利用这些基础模型，通过监督微调，使其在药物研发或芯片设计等专业领域表现卓越。以我们公司为例，核心价值在于内部积累的数据、智能和工艺诀窍，这些数据并不在互联网上，因此我们需要构建智能AI并专门训练它来学习芯片设计和软件编写等专业技能。</p></div></section></section></div><div class="dialogue-section-block" data-dialogue-section-id="dialogue-section-8"><section class="section-theme-block"><h2 class="section-theme-title"><span class="section-theme-title-text">芯片独立</span><span class="section-theme-divider">: </span><span class="section-theme-summary">实现供应链完全独立需十年以上。</span></h2></section><section class="dialogue-subtopic-block"><h3 class="dialogue-subtopic-title">芯片独立的可行性</h3><section class="qa"><div class="qa-meta"><div class="qa-speaker">Andrew</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=771s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">12:51</a></div></div><div class="qa-body"><p>关于芯片独立以及美国本土制造芯片的投资，我们目前处于什么阶段，您认为这是一个值得追求的目标吗？</p></div></section><section class="qa"><div class="qa-meta"><div class="qa-speaker">Jensen</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=805s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">13:25</a></div></div><div class="qa-body"><p>我们距离实现供应链独立还有十年到二十年的路要走。我们的系统包含35,000个零件，其中有8个来自台积电，而整个供应链分布在世界各地。虽然我们绝对应该努力去尝试，但要实现供应链的完全独立，在未来十年或二十年内并不现实。</p></div></section></section></div><div class="dialogue-section-block" data-dialogue-section-id="dialogue-section-9"><section class="section-theme-block"><h2 class="section-theme-title"><span class="section-theme-title-text">出口管制</span><span class="section-theme-divider">: </span><span class="section-theme-summary">平衡国家安全与商业利益。</span></h2></section><section class="dialogue-subtopic-block"><h3 class="dialogue-subtopic-title">如何看待对华芯片出口限制</h3><section class="qa"><div class="qa-meta"><div class="qa-speaker">Andrew</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=840s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">14:00</a></div></div><div class="qa-body"><p>美国政府要求限制向中国出口芯片的速度，这对您的业务产生了影响，您如何从地缘政治和商业角度看待这一国家安全问题？</p></div></section><section class="qa"><div class="qa-meta"><div class="qa-speaker">Jensen</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=869s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">14:29</a></div></div><div class="qa-body"><p>作为一家企业，我们的原则是尽可能与所有人开展业务。但另一方面，国家安全和国家竞争力至关重要，我们必须在商业利益与国家安全之间找到平衡。国家既希望我们的行业能够成功、引领世界并实现技术独立，同时又必须确保国家安全。目前的法规正是为了实现这一目标，我们最尖端的技术不会提供给中国。针对新出台的法规，我们必须研发出符合规定的新芯片，一旦合规，我们将重返市场并继续尽力而为。</p></div></section></section></div><div class="dialogue-section-block" data-dialogue-section-id="dialogue-section-10"><section class="section-theme-block"><h2 class="section-theme-title"><span class="section-theme-title-text">技术竞争</span><span class="section-theme-divider">: </span><span class="section-theme-summary">中国半导体技术仍落后于行业领先水平。</span></h2></section><section class="dialogue-subtopic-block"><h3 class="dialogue-subtopic-title">技术限制的影响</h3><section class="qa"><div class="qa-meta"><div class="qa-speaker">Andrew</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=935s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">15:35</a></div></div><div class="qa-body"><p>你是否认为通过限制芯片出口，反而会促使中国等地区发展出我们无法控制的竞争对手？</p></div></section><section class="qa"><div class="qa-meta"><div class="qa-speaker">Jensen</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=951s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">15:51</a></div></div><div class="qa-body"><p>在复杂的系统中，任何决策都可能产生意想不到的后果。如果我们限制他们获取英伟达的技术，他们可能会通过其他途径获得，或者转而激励本土产业的发展。目前中国已经有大约50家公司正在致力于提供此类技术，这是一个非常复杂的问题。</p></div></section></section><section class="dialogue-subtopic-block"><h3 class="dialogue-subtopic-title">华为芯片的突破</h3><section class="qa"><div class="qa-meta"><div class="qa-speaker">Andrew</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=984s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">16:24</a></div></div><div class="qa-body"><p>华为近期推出的手机采用了7纳米芯片，这是否让你感到惊讶，因为此前普遍认为中国在这一领域落后我们多年？</p></div></section><section class="qa"><div class="qa-meta"><div class="qa-speaker">Jensen</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=1007s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">16:47</a></div></div><div class="qa-body"><p>市场上关于此事的传闻由来已久，因此业内人士对此并不感到惊讶。虽然这些数字只是代号，但他们确实通过技术手段将芯片性能提升到了足以制造手机的水平，这证明了他们能够通过优化现有技术来实现目标。</p></div></section></section><section class="dialogue-subtopic-block"><h3 class="dialogue-subtopic-title">半导体技术差距</h3><section class="qa"><div class="qa-meta"><div class="qa-speaker">Andrew</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=1041s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">17:21</a></div></div><div class="qa-body"><p>你认为我们在半导体领域领先他们多少年？</p></div></section><section class="qa"><div class="qa-meta"><div class="qa-speaker">Jensen</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=1041s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">17:21</a></div></div><div class="qa-body"><p>你可以将其称为十年左右的差距。尽管如此，世界各地的工程师都非常聪明，他们完全有能力通过不断挖掘旧技术的潜力，将其性能提升到接近领先水平的程度。</p></div></section></section></div><div class="dialogue-section-block" data-dialogue-section-id="dialogue-section-11"><section class="section-theme-block"><h2 class="section-theme-title"><span class="section-theme-title-text">危机管理</span><span class="section-theme-divider">: </span><span class="section-theme-summary">黄仁勋在逆境中能保持专注并高效工作。</span></h2></section><section class="dialogue-subtopic-block"><h3 class="dialogue-subtopic-title">如何看待ASML的垄断地位</h3><section class="qa"><div class="qa-meta"><div class="qa-speaker">Andrew</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=1075s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">17:55</a></div></div><div class="qa-body"><p>荷兰的ASML公司几乎为全球所有芯片制造提供设备，有人称其为垄断企业，我们是否应该对这种权力感到担忧？</p></div></section><section class="qa"><div class="qa-meta"><div class="qa-speaker">Jensen</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=1096s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">18:16</a></div></div><div class="qa-body"><p>他们制造的设备非常出色，且技术极其复杂，研发耗时极长。他们有动力向全球供应设备，因此我并不担心。我认为各方的激励机制是一致的，他们是优秀的供应商。</p></div></section></section><section class="dialogue-subtopic-block"><h3 class="dialogue-subtopic-title">为何始终保持危机感</h3><section class="qa"><div class="qa-meta"><div class="qa-speaker">Andrew</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=1126s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">18:46</a></div></div><div class="qa-body"><p>即便英伟达已经取得了巨大成功，你依然将“竭尽全力避免公司倒闭”作为座右铭，这背后的原因是什么？</p></div></section><section class="qa"><div class="qa-meta"><div class="qa-speaker">Jensen</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=1144s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">19:04</a></div></div><div class="qa-body"><p>当你白手起家并经历过多次濒临倒闭的真实逆境后，那种感觉会伴随你一生。我每天早上醒来时，并非感到骄傲和自信，而是充满担忧和关切。我生活在一种既有绝望感又充满抱负的状态中。</p></div></section></section><section class="dialogue-subtopic-block"><h3 class="dialogue-subtopic-title">逆境下的工作状态</h3><section class="qa"><div class="qa-meta"><div class="qa-speaker">Andrew</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=1221s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">20:21</a></div></div><div class="qa-body"><p>你曾提到自己在逆境中思考最清晰，甚至心率会下降，这与常人截然不同，你是如何做到的？</p></div></section><section class="qa"><div class="qa-meta"><div class="qa-speaker">Jensen</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=Pkj-BLHs6dE&amp;t=1247s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">20:47</a></div></div><div class="qa-body"><p>在逆境中，人会变得更加专注，而专注能带来更好的表现。我喜欢那种“濒临灭亡”的状态，我在那种条件下能发挥出最佳水平，甚至会开玩笑地告诉妻子我今天又拯救了公司。</p></div></section></section></div>`,
  meta: {
    stage: 'complete',
    statusText: '内容已完成',
    videoId: JENSEN_VIDEO_ID,
    sourceTitle: 'Jensen Huang of Nvidia on the Future of A.I. | DealBook Summit 2023',
    sourceAuthor: 'New York Times Events',
    sourceLanguage: 'English (auto-generated)',
    sourceLanguageCode: 'en',
    isAutoGenerated: true,
    thumbnailUrl: 'https://i.ytimg.com/vi_webp/Pkj-BLHs6dE/sddefault.webp',
    durationSeconds: 1689,
    transcriptChunks: 95,
    resultMode: 'transcript',
    readingMode: 'full',
    readingModeLabel: '详细版',
    translatedTitleZh: '英伟达CEO黄仁勋谈人工智能的未来 | 2023年DealBook峰会',
    summaryZh: '如果你在1993年就知道创业过程会面临如此多的艰难险阻，你可能根本就不会开始。',
    geminiTranslationComplete: true,
    translationNeedsRefresh: false,
  },
} satisfies {
  articleHtml: string;
  meta: Record<string, unknown>;
};
