import type {
  StoredDialogueGroup,
  StoredDialogueTurn,
  StoredFullRendering,
  StoredTranslationContent,
} from '../services/render-content';
import { blockCuratedGeneratedArticle } from './curated-hot-block';
import { andreessenCuratedTranslationContent } from './curated-hot-content';
import { jensenCuratedGeneratedArticle } from './curated-hot-jensen';

type CuratedGeneratedArticle = {
  articleHtml: string;
  meta: Record<string, unknown>;
};

function escapeHtml(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}

function timestampToSeconds(timestamp: string): number {
  const parts = timestamp.split(':').map((part) => Number.parseInt(part, 10));
  if (parts.some((part) => !Number.isFinite(part) || part < 0)) {
    return 0;
  }

  if (parts.length === 2) {
    return parts[0] * 60 + parts[1];
  }

  if (parts.length === 3) {
    return parts[0] * 60 * 60 + parts[1] * 60 + parts[2];
  }

  return 0;
}

function renderTimestampLink(videoId: string, timestamp: string): string {
  const seconds = timestampToSeconds(timestamp);
  const href = `https://www.youtube.com/watch?v=${escapeHtml(videoId)}&amp;t=${seconds}s`;
  return `<a href="${href}" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">${escapeHtml(timestamp)}</a>`;
}

function renderQa(videoId: string, turn: StoredDialogueTurn): string {
  const speakerHtml = turn.speaker
    ? `<div class="qa-speaker">${escapeHtml(turn.speaker)}</div>`
    : '';

  return [
    '<section class="qa">',
    '<div class="qa-meta">',
    speakerHtml,
    `<div class="qa-time">${renderTimestampLink(videoId, turn.timestamp)}</div>`,
    '</div>',
    `<div class="qa-body"><p>${escapeHtml(turn.textZh)}</p></div>`,
    '</section>',
  ].join('');
}

function renderDialogueGroup(videoId: string, group: StoredDialogueGroup): string {
  const parts: string[] = [
    '<section class="dialogue-subtopic-block">',
    `<h3 class="dialogue-subtopic-title">${escapeHtml(group.topicTitleZh)}</h3>`,
  ];

  if (group.question) {
    parts.push(renderQa(videoId, group.question));
  }

  for (const answer of group.answers ?? []) {
    parts.push(renderQa(videoId, answer));
  }

  if (!group.question && !(group.answers ?? []).length) {
    for (const turn of group.turns) {
      parts.push(renderQa(videoId, turn));
    }
  }

  parts.push('</section>');
  return parts.join('');
}

function renderFullArticle(content: StoredTranslationContent): CuratedGeneratedArticle {
  const full = content.renderings.full as StoredFullRendering | undefined;
  if (!full) {
    throw new Error('Missing full curated rendering');
  }

  const source = content.source;
  const articleParts: string[] = [
    '<header class="article-hero" data-article-hero="">',
    `<h1 data-article-title="">${escapeHtml(full.hero.displayTitle)}</h1>`,
    '<blockquote class="article-pullquote"><p class="transcript-kicker">',
    `<span data-article-kicker="">${escapeHtml(full.hero.summaryZh)}</span>`,
    '</p></blockquote>',
    '<figure class="article-media">',
    `<img class="article-media-image" data-article-thumb="" src="${escapeHtml(source.thumbnailUrl)}" alt="${escapeHtml(source.sourceTitle)} 缩略图" loading="eager" referrerpolicy="no-referrer">`,
    '</figure>',
    '</header>',
  ];

  for (const section of full.sections) {
    articleParts.push(
      `<div class="dialogue-section-block" data-dialogue-section-id="${escapeHtml(section.id)}">`,
      '<section class="section-theme-block">',
      '<h2 class="section-theme-title">',
      `<span class="section-theme-title-text">${escapeHtml(section.titleZh)}</span>`,
      '<span class="section-theme-divider">: </span>',
      `<span class="section-theme-summary">${escapeHtml(section.summaryZh)}</span>`,
      '</h2>',
      '</section>',
    );

    for (const group of section.groups) {
      articleParts.push(renderDialogueGroup(source.videoId, group));
    }

    articleParts.push('</div>');
  }

  return {
    articleHtml: articleParts.join(''),
    meta: {
      stage: 'complete',
      statusText: '内容已完成',
      videoId: source.videoId,
      sourceTitle: source.sourceTitle,
      sourceAuthor: source.sourceAuthor,
      sourceLanguage: source.isAutoGenerated ? `${source.sourceLanguage} (auto-generated)` : source.sourceLanguage,
      sourceLanguageCode: source.sourceLanguageCode,
      isAutoGenerated: source.isAutoGenerated,
      thumbnailUrl: source.thumbnailUrl,
      durationSeconds: source.durationSeconds,
      transcriptChunks: full.sections.reduce((total, section) => total + section.turns.length, 0),
      resultMode: 'transcript',
      readingMode: 'full',
      readingModeLabel: '详细版',
      translatedTitleZh: full.hero.translatedTitleZh,
      summaryZh: full.hero.summaryZh,
      geminiTranslationComplete: full.geminiTranslationComplete,
      translationNeedsRefresh: full.translationNeedsRefresh,
    },
  };
}

const curatedGeneratedArticles: Record<string, Partial<Record<'quick' | 'full', CuratedGeneratedArticle>>> = {
  krdrkl38nRw: {
    full: blockCuratedGeneratedArticle,
  },
  'Pkj-BLHs6dE': {
    full: jensenCuratedGeneratedArticle,
  },
  xRh2sVcNXQ8: {
    full: renderFullArticle(andreessenCuratedTranslationContent),
  },
};

export function getCuratedGeneratedArticle(
  videoId: string,
  readingMode: string,
): CuratedGeneratedArticle | null {
  const article = curatedGeneratedArticles[videoId.trim()]?.[readingMode === 'quick' ? 'quick' : 'full'];
  return article ?? null;
}
