import type { TranscriptDialogueSliceResult, TranscriptSection } from '../services/gemini';
import {
  buildStoredFullRendering,
  buildStoredQuickRendering,
  buildStoredTranslationContent,
  type StoredTranslationContent,
} from '../services/render-content';
import type { TranscriptBundle } from '../services/youtube';

const CURATED_MODEL = 'manual_curated_translation';
const BLOCK_UPDATED_AT = 1775363013556;
const BLOCK_VIDEO_ID = 'krdrkl38nRw';

function joinText(parts: string[]): string {
  return parts.join('');
}

function addDefaultQaSpeaker(articleHtml: string, speaker: string): string {
  return articleHtml.replaceAll(
    '<div class="qa-meta"><div class="qa-time">',
    `<div class="qa-meta"><div class="qa-speaker">${speaker}</div><div class="qa-time">`,
  );
}

function createDialogueSlice(input: {
  startLabel: string;
  endLabel: string;
  titleZh: string;
  summaryZh: string;
  topicTitleZh: string;
  questionSpeaker: string;
  question: string;
  answerSpeaker: string;
  answer: string;
}): TranscriptDialogueSliceResult {
  return {
    section: {
      startLabel: input.startLabel,
      endLabel: input.endLabel,
      subtitle: input.titleZh,
      summary: input.summaryZh,
      transcript: '',
      topicTitleZh: input.titleZh,
      topicSummaryZh: input.summaryZh,
      subtitleZh: input.titleZh,
      summaryZh: input.summaryZh,
    },
    turns: [
      {
        timestamp: input.startLabel,
        speaker: input.questionSpeaker,
        textZh: input.question,
      },
      {
        timestamp: input.endLabel,
        speaker: input.answerSpeaker,
        textZh: input.answer,
      },
    ],
    groups: [
      {
        topicTitleZh: input.topicTitleZh,
        question: {
          timestamp: input.startLabel,
          speaker: input.questionSpeaker,
          textZh: input.question,
        },
        answers: [
          {
            timestamp: input.endLabel,
            speaker: input.answerSpeaker,
            textZh: input.answer,
          },
        ],
        turns: [
          {
            timestamp: input.startLabel,
            speaker: input.questionSpeaker,
            textZh: input.question,
          },
          {
            timestamp: input.endLabel,
            speaker: input.answerSpeaker,
            textZh: input.answer,
          },
        ],
      },
    ],
    model: CURATED_MODEL,
  };
}

const sourceBundle: TranscriptBundle = {
  videoId: BLOCK_VIDEO_ID,
  sourceTitle: "How to Reorg After AI Changes Everything | Block's Owen Jennings on the a16z Show",
  sourceAuthor: 'a16z',
  channelId: '',
  languageCode: 'en',
  languageName: 'English (auto-generated)',
  isAutoGenerated: true,
  durationSeconds: 1636,
  viewCount: 0,
  thumbnailUrl: 'https://i.ytimg.com/vi_webp/krdrkl38nRw/sddefault.webp',
  segments: [],
  chunks: [],
  transcriptText: '',
};

const fullDialogueSlices: TranscriptDialogueSliceResult[] = [
  createDialogueSlice({
    startLabel: '00:10',
    endLabel: '00:49',
    titleZh: 'AI让裁员从成本问题变成范式切换',
    summaryZh: '员工规模与产出挂钩的老逻辑正在失效',
    topicTitleZh: '裁员动因',
    questionSpeaker: 'Host',
    question: 'Block为什么会做出裁减40%员工这样激进的决定？',
    answerSpeaker: 'Owen',
    answer: joinText([
      'Owen 的核心判断是，过去几十年里“人越多、产出越多”的公司规律已经被AI打破。',
      '现在一两名工程师配合AI工具，生产力就可能提升10倍、20倍甚至100倍，因此同样的产品路线图未来不再需要过去那么多工程师、设计师和产品经理。',
      '所以这次调整并不只是一次简单裁员，而是一次围绕AI重新定义运营方式和未来组织形态的重组。',
    ]),
  }),
  createDialogueSlice({
    startLabel: '01:57',
    endLabel: '02:16',
    titleZh: '真正的转折点是AI开始接管复杂旧代码库',
    summaryZh: '从Goose到更强模型，开发生产力发生质变',
    topicTitleZh: '技术变革',
    questionSpeaker: 'Host',
    question: '这次决策背后，更像是纠正过度招聘，还是在回应AI带来的生产力跃迁？',
    answerSpeaker: 'Owen',
    answer: joinText([
      '他把原因明确归到后者。',
      'Block 很早就在布局智能体开发，并在2024年初推出 Goose；真正的质变发生在更强模型出现之后，因为它们不只是会写新代码，更开始能处理复杂的存量代码库。',
      '这意味着公司构建软件的方式被根本改写，所以开发端的大规模裁减不是单纯去冗员，而是在承认“手动写代码的时代正在结束”。',
    ]),
  }),
  createDialogueSlice({
    startLabel: '06:14',
    endLabel: '07:49',
    titleZh: '重组先看系统可靠性、合规与长期增长',
    summaryZh: '不是为了短期财务数字，而是为了在AI时代保住关键能力',
    topicTitleZh: '组织重构',
    questionSpeaker: 'Host',
    question: '你们在重组时坚持了哪些原则，哪些能力必须保住？',
    answerSpeaker: 'Owen',
    answer: joinText([
      '他们不是围绕财务指标去倒推人数，而是先定义哪些东西绝不能牺牲。',
      '第一是可靠性，系统在重组期间不能掉链子；第二是客户信任与合规，在受监管环境里不能妥协；第三是持久增长，要保证既定路线图和长期战略投入继续推进。',
      '因此哪怕有些团队从14人缩到3人，Block 也要求核心功能和长期投入不能被中断。',
    ]),
  }),
  createDialogueSlice({
    startLabel: '07:49',
    endLabel: '09:06',
    titleZh: '执行上从零设计新组织，并尽量减少反复裁员的伤害',
    summaryZh: '一次性重组优于持续恐慌',
    topicTitleZh: '重组执行',
    questionSpeaker: 'Host',
    question: '这次重组在具体执行上和传统裁员有什么不同？',
    answerSpeaker: 'Owen',
    answer: joinText([
      'Block 基本是从零开始重画组织结构，尤其在开发侧变化非常大。',
      '执行时他们尽量保持人性化，比如提供更慷慨的遣散方案，并由 Jack 和高管团队直接向全员解释原因，而不是只给结果。',
      'Owen 还强调，相比反复多轮小规模裁员，一次性做完整调整虽然痛，但文化代价反而更低，因为团队不会长期活在下一轮裁员的阴影里。',
    ]),
  }),
  createDialogueSlice({
    startLabel: '09:06',
    endLabel: '11:16',
    titleZh: '重组后的日常：会议骤减，开发者转向管理多个Agent',
    summaryZh: '组织更扁平，工作流从线性协作变成并行调度',
    topicTitleZh: '运营变化',
    questionSpeaker: 'Host',
    question: '组织收缩之后，最显著的运营变化是什么？',
    answerSpeaker: 'Owen',
    answer: joinText([
      '最直观的变化是会议减少了70%到80%，很多时间重新回到了“真正构建产品”这件事上。',
      '公司层级更少、管理跨度更大、节奏更像早期创业团队。',
      '与此同时，开发流程也不再是提交PR、等审核、再修改的线性循环，而是一个人同时管理十几个后台代理，让它们并行产出，再由人去检查、微调和整合。',
    ]),
  }),
  createDialogueSlice({
    startLabel: '11:16',
    endLabel: '13:08',
    titleZh: 'AI会让单家公司更小，但不一定减少整体需求',
    summaryZh: '更少的人能做更多事，也会催生更多公司',
    topicTitleZh: 'AI重塑组织',
    questionSpeaker: 'Host',
    question: '其他公司会不会走上类似道路，这是否意味着相关岗位需求长期下降？',
    answerSpeaker: 'Owen',
    answer: joinText([
      'Owen 认为，针对同样的产品和路线图，未来确实会需要更少的工程师、设计师和产品经理。',
      '但这不等于全球总需求下降，因为生产力提升会释放出更多可被构建的产品组合，类似杰文斯悖论。',
      '结果可能是单一科技公司规模变小，但市场上会出现更多科技公司，以及更多原本不算科技行业的企业被数字化。',
    ]),
  }),
  createDialogueSlice({
    startLabel: '13:08',
    endLabel: '16:02',
    titleZh: 'AI开始成为组织的内置基础设施',
    summaryZh: '小组化组织、Builderbot 与更自由的信息流同时出现',
    topicTitleZh: '组织重构',
    questionSpeaker: 'Host',
    question: 'AI在Block内部到底是一个工具，还是已经变成基础设施？',
    answerSpeaker: 'Owen',
    answer: joinText([
      '他的答案更接近后者。',
      'Block 正从传统职能层级转向由1到6人组成的小组，大幅减少管理层级，让信息在组织中更自由地流动。',
      '在开发层面，产品经理和设计师也能更直接地下场改代码，而内部工具 Builderbot 已能完成大部分实现工作，人类更多负责最后的判断和微调。',
    ]),
  }),
  createDialogueSlice({
    startLabel: '16:02',
    endLabel: '19:52',
    titleZh: '确定性流程自动化与跨业务代理平台正在合并',
    summaryZh: '客户支持、风险控制和多业务平台都在被代理层统一',
    topicTitleZh: '平台整合',
    questionSpeaker: 'Host',
    question: '除了写代码，AI在客户支持、运营和跨业务平台整合里扮演什么角色？',
    answerSpeaker: 'Owen',
    answer: joinText([
      '他认为，凡是确定性的工作流，理论上都可以被自动化。',
      '在客户支持、风险控制和合规决策里，AI与代理系统已经在承担越来越多的工作，只是短期内仍需“人在回路”来满足监管要求。',
      '更上层的变化是，Block 用 Goose 这样的模型无关代理框架把 Square、Cash App、Afterpay 等业务背后的技术和数据能力串了起来，让 Moneybot、Manager bot 这类主动式助手能跨产品工作。',
    ]),
  }),
  createDialogueSlice({
    startLabel: '19:52',
    endLabel: '24:34',
    titleZh: '生成式UI与主动智能会重写产品体验和企业护城河',
    summaryZh: '长期优势不只是渠道和网络，更是深刻的业务理解与迭代速度',
    topicTitleZh: '核心护城河',
    questionSpeaker: 'Host',
    question: '从产品到资本市场，再到长期护城河，Block 如何理解AI时代真正的竞争优势？',
    answerSpeaker: 'Owen',
    answer: joinText([
      '在产品层，Owen 认为静态UI会被生成式UI快速改写，未来界面将根据用户意图和上下文动态生成，而不是由团队预先把每一条路径都写死。',
      '在经营层，他认为股价短期受市场投票影响，但长期仍取决于企业是否持续把业务做强。',
      '而在长期防御能力上，真正难以复制的不是单一功能，而是企业能否深刻理解别人不容易掌握的业务逻辑，并把这种理解转成高频反馈循环，让AI持续放大这种独特认知。',
    ]),
  }),
];

const quickSections: TranscriptSection[] = fullDialogueSlices.map((slice) => slice.section);

export const blockCuratedHotItem = {
  videoId: BLOCK_VIDEO_ID,
  title: 'AI如何改变一切：Block公司如何进行组织重组',
  author: sourceBundle.sourceAuthor,
  thumbnailUrl: sourceBundle.thumbnailUrl,
  youtubeUrl: `https://www.youtube.com/watch?v=${BLOCK_VIDEO_ID}`,
  viewCount: 0,
  updatedAt: BLOCK_UPDATED_AT,
};

export const blockCuratedTranslationContent: StoredTranslationContent = buildStoredTranslationContent(
  sourceBundle,
  {
    quick: buildStoredQuickRendering(sourceBundle, quickSections, {
      translatedTitleZh: 'AI如何改变一切：Block公司如何进行组织重组',
      summaryZh: '公司最大的护城河在于能否深刻理解他人难以掌握的核心业务逻辑。',
      summary: 'Owen Jennings explains why AI forced Block to redesign its org, shrink teams, automate deterministic work, and treat deep business understanding as the long-term moat.',
      speakers: ['Host', 'Owen'],
      model: CURATED_MODEL,
      geminiTranslationComplete: true,
      translationNeedsRefresh: false,
    }),
    full: buildStoredFullRendering(sourceBundle, fullDialogueSlices, {
      translatedTitleZh: 'AI如何改变一切：Block公司如何进行组织重组',
      summaryZh: '公司最大的护城河在于能否深刻理解他人难以掌握的核心业务逻辑。',
      summary: 'Owen Jennings explains why AI forced Block to redesign its org, shrink teams, automate deterministic work, and treat deep business understanding as the long-term moat.',
      speakers: ['Host', 'Owen'],
      model: CURATED_MODEL,
      geminiTranslationComplete: true,
      translationNeedsRefresh: false,
    }),
  },
  BLOCK_UPDATED_AT,
);

export const blockCuratedGeneratedArticle = {
  articleHtml: addDefaultQaSpeaker(
    String.raw`<header class="article-hero" data-article-hero=""><h1 data-article-title="">AI如何改变一切：Block公司如何进行组织重组</h1><blockquote class="article-pullquote"><p class="transcript-kicker"><span data-article-kicker="">公司最大的护城河在于能否深刻理解他人难以掌握的核心业务逻辑。</span></p></blockquote><figure class="article-media"><img class="article-media-image" data-article-thumb="" src="https://i.ytimg.com/vi_webp/krdrkl38nRw/sddefault.webp" alt="How to Reorg After AI Changes Everything | Block's Owen Jennings on the a16z Show 缩略图" loading="eager" referrerpolicy="no-referrer"></figure></header><div class="dialogue-section-block" data-dialogue-section-id="dialogue-section-1"><section class="section-theme-block"><h2 class="section-theme-title"><span class="section-theme-title-text">裁员动因</span><span class="section-theme-divider">: </span><span class="section-theme-summary">AI提升生产力导致人员需求减少。</span></h2></section><section class="dialogue-subtopic-block"><h3 class="dialogue-subtopic-title">裁员决策背景</h3><section class="qa"><div class="qa-meta"><div class="qa-time"><a href="https://www.youtube.com/watch?v=krdrkl38nRw&amp;t=10s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">00:10</a></div></div><div class="qa-body"><p>Block公司为何做出裁减40%员工的重大决定？</p></div></section><section class="qa"><div class="qa-meta"><div class="qa-speaker">Owen</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=krdrkl38nRw&amp;t=10s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">00:10</a></div></div><div class="qa-body"><p>几十年来，公司员工数量与产出之间一直存在相关性，但我认为这种模式已经失效。我们观察到，使用AI工具的一两名工程师的生产力可以提升10倍、20倍甚至100倍。显而易见，这些系统比雇佣一千人来完成同样的工作要高效得多。从根本上讲，对于特定的产品或路线图，未来将不再需要那么多的工程师、设计师和产品经理，这一点非常明确。</p></div></section></section><section class="dialogue-subtopic-block"><h3 class="dialogue-subtopic-title">组织重组差异</h3><section class="qa"><div class="qa-meta"><div class="qa-time"><a href="https://www.youtube.com/watch?v=krdrkl38nRw&amp;t=49s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">00:49</a></div></div><div class="qa-body"><p>在裁员40%之后，公司在运营方式上最显著的变化是什么？</p></div></section><section class="qa"><div class="qa-meta"><div class="qa-speaker">Owen</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=krdrkl38nRw&amp;t=49s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">00:49</a></div></div><div class="qa-body"><p>最核心的问题在于，一家大型上市公司如何围绕AI进行重组。我们正在经历从产品线到业务单元的大规模AI转型，这不仅是关于裁员的决定，更是关于如何适应当前及未来的业务状态，通过AI重塑我们的运营逻辑。</p></div></section></section></div><div class="dialogue-section-block" data-dialogue-section-id="dialogue-section-2"><section class="section-theme-block"><h2 class="section-theme-title"><span class="section-theme-title-text">技术变革</span><span class="section-theme-divider">: </span><span class="section-theme-summary">AI工具使代码编写效率实现质变。</span></h2></section><section class="dialogue-subtopic-block"><h3 class="dialogue-subtopic-title">裁员决策背景</h3><div class="qa"><div class="qa-meta"><div class="qa-speaker">Host:</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=krdrkl38nRw&amp;t=117s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">01:57</a></div></div><div class="qa-body">Block公司此前做出了裁员40%的重大决定，能否分享一下这一决策背后的考量？</div></div><div class="qa"><div class="qa-meta"><div class="qa-speaker">Owen:</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=krdrkl38nRw&amp;t=136s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">02:16</a></div></div><div class="qa-body">这其实始于两三年前。Jack一向具有前瞻性，我们很早就开始布局智能体开发，并在2024年初推出了首个智能体框架Goose，这改变了我们的内部工具开发方式。到了2024年底，随着Opus 46和Codex 53等模型的出现，我们观察到了一个质的飞跃：AI模型不仅擅长编写新代码，处理现有复杂代码库的能力也突飞猛进。这打破了过去几十年公司规模与产出成正比的传统逻辑，现在一两名工程师配合AI工具，生产力可以提升10倍、20倍甚至100倍。因此，我们利用第一季度深入探讨了这种范式转移对产品开发和公司运营的深远影响，最终做出了裁员决定，且开发部门的裁减幅度尤为显著。这次裁员究竟是因为2021年的过度招聘，还是为了应对AI带来的生产力变革？从2019年到2024年的人均毛利润来看，我们一直处于行业中游水平，去年甚至达到了第二梯队，仅次于英伟达和Meta。如果裁员仅仅是为了削减冗余，那应该针对运营团队，但我们这次是在开发端进行了大规模裁员。这说明我们已经意识到技术和工具正在从根本上改变构建方式，我们不再需要像过去那样手动编写代码了，那个时代已经结束。</div></div></section></div><div class="dialogue-section-block" data-dialogue-section-id="dialogue-section-3" hidden="" aria-hidden="true"></div><div class="dialogue-section-block" data-dialogue-section-id="dialogue-section-4"><section class="section-theme-block"><h2 class="section-theme-title"><span class="section-theme-title-text">组织重构</span><span class="section-theme-divider">: </span><span class="section-theme-summary">以原则为导向重构组织架构。</span></h2></section><section class="dialogue-subtopic-block"><h3 class="dialogue-subtopic-title">重组的核心原则</h3><section class="qa"><div class="qa-meta"><div class="qa-speaker">Host</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=krdrkl38nRw&amp;t=374s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">06:14</a></div></div><div class="qa-body"><p>在进行组织重组时，你们遵循了哪些核心原则？</p></div></section><section class="qa"><div class="qa-meta"><div class="qa-speaker">Owen</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=krdrkl38nRw&amp;t=374s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">06:14</a></div></div><div class="qa-body"><p>我们并非单纯为了财务目标而裁员，而是基于AI工具带来的变化重新思考组织架构。我们确立了三个核心原则：首先是可靠性，确保重组过程中系统绝不能出现故障；其次是建立客户信任与合规，我们在复杂的监管环境下绝不妥协，因此完全保留了合规及相关技术团队；最后是持续推动持久增长，我们确保既定的路线图和长期战略投入不受影响，即便这意味着将原本14人的功能团队缩减为3人的小组，也要保证核心功能的交付。</p></div></section></section><section class="dialogue-subtopic-block"><h3 class="dialogue-subtopic-title">重组的执行细节</h3><section class="qa"><div class="qa-meta"><div class="qa-speaker">Host</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=krdrkl38nRw&amp;t=469s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">07:49</a></div></div><div class="qa-body"><p>在具体的执行层面，这次重组与以往有何不同？</p></div></section><section class="qa"><div class="qa-meta"><div class="qa-speaker">Owen</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=krdrkl38nRw&amp;t=469s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">07:49</a></div></div><div class="qa-body"><p>我们是从零开始重新构建组织。在监管和销售支持等领域，架构与年初变化不大，但在开发侧则完全不同。执行上，我们非常审慎且人性化，考虑到许多离职员工是共事十年的老友，我们提供了慷慨的遣散费，且没有立即切断他们的技术访问权限。此外，Jack和高管团队通过全员大会面对面解释决策背景，以应对随之而来的冲击与不确定性。</p></div></section></section><section class="dialogue-subtopic-block"><h3 class="dialogue-subtopic-title">重组后的运营变化</h3><div class="qa"><div class="qa-meta"><div class="qa-speaker">Host:</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=krdrkl38nRw&amp;t=546s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">09:06</a></div></div><div class="qa-body">重组后公司运营最显著的变化是什么？</div></div><div class="qa"><div class="qa-meta"><div class="qa-speaker">Owen:</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=krdrkl38nRw&amp;t=546s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">09:06</a></div></div><div class="qa-body">最直接的变化是会议数量减少了约70%到80%，这让我有更多时间投入到实际的构建工作中，而不是被连轴转的会议填满。我们现在每周一都会举行全员大会，公司变得更精简、层级更少、管理跨度更大，整体氛围已经回归到专注产品开发的节奏中。非创始人领导的企业在面对组织重组时，通常会采取什么样的策略及其后果是什么？如果领导者缺乏创始人那种大胆决策的能力，往往会采取渐进式的裁员策略。这种方式表现为多次小规模裁员，例如先裁掉15%，过段时间再裁15%。从文化层面来看，这对团队是毁灭性的，因为员工始终处于对未来裁员的持续焦虑和阴影之中。 AI工具的使用如何从根本上改变了团队的开发与协作模式？ AI成为了一个巨大的推动力。以前需要15人完成的项目，现在仅需4人配合AI工具即可完成。工作流已经不再是线性的，即不再是单纯的提交PR、等待审核、修改代码的循环。现在的模式是，开发者同时管理十几个代理（Agent）在后台并行工作，开发者只需在不同任务间切换，检查代理产出的成果，进行微调或引导，最后提交至代码库。这种模式不仅适用于软件开发，同样适用于产品经理和增长营销人员，每个人都在同时管理多个后台运行的AI代理。</div></div></section></div><div class="dialogue-section-block" data-dialogue-section-id="dialogue-section-5" hidden="" aria-hidden="true"></div><div class="dialogue-section-block" data-dialogue-section-id="dialogue-section-6"><section class="section-theme-block"><h2 class="section-theme-title"><span class="section-theme-title-text">AI重塑组织</span><span class="section-theme-divider">: </span><span class="section-theme-summary">AI将催生更多小型科技公司。</span></h2></section><section class="dialogue-subtopic-block"><h3 class="dialogue-subtopic-title">企业AI转型路径</h3><section class="qa"><div class="qa-meta"><div class="qa-speaker">Host</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=krdrkl38nRw&amp;t=676s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">11:16</a></div></div><div class="qa-body"><p>您认为其他公司是否会效仿这种重组路径，以及需要具备哪些条件才能成功？</p></div></section><section class="qa"><div class="qa-meta"><div class="qa-speaker">Owen</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=krdrkl38nRw&amp;t=689s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">11:29</a></div></div><div class="qa-body"><p>我们在2023到2025年间打下了坚实基础，构建了名为Goose的智能体基座，并在其上开发了大量内部工具。我们还拥有一个名为G2的内部智能体操作系统，允许员工自动化任何确定性的工作流程。我认为许多公司都在进行类似的工作，只是进度各不相同。我坚信对于特定的产品或路线图，未来将需要更少的工程师、设计师和产品经理。但这并不意味着全球范围内这些人才的需求会减少，这就像杰文斯悖论一样，技术进步反而会带来更多可构建的产品组合。虽然单一科技公司可能会变得更小，但市场上可能会涌现出更多科技公司，甚至在以往未曾涉及的领域实现数字化转型，不过我目前专注于Block公司的发展，不便预测未来。</p></div></section></section></div><div class="dialogue-section-block" data-dialogue-section-id="dialogue-section-7"><section class="section-theme-block"><h2 class="section-theme-title"><span class="section-theme-title-text">组织重构</span><span class="section-theme-divider">: </span><span class="section-theme-summary">利用代理框架统一业务基础设施。</span></h2></section><section class="dialogue-subtopic-block"><h3 class="dialogue-subtopic-title">AI对内部组织架构的影响</h3><section class="qa"><div class="qa-meta"><div class="qa-time"><a href="https://www.youtube.com/watch?v=krdrkl38nRw&amp;t=788s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">13:08</a></div></div><div class="qa-body"><p>AI在您负责的运营和客户支持等业务领域中是如何应用的？</p></div></section><section class="qa"><div class="qa-meta"><div class="qa-speaker">Owen</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=krdrkl38nRw&amp;t=788s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">13:08</a></div></div><div class="qa-body"><p>AI对我们而言已是内置的基础设施。在组织架构上，我们从传统的职能型层级结构转变为由1到6人组成的灵活小组，大幅减少了管理层级，使信息流动更自由。在开发层面，不仅产品经理和设计师能直接提交代码，我们还开发了名为Builderbot的内部工具，它能自主完成大部分代码编写，仅需人类进行最后的微调，这极大地压缩了从创意到产品交付的周期。</p></div></section></section><section class="dialogue-subtopic-block"><h3 class="dialogue-subtopic-title">确定性工作流的自动化</h3><section class="qa"><div class="qa-meta"><div class="qa-time"><a href="https://www.youtube.com/watch?v=krdrkl38nRw&amp;t=962s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">16:02</a></div></div><div class="qa-body"><p>除了开发领域，AI在其他业务流程中发挥了什么作用？</p></div></section><section class="qa"><div class="qa-meta"><div class="qa-speaker">Owen</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=krdrkl38nRw&amp;t=962s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">16:02</a></div></div><div class="qa-body"><p>任何确定性的工作流都能被自动化。在客户支持方面，聊天机器人和AI语音支持已经处理了大部分查询。在产品运营、风险控制和合规决策等领域，AI模型和代理的表现正逐渐超越人类。虽然目前仍需保持“人在回路”以满足监管要求，但长期来看，这些系统在处理复杂决策上的效率将远超人工。</p></div></section></section><section class="dialogue-subtopic-block"><h3 class="dialogue-subtopic-title">业务生态与平台整合</h3><section class="qa"><div class="qa-meta"><div class="qa-time"><a href="https://www.youtube.com/watch?v=krdrkl38nRw&amp;t=1024s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">17:04</a></div></div><div class="qa-body"><p>Block旗下的Square、Cash App和Afterpay等业务目前是如何整合的？</p></div></section><section class="qa"><div class="qa-meta"><div class="qa-speaker">Owen</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=krdrkl38nRw&amp;t=1024s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">17:04</a></div></div><div class="qa-body"><p>我们已从独立的业务单元结构转向职能化架构，所有工程、设计和产品职能统一汇报。我们构建了跨公司的金融平台和业务平台，旨在打破品牌壁垒。核心策略是利用名为“Goose”的代理框架，它是一个模型无关的代理工具，能根据任务需求灵活切换Anthropic、OpenAI或开源模型。通过这一层级，我们开发了如Moneybot和Manager bot等主动式AI助手，实现了跨产品的技术与数据共享。</p></div></section></section><section class="dialogue-subtopic-block"><h3 class="dialogue-subtopic-title">生成式UI的未来趋势</h3><div class="qa"><div class="qa-meta"><div class="qa-time"><a href="https://www.youtube.com/watch?v=krdrkl38nRw&amp;t=1192s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">19:52</a></div></div><div class="qa-body">在产品层面，AI带来的最大变化是什么？</div></div><div class="qa"><div class="qa-meta"><div class="qa-speaker">Owen:</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=krdrkl38nRw&amp;t=1192s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">19:52</a></div></div><div class="qa-body">最大的转变在于交互方式。过去十几年，用户习惯了静态且固定的UI界面，但随着生成式UI的到来，这种模式将在未来半年内发生根本性改变。我们通过Moneybot和Manager bot的实践发现，界面将变得更加动态和个性化，能够根据模型理解实时生成最符合用户需求的操作界面。生成式UI在实际应用中会呈现出什么样的形态？最简单的理解是，每个人的Cash App界面都应根据个人需求呈现出完全不同的样貌。例如，如果你经常使用比特币，而我频繁使用Afterpay，我们的应用界面就应该有所区分。这不仅仅是简单的个性化，更深层的变化在于，比如通过Moneybot，我可以询问资金支出情况，系统会实时生成图表和可视化内容，这些内容并非预先写在代码中，而是即时生成的。虽然这给质量保证（QA）带来了挑战，但它确实赋予了用户极大的控制权，并能显著提升产品参与度和体验。在Square业务中，ManagerBot是如何体现这种生成式能力的？以拥有多家分店的快餐店主为例，他们可以要求ManagerBot构建一个专门用于管理两家分店排班的应用程序，并自动通过WhatsApp或Signal向员工发送通知。这个应用程序的界面和功能逻辑并不存在于我们推送到应用商店的原始代码中，而是根据需求即时创建的。这种方式不仅能提供更好的产品体验，还能让用户更高效地完成复杂任务。我们是否应该让客户自己去提示这些AI工具以获取结果？我不认为应该完全依赖客户自己去编写提示词，因为他们未必知道如何精准地表达需求。因此，我们在主动智能（proactive intelligence）方面进行了大量投入。特别是在金融领域，我们认为更有价值的做法是由系统主动向客户提供建议和方案，这种主动引导才是创造核心价值的关键所在。</div></div></section></div><div class="dialogue-section-block" data-dialogue-section-id="dialogue-section-8" hidden="" aria-hidden="true"></div><div class="dialogue-section-block" data-dialogue-section-id="dialogue-section-9"><section class="section-theme-block"><h2 class="section-theme-title"><span class="section-theme-title-text">市场价值</span><span class="section-theme-divider">: </span><span class="section-theme-summary">长期价值取决于持续构建。</span></h2></section><section class="dialogue-subtopic-block"><h3 class="dialogue-subtopic-title">股价与业务增长的背离</h3><div class="qa"><div class="qa-meta"><div class="qa-speaker">Owen:</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=krdrkl38nRw&amp;t=1359s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">22:39</a></div></div><div class="qa-body">尽管公司业务和人均毛利润大幅增长，但股价在过去六七年间基本持平，该如何调和这种背离？市场具有周期性，且存在各种外部因素。我记得2021年股价曾达到260美元左右，当时我就觉得那是不理性的。从长远来看，市场短期是投票机，长期是称重机，因此我们只需专注于业务构建。</div></div></section></div><div class="dialogue-section-block" data-dialogue-section-id="dialogue-section-10"><section class="section-theme-block"><h2 class="section-theme-title"><span class="section-theme-title-text">核心护城河</span><span class="section-theme-divider">: </span><span class="section-theme-summary">深刻的业务洞察是核心竞争力。</span></h2></section><section class="dialogue-subtopic-block"><h3 class="dialogue-subtopic-title">Block公司的竞争优势</h3><section class="qa"><div class="qa-meta"><div class="qa-time"><a href="https://www.youtube.com/watch?v=krdrkl38nRw&amp;t=1404s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">23:24</a></div></div><div class="qa-body"><p>您如何看待Block公司目前的核心竞争优势？</p></div></section><section class="qa"><div class="qa-meta"><div class="qa-speaker">Owen</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=krdrkl38nRw&amp;t=1418s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">23:38</a></div></div><div class="qa-body"><p>短期和中期来看，Block拥有分销渠道和网络效应等护城河。例如，虽然任何人都能在一周内开发出一个点对点支付应用，但没人能通过简单的AI编程（vibe coding）复制我们拥有数千万活跃用户的支付生态。此外，我们的牌照资质、监管合规能力以及硬件基础设施也是现阶段难以被替代的壁垒。</p></div></section></section><section class="dialogue-subtopic-block"><h3 class="dialogue-subtopic-title">AI时代的长期护城河</h3><section class="qa"><div class="qa-meta"><div class="qa-time"><a href="https://www.youtube.com/watch?v=krdrkl38nRw&amp;t=1474s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">24:34</a></div></div><div class="qa-body"><p>从长远来看，AI技术变革将如何重塑企业的防御能力？</p></div></section><section class="qa"><div class="qa-meta"><div class="qa-speaker">Owen</div><div class="qa-time"><a href="https://www.youtube.com/watch?v=krdrkl38nRw&amp;t=1474s" target="_blank" rel="noreferrer noopener" class="timestamp rail compact timestamp-link" data-linked="true">24:34</a></div></div><div class="qa-body"><p>长远来看，企业的核心护城河在于能否深刻理解他人难以掌握的业务逻辑。企业应将自身视为一个智能系统，利用深层数据洞察（如买卖双方在经济中的互动模式）构建世界模型。通过将企业价值观、核心指标和业务逻辑转化为可迭代的反馈循环，并结合AI工具，企业可以将原本数月的开发周期缩短至数周甚至更短。未来，能够高频运行这种迭代循环并持续深化独特业务理解的公司，才不会被AI技术所取代。</p></div></section></section></div>`,
    'Host',
  ),
  meta: {
    stage: 'complete',
    statusText: '内容已完成',
    videoId: BLOCK_VIDEO_ID,
    sourceTitle: "How to Reorg After AI Changes Everything | Block's Owen Jennings on the a16z Show",
    sourceAuthor: 'a16z',
    sourceLanguage: 'English (auto-generated)',
    sourceLanguageCode: 'en',
    isAutoGenerated: true,
    thumbnailUrl: 'https://i.ytimg.com/vi_webp/krdrkl38nRw/sddefault.webp',
    durationSeconds: 1636,
    transcriptChunks: 109,
    resultMode: 'transcript',
    readingMode: 'full',
    readingModeLabel: '详细版',
    translatedTitleZh: 'AI如何改变一切：Block公司如何进行组织重组',
    summaryZh: '公司最大的护城河在于能否深刻理解他人难以掌握的核心业务逻辑。',
    geminiTranslationComplete: true,
    translationNeedsRefresh: false,
  },
} satisfies {
  articleHtml: string;
  meta: Record<string, unknown>;
};
