import type { TranscriptDialogueSliceResult, TranscriptSection } from '../services/gemini';
import {
  buildStoredFullRendering,
  buildStoredQuickRendering,
  buildStoredTranslationContent,
  type StoredTranslationContent,
} from '../services/render-content';
import type { TranscriptBundle } from '../services/youtube';

export interface CuratedHotVideoItem {
  videoId: string;
  title: string;
  author: string;
  thumbnailUrl: string;
  youtubeUrl: string;
  viewCount: number;
  updatedAt: number;
}

const CURATED_MODEL = 'manual_curated_translation';
const CURATED_UPDATED_AT = Date.parse('2026-04-05T00:00:00Z');
const CURATED_VIDEO_ID = 'xRh2sVcNXQ8';

function joinText(parts: string[]): string {
  return parts.join('');
}

function createDialogueSlice(input: {
  startLabel: string;
  endLabel: string;
  titleZh: string;
  summaryZh: string;
  topicTitleZh: string;
  questionSpeaker: string;
  question: string;
  answerSpeaker: string;
  answer: string;
}): TranscriptDialogueSliceResult {
  return {
    section: {
      startLabel: input.startLabel,
      endLabel: input.endLabel,
      subtitle: input.titleZh,
      summary: input.summaryZh,
      transcript: '',
      topicTitleZh: input.titleZh,
      topicSummaryZh: input.summaryZh,
      subtitleZh: input.titleZh,
      summaryZh: input.summaryZh,
    },
    turns: [
      {
        timestamp: input.startLabel,
        speaker: input.questionSpeaker,
        textZh: input.question,
      },
      {
        timestamp: input.endLabel,
        speaker: input.answerSpeaker,
        textZh: input.answer,
      },
    ],
    groups: [
      {
        topicTitleZh: input.topicTitleZh,
        question: {
          timestamp: input.startLabel,
          speaker: input.questionSpeaker,
          textZh: input.question,
        },
        answers: [
          {
            timestamp: input.endLabel,
            speaker: input.answerSpeaker,
            textZh: input.answer,
          },
        ],
        turns: [
          {
            timestamp: input.startLabel,
            speaker: input.questionSpeaker,
            textZh: input.question,
          },
          {
            timestamp: input.endLabel,
            speaker: input.answerSpeaker,
            textZh: input.answer,
          },
        ],
      },
    ],
    model: CURATED_MODEL,
  };
}

const sourceBundle: TranscriptBundle = {
  videoId: CURATED_VIDEO_ID,
  sourceTitle: "Marc Andreessen's 2026 Outlook: AI Timelines, US vs. China, and The Price of AI",
  sourceAuthor: 'a16z',
  channelId: 'UC9cn0TuPq4dnbTY-CBsm8XA',
  languageCode: 'en',
  languageName: 'English',
  isAutoGenerated: true,
  durationSeconds: 4878,
  viewCount: 232375,
  thumbnailUrl: 'https://i.ytimg.com/vi_webp/xRh2sVcNXQ8/hqdefault.webp',
  segments: [],
  chunks: [],
  transcriptText: '',
};

const fullDialogueSlices: TranscriptDialogueSliceResult[] = [
  createDialogueSlice({
    startLabel: '00:00',
    endLabel: '00:20',
    titleZh: 'AI公司的收入增长与产品形态演进',
    summaryZh: '收入起飞，形态未定',
    topicTitleZh: '收入起飞',
    questionSpeaker: 'Jen',
    question: '目前AI公司的商业化表现和收入增长，大致处于什么状态？',
    answerSpeaker: 'Marc',
    answer: joinText([
      '这一波AI公司正在经历近乎前所未见的收入起飞。这里说的不是纸面上的想象空间，而是真实的客户需求转化为实际营收，最终体现在银行账户里的现金流，而且爬升速度极其惊人。',
      '我们看到，真正领先、并且做出实质性突破的AI公司，收入增长曲线已经快到超过我过去见过的任何一类科技企业。',
      '与此同时，我非常怀疑今天大家正在使用的这些AI产品形态，会是5年或10年后的最终形态。我更倾向于认为，未来的产品会比现在复杂得多、成熟得多、也强大得多。',
      '所以从这个意义上看，我们现在仍然在很早期的位置，后面还有很长的路要走。',
    ]),
  }),
  createDialogueSlice({
    startLabel: '00:20',
    endLabel: '00:48',
    titleZh: '战略选择与风投押注逻辑',
    summaryZh: '企业单选，风投多押',
    topicTitleZh: '多线押注',
    questionSpeaker: 'Jen',
    question: '面对AI带来的这些根本性战略和经济问题，公司与风险投资机构的应对方式有什么不同？',
    answerSpeaker: 'Marc',
    answer: joinText([
      '这些问题本身就是价值数万亿美元的命题，但现在还远远谈不上已有定论。',
      '一旦某种能力被证明可行，后来者往往就会迅速跟上，哪怕他们手里的资源少得多。',
      '对一家公司来说，如果它面对的是这种开放性的战略或经济问题，那通常意味着真正的大考来了。企业必须给出答案，而且一旦判断失误，后果会非常严重。',
      '但风投机构的优势在于，我们不需要只押一条路。我们可以并行布局多种可能成立的策略。对于每一条我们判断“有现实胜算”的路径，我们都会积极下注。',
    ]),
  }),
  createDialogueSlice({
    startLabel: '00:48',
    endLabel: '01:14',
    titleZh: 'AI的公众态度与真实行为',
    summaryZh: '口头恐慌，实际在用',
    topicTitleZh: '态度反差',
    questionSpeaker: 'Jen',
    question: '大众对AI的认知，和他们真实的使用行为之间，是否存在明显落差？',
    answerSpeaker: 'Marc',
    answer: joinText([
      '如果你想理解人们到底怎么想、怎么做，通常有两种方法：一种是直接问他们，另一种是观察他们的行为。',
      '现实中，在很多人类活动领域里，人们口头上说的，和他们真正做的，往往完全不是一回事。',
      '举例来说，如果你去调查美国选民对AI的看法，他们给出的回答很可能是高度恐慌的：觉得AI会摧毁就业，会把一切搞砸，看起来像是全面失控。',
      '但如果你去看他们实际的“显性偏好”，你会发现另一幅图景：他们其实已经在广泛使用AI。',
    ]),
  }),
  createDialogueSlice({
    startLabel: '01:46',
    endLabel: '09:10',
    titleZh: 'AI革命的历史位置与当前所处阶段',
    summaryZh: '八十年革命刚进第三年',
    topicTitleZh: '革命位置',
    questionSpeaker: 'Jen',
    question: '我们正身处AI革命的正中央。Marc，你觉得现在大概走到了第几局？你最兴奋的点是什么？',
    answerSpeaker: 'Marc',
    answer: joinText([
      '首先，在我看来，这是我一生中见过最重大的技术革命。就量级而言，它显然已经超过互联网。真正可类比的对象，更接近微处理器、蒸汽机、电力，甚至轮子的发明。这是一个极大级别的技术转折。',
      '如果往前追溯，整个计算机产业过去80年基本都沿着“加法机”这条路径发展：我们造出了极端精密、计算能力惊人的机器，但它们并不擅长以人类喜欢的方式与人类互动，无法自然理解语言、语音和认知语境。',
      '可事实上，早在上世纪中叶，人们就已经提出了另一条路径，用神经网络去模拟人类认知。最早的神经网络论文在1943年就已经出现了。',
      '只是这条路在之后的几十年里，经历了长期的反复：一轮又一轮乐观预期，随后又一轮又一轮失望。直到2022年底ChatGPT出现，大家才突然意识到：原来这条路径真的可以跑通。某种意义上，我们现在只是这场80年长周期革命真正兑现成果后的第三年左右。',
      '而最让人兴奋的是，这项技术已经呈现出高度民主化的特征。今天，世界上最先进的一批AI能力，普通人直接就能体验。你可以打开不同产品，亲自感受它们的表现；视频、音乐等方向也同样如此。',
      '与此同时，硅谷对这波浪潮的反应极其迅猛。它最神奇的地方，不再是“制造硅”，而是它能持续回收前几波技术浪潮积累的人才、资本和热情，再把它们重新配置到新一代技术周期中。',
      '这正是当下AI正在发生的事情。对我来说，最直观的感受就是：我几乎每天都会被新的研究进展和新产品震惊到。一方面，我们持续跟踪底层科研进展，几乎天天都能看到让我拍案叫绝的新论文、新能力、新突破；另一方面，我们也不断看到新的创业公司和产品涌现，其中不少都让人有一种“下巴掉下来”的感觉。',
      '当然，这个过程不会是线性平滑的。它一定会伴随波动、失误、成本问题，以及过度承诺后的回调。某些阶段人们会发现，有些东西没有预想中好用，或者经济性还不成立。',
      '但即便如此，这项技术展现出来的能力仍然带有某种“魔法感”。无论是消费者还是企业，在真正上手之后，大多都能感受到这一点。而这种体验最终会反馈到商业指标上，你会看到收入的真实起飞。',
      '因此，从各个角度综合来看，我都很难相信这场浪潮已经到顶。相反，它给我的感觉是：一切都还在展开，产品本身还非常早期，未来一定会变得更加成熟和复杂。',
    ]),
  }),
  createDialogueSlice({
    startLabel: '09:11',
    endLabel: '15:52',
    titleZh: 'AI商业模式、扩散速度与成本结构',
    summaryZh: '智能按量卖，成本持续降',
    topicTitleZh: '智能经济',
    questionSpeaker: 'John',
    question: '关于AI，有一种常见质疑是：虽然收入规模很大，但支出也在同步膨胀，导致商业上似乎并不划算。你觉得这类讨论通常忽略了什么？',
    answerSpeaker: 'Marc',
    answer: joinText([
      '先从最基础的商业模式讲起。现在这个行业大体上有两种核心模式：一种是面向消费者的模式，另一种是企业/基础设施模式。',
      '先说消费者侧。很多人会问，AI是不是像当年的互联网革命？答案是：有点像，但又很不一样。互联网当年最大的问题，是我们必须先把互联网本身建出来。这意味着要铺光纤、建移动基站、出货大量智能手机、平板和电脑，把整个基础设施一层层搭好。这个过程花了几十年。',
      '而AI不同。今天互联网和智能终端已经部署完成，全球已有50亿到60亿人连在网络上。也就是说，AI不需要再重复建设一套新的物理底座，它直接借助现成的互联网进行扩散。你没法“下载”电力，也没法“下载”自来水系统，但你可以直接“下载”AI。正因为如此，AI消费产品的普及速度，理论上可以快到前所未有。',
      '而且它们的变现能力也很强。尤其让我印象深刻的是，这一代AI公司在定价上比过去的SaaS公司和消费互联网公司更大胆、更灵活。比如现在，个人用户每月200到300美元的订阅档位，已经逐渐开始变得常见。这种对高价格带的探索，其实是在主动放大市场空间。',
      '再看企业侧，本质问题只有一个：智能到底值多少钱？如果AI能提高客服评分、带来更多增购、降低流失、优化营销表现，或者让产品本身拥有新的智能能力，那么这些都对应着直接的商业回报。企业不是在为一个抽象概念买单，而是在为可量化的业务结果付费。',
      '在这背后，还有一个极其关键的因素：AI的核心商业模式，本质上有点像“按杯卖智能”，也就是按需购买Token。与此同时，AI的单位成本下降速度，甚至比摩尔定律还要快。所有输入要素按单位计算的成本，几乎都在快速下滑。这种成本的剧烈通缩，会进一步刺激更大规模的需求增长。',
      '至于大家担心的GPU短缺、芯片短缺、数据中心容量不足，这些问题确实存在，但从历史经验看，凡是能被物理复制的短缺，最终都会因为需求而被快速复制出来。短缺往往会引来过度扩张，过剩又会重新压低成本。未来十年，AI公司的单位成本大概率会像石头一样往下掉。',
      '所以，微观层面的盈利问题当然值得讨论，但从宏观方向上看，驱动力其实非常强。考虑到这项技术对消费者和企业的基础价值，再加上人们不断发现它在现实生活和商业中的新用途，我很难想象它不会继续高速增长，并创造出极其庞大的收入规模。',
    ]),
  }),
  createDialogueSlice({
    startLabel: '15:52',
    endLabel: '19:50',
    titleZh: 'GPU优化与模型规模演化',
    summaryZh: '小模型正快速追赶',
    topicTitleZh: '大小模型',
    questionSpeaker: 'Marc',
    question: 'AWS前不久提到，他们已经把GPU的使用寿命延长到了7年以上。这是否意味着GPU的经济寿命正在被拉长，优化空间也比前几个周期更大？',
    answerSpeaker: 'John',
    answer: joinText([
      '是的，这是一个非常关键的观察。而它其实会进一步引出另一个重要问题：大模型和小模型之间的分化。',
      '当前，大量数据中心建设仍然围绕大模型的训练和推理服务展开，这很自然。但与此同时，“小模型革命”也在同步发生。你会看到一个明显规律：领先模型推出之后，过上6到12个月，能力接近的小模型就会迅速出现。也就是说，大模型的新能力会很快被压缩到更小的参数规模里，并以更低成本重新提供出来。',
      '举个例子，中国的Kimi模型，在最新版本中已经表现出非常强的推理能力。按照一些基准测试，它已经逼近GPT-5这一档能力，而且可以被压缩到在普通电脑上本地运行。这意味着，一家企业如果希望拥有接近顶级的推理能力，但又不愿承担超高托管成本，那么它完全可能选择本地部署。',
      '我个人更倾向于认为，未来AI行业的结构会很像过去的计算机产业：少数最强、最昂贵的“上帝模型”会像超级计算机一样驻留在大型云端数据中心；与此同时，大量更小、更便宜、更容易部署的模型，会不断下沉到终端设备、嵌入式系统乃至各种物理对象中。最聪明的模型始终在塔尖，但数量最多、渗透最广的，反而会是那些小模型。',
    ]),
  }),
  createDialogueSlice({
    startLabel: '19:51',
    endLabel: '21:01',
    titleZh: 'AI芯片市场的周期与竞争态势',
    summaryZh: '短缺终会走向过剩',
    topicTitleZh: '芯片周期',
    questionSpeaker: 'Marc',
    question: '现在AI芯片仍处于供不应求的状态。你怎么看未来几年的供给变化和竞争格局？',
    answerSpeaker: 'John',
    answer: joinText([
      '从芯片产业历史来看，一个反复上演的规律就是：短缺最终会导向过剩。',
      '今天英伟达的成功，以及它获得的超高利润，已经成了整个芯片行业最明显的“集结号”。这会刺激所有竞争者加速跟进。AMD在追，超大规模云厂商也在自研，中国企业同样在推进自己的方案。',
      '英伟达毫无疑问是一家非常优秀的公司，它今天的位置和利润都配得上它的实力。但市场规律是，只要一个新芯片品类里出现了足够大的利润池，就一定会有越来越多玩家冲进来。',
      '按照这个逻辑推演，五年之后，AI芯片大概率会比现在便宜得多、也充足得多。对于我们投资的创业公司来说，这显然是重大利好，因为它会显著改善它们的单位经济模型。',
    ]),
  }),
  createDialogueSlice({
    startLabel: '21:02',
    endLabel: '24:14',
    titleZh: '从GPU到专用AI芯片的演进',
    summaryZh: '专用芯片与多元生态将起',
    topicTitleZh: '专用芯片',
    questionSpeaker: 'Marc',
    question: '现在也有不少初创公司开始尝试新的芯片架构设计。这会改变AI今天主要依赖GPU的局面吗？',
    answerSpeaker: 'John',
    answer: joinText([
      '其实，AI今天跑在GPU上，某种程度上带有很强的历史偶然性。GPU原本是图形处理器，是为了游戏、3D图形、CAD、图像处理这类任务而设计的。只是后来人们发现，它那种高度并行的架构碰巧特别适合另外两类高价值计算：一种是加密货币，另一种就是AI。',
      '过去30年，英伟达在GPU市场的长期竞争中胜出，最终拥有了最强的图形处理架构。后来事实证明，这套架构也恰好非常适合AI。所以今天AI建立在GPU之上，既有英伟达的前瞻布局，也有一定的时代巧合。',
      '但如果我们今天从零设计一套专门面向AI的芯片，很可能不会再照着传统GPU的完整形态去造，而是会开发更高效、更便宜、更适配AI负载的专用芯片。现在已经有不少初创公司在朝这个方向推进。起步当然很难，但它们未来可能通过独立做大，或者被大型公司并购，完成规模化。',
      '同时，韩国、日本、中国都在构建各自的芯片生态。未来AI芯片不会只有单一答案，而是会出现更加多元的选择，这将是未来几年非常值得关注的一场大战。',
    ]),
  }),
];

const quickSections: TranscriptSection[] = fullDialogueSlices.map((slice) => slice.section);

const curatedTranslationContent = buildStoredTranslationContent(
  sourceBundle,
  {
    quick: buildStoredQuickRendering(sourceBundle, quickSections, {
      translatedTitleZh: '马克·安德森的2026年展望：AI时间线、中美竞争与AI成本',
      summaryZh: '尽管公众在民调中对AI感到恐慌，但其实际使用行为却显示出人们正积极拥抱并依赖这项技术。',
      summary: 'Despite public fear in polls, actual behavior shows people are already embracing and relying on AI.',
      speakers: ['Jen', 'Marc', 'John'],
      model: CURATED_MODEL,
      geminiTranslationComplete: true,
      translationNeedsRefresh: false,
    }),
    full: buildStoredFullRendering(sourceBundle, fullDialogueSlices, {
      translatedTitleZh: '马克·安德森的2026年展望：AI时间线、中美竞争与AI成本',
      summaryZh: '尽管公众在民调中对AI感到恐慌，但其实际使用行为却显示出人们正积极拥抱并依赖这项技术。',
      summary: 'Despite public fear in polls, actual behavior shows people are already embracing and relying on AI.',
      speakers: ['Jen', 'Marc', 'John'],
      model: CURATED_MODEL,
      geminiTranslationComplete: true,
      translationNeedsRefresh: false,
    }),
  },
  CURATED_UPDATED_AT,
);

const curatedEntries: Array<{
  item: CuratedHotVideoItem;
  content: StoredTranslationContent;
}> = [
  {
    item: {
      videoId: CURATED_VIDEO_ID,
      title: '马克·安德森的2026年展望：AI时间线、中美竞争与AI成本',
      author: sourceBundle.sourceAuthor,
      thumbnailUrl: sourceBundle.thumbnailUrl,
      youtubeUrl: `https://www.youtube.com/watch?v=${CURATED_VIDEO_ID}`,
      viewCount: 0,
      updatedAt: CURATED_UPDATED_AT,
    },
    content: curatedTranslationContent,
  },
];

export function listCuratedHotVideoItems(): CuratedHotVideoItem[] {
  return curatedEntries.map((entry) => ({ ...entry.item }));
}

export function getCuratedHotTranslationContent(videoId: string): StoredTranslationContent | null {
  const normalizedVideoId = videoId.trim();
  const entry = curatedEntries.find((item) => item.item.videoId === normalizedVideoId);
  return entry?.content ?? null;
}
